// Copyright (C) Parity Technologies (UK) Ltd.
// This file is part of Individuality.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! People lite.
//!
//! Warning: This pallet must be configured with some spam prevention mechanism.
//! The spam prevention mechanism must limit how many calls the origin
//! `LitePerson` can do.
//! The recommended approach is to use pallet-origins-restriction.

#![cfg_attr(not(feature = "std"), no_std)]
#![allow(clippy::borrowed_box)]
extern crate alloc;
use alloc::{boxed::Box, vec};
use codec::Encode;
use frame_support::{
	dispatch::{DispatchResultWithPostInfo, PostDispatchInfo},
	traits::IsSubType,
};
use indiv_support::traits::{
	Alias, AppendOnlyMembers, CommunicationIdentifier, ConsumerRegistrar, Context, ContextualAlias,
	CountedMembers, Identifier, MembershipProver, RevisedContextualAlias, RingExponent, RingMode,
	Username, PEOPLE_LITE_IDENTIFIER,
};
use sp_runtime::{
	traits::{Dispatchable, IdentifyAccount, Verify},
	Saturating,
};
use types::{
	CryptoOf, LiteConsumerRegistrationParamsOf, LitePersonInfo, LitePersonInfoOf, MemberOf,
	ProofOf, RecognitionMethod, SignatureOf,
};
use verifiable::GenerateVerifiable;

#[cfg(feature = "runtime-benchmarks")]
pub mod benchmarking;
pub mod extension;
pub mod types;
pub mod weights;

#[cfg(test)]
mod mock;
#[cfg(test)]
mod tests;

pub use extension::{PeopleLiteAuth, PeopleLiteAuthData};
pub use pallet::*;
pub use weights::WeightInfo;

#[frame_support::pallet]
pub mod pallet {
	use super::*;
	use frame_support::{pallet_prelude::*, traits::EnsureOriginWithArg};
	use frame_system::pallet_prelude::*;

	pub const MSG_PREFIX: &[u8; 30] = b"pop:people-lite:register using";
	/// Fixed-width namespaced storage identifier for the lite people collection.
	pub use indiv_support::traits::PEOPLE_LITE_IDENTIFIER as LITE_PEOPLE_MEMBER_IDENTIFIER;
	/// Fixed-width namespaced proof context for lite people authorization; trailing spaces are
	/// intentional padding.
	pub const LITE_PEOPLE_AUTH_CONTEXT: &Context = b"pop:polkadot.network/plite-auth ";

	const LOG_TARGET: &str = "runtime::indiv-pallet-people-lite";

	#[pallet::pallet]
	pub struct Pallet<T>(_);

	#[pallet::config]
	pub trait Config:
		frame_system::Config<
		RuntimeOrigin: From<Origin<Self>> + OriginTrait<PalletsOrigin: TryInto<Origin<Self>>>,
		RuntimeCall: IsSubType<Call<Self>> + Dispatchable<PostInfo = PostDispatchInfo>,
	>
	{
		/// Weight information for extrinsics in this pallet.
		type WeightInfo: WeightInfo;

		/// The origin that can issue quotas to verifiers.
		type AttestationAllowanceManager: EnsureOrigin<Self::RuntimeOrigin>;

		/// Service handling lite people member collection lifecycle.
		type MemberService: AppendOnlyMembers
			+ MembershipProver<
				Crypto: GenerateVerifiable<
					Proof: Send + Sync + DecodeWithMemTracking,
					Signature: Send + Sync + DecodeWithMemTracking,
					Member: DecodeWithMemTracking,
				>,
			>;

		/// Owner location for the lite people collection.
		type CollectionOwner: Get<<Self::MemberService as AppendOnlyMembers>::Location>;

		/// Ring exponent used for the lite people collection.
		#[pallet::constant]
		type LiteRingExponent: Get<RingExponent>;

		/// Onboarding size used when creating the lite people collection.
		#[pallet::constant]
		type LiteOnboardingSize: Get<u32>;

		/// Signature generated by lite people and used by verifiers to claim attestations on their
		/// behalf.
		type AttestationSignature: Verify<Signer: IdentifyAccount<AccountId = Self::AccountId>>
			+ Parameter;

		/// Lite personhood consumer service. Lite people can be automatically registered when
		/// attested.
		type LiteConsumerRegistrar: ConsumerRegistrar<Self::AccountId, Error: Into<DispatchError>>;

		/// A set of helper functions for benchmarking.
		///
		/// The default configuration `()` uses the `SR25519` signature schema.
		#[cfg(feature = "runtime-benchmarks")]
		type BenchmarkHelper: BenchmarkHelper<Self::AccountId, Self::AttestationSignature>;
	}

	#[pallet::origin]
	#[derive(
		CloneNoBound,
		PartialEqNoBound,
		EqNoBound,
		DebugNoBound,
		Encode,
		Decode,
		MaxEncodedLen,
		TypeInfo,
		DecodeWithMemTracking,
	)]
	#[scale_info(skip_type_params(T))]
	pub enum Origin<T: Config> {
		/// A person litely recognized.
		LitePerson(T::AccountId),
		/// A privacy-preserving lite alias.
		LiteAlias(RevisedContextualAlias),
	}

	#[pallet::storage]
	pub type LitePeople<T: Config> =
		StorageMap<_, Blake2_128Concat, T::AccountId, LitePersonInfoOf<T>>;

	/// Conversion of a lite contextual alias to an account ID.
	#[pallet::storage]
	pub type AliasToAccount<T: Config> =
		StorageMap<_, Blake2_128Concat, ContextualAlias, T::AccountId, OptionQuery>;

	/// Conversion of an account ID to a lite contextual alias.
	#[pallet::storage]
	pub type AccountToAlias<T: Config> =
		StorageMap<_, Blake2_128Concat, T::AccountId, RevisedContextualAlias, OptionQuery>;

	/// Whether the lite people member collection has been created.
	#[pallet::storage]
	pub type LitePeopleCollectionCreated<T: Config> = StorageValue<_, bool, ValueQuery>;

	/// Number of attestations available to distribute for a verifier account id.
	#[pallet::storage]
	pub type AttestationAllowance<T: Config> =
		StorageMap<_, Blake2_128Concat, T::AccountId, u32, ValueQuery>;

	#[pallet::event]
	#[pallet::generate_deposit(pub(super) fn deposit_event)]
	pub enum Event<T: Config> {
		/// All attestation allowance has been removed for the verifier.
		AllAttestationAllowanceCleared { verifier: T::AccountId },
		/// Attestation allowance was increased for an account by `count` attestations.
		AttestationAllowanceIncreased { account: T::AccountId, count: u32 },
		/// A new lite person was registered through attestation.
		PersonAttested { candidate: T::AccountId, verifier: T::AccountId },
		/// A lite person was registered as a consumer.
		ConsumerRegistered { account: T::AccountId },
		/// An alias-to-account mapping was set or updated.
		AliasAccountSet { alias: ContextualAlias, account: T::AccountId },
		/// An alias-to-account mapping was removed.
		AliasAccountUnset { alias: ContextualAlias, account: T::AccountId },
	}

	#[pallet::extra_constants]
	impl<T: Config> Pallet<T> {
		/// The number of blocks of tolerance we allow for an alias setup transaction.
		pub fn account_setup_block_tolerance() -> BlockNumberFor<T> {
			600u32.into()
		}
	}

	#[pallet::error]
	pub enum Error<T> {
		/// No attestation allowance.
		NoAttestationAllowance,
		/// The signature created by the candidate's account is invalid.
		InvalidAttestationSignature,
		/// The signature created by the candidate's ring vrf key is invalid.
		InvalidProofOfOwnership,
		/// The candidate is already registered.
		AlreadyRegistered,
		/// The ring VRF key is already enrolled by another lite person.
		KeyAlreadyInUse,
		/// The account is already in use.
		AccountInUse,
		/// The alias <-> account mapping is already set and current.
		AliasAccountAlreadySet,
		/// The alias <-> account mapping is not set.
		AliasAccountNotSet,
		/// The requested alias setup block window is invalid for the current block.
		CallBlockOutOfRange,
		/// The alias context is invalid.
		InvalidAliasContext,
		/// The lite people member collection has not been initialized yet.
		LitePeopleCollectionNotCreated,
	}

	#[pallet::hooks]
	impl<T: Config> Hooks<BlockNumberFor<T>> for Pallet<T> {
		fn on_poll(_n: BlockNumberFor<T>, weight: &mut frame_support::weights::WeightMeter) {
			// Use at most 50% of available weight to be cautious about weight
			// underestimates.
			let budget = weight.remaining() / 2;
			let mut meter = frame_support::weights::WeightMeter::with_limit(budget);
			Self::do_on_poll(&mut meter);
			weight.consume(meter.consumed());
		}
	}

	#[pallet::call]
	impl<T: Config> Pallet<T> {
		/// Grant some attestation allowance to an account so they can attest people.
		///
		/// The origin must be `AttestationAllowanceManager`.
		///
		/// - `account`: The account to grant attestations to.
		/// - `count`: The number of attestations to grant.
		#[pallet::call_index(0)]
		#[pallet::weight(<T as Config>::WeightInfo::increase_attestation_allowance())]
		pub fn increase_attestation_allowance(
			origin: OriginFor<T>,
			account: T::AccountId,
			count: u32,
		) -> DispatchResult {
			T::AttestationAllowanceManager::ensure_origin(origin)?;
			let mut available = AttestationAllowance::<T>::get(&account);
			available = available.saturating_add(count);
			AttestationAllowance::<T>::insert(&account, available);
			Self::deposit_event(Event::AttestationAllowanceIncreased { account, count });
			Ok(())
		}

		/// Clear all attestation allowance for an account.
		///
		/// The origin must be `AttestationAllowanceManager`.
		///
		/// - `account`: The account to remove all attestations from.
		#[pallet::call_index(1)]
		#[pallet::weight(<T as Config>::WeightInfo::clear_attestation_allowance())]
		pub fn clear_attestation_allowance(
			origin: OriginFor<T>,
			account: T::AccountId,
		) -> DispatchResult {
			T::AttestationAllowanceManager::ensure_origin(origin)?;
			AttestationAllowance::<T>::remove(&account);
			Self::deposit_event(Event::AllAttestationAllowanceCleared { verifier: account });

			Ok(())
		}

		/// Attest an account.
		///
		/// The origin must be signed by an account and have some attestation allowance left.
		///
		/// The authority will have to get two signatures from the user:
		/// - one created using their account key attesting to the ownership of the `candidate`
		///   account;
		/// - one created using their ring-vrf key attesting to the ownership of the `ring_vrf_key`
		///   key.
		///
		/// The message to be signed by both keys from which the signatures are generated is created
		/// by concatenating the bytes "pop:people-lite:register using" with the encoded bytes of
		/// the user's account (`candidate`), and the encoded bytes of the ring VRF key
		/// (`ring_vrf_key`).
		///
		/// On success, this call:
		/// - stores lite registration data in `LitePeople`,
		/// - adds the user's ring VRF key to the lite member collection.
		///
		/// The lite member collection must already have been initialized by `on_poll`.
		///
		/// - `candidate`: The candidate to be recognized as a lite person.
		/// - `candidate_signature`: The signature, provided by the candidate, to allow the attester
		///   to complete the registration process on their behalf.
		/// - `ring_vrf_key`: The ring VRF key to be associated with the lite person.
		/// - `ring_vrf_key_signature`: The ring VRF signature, provided by the candidate, to allow
		///   the attester to complete the registration process. This also prove the ownership of
		///   the ring VRF key by the candidate.
		/// - consumer_registration: Optional parameter which can contain the necessary information
		///   to forward a consumer registration request to the `LiteConsumerRegistrar` service. If
		///   present, it also contains a signature created by the user in order to validate the
		///   intent. More information on the signing payload generation available in
		///   [types::LiteConsumerRegistrationParams::signing_payload].
		#[pallet::call_index(2)]
		#[pallet::weight({ if consumer_registration.is_some() {
			<T as Config>::WeightInfo::attest().saturating_add(<T as Config>::WeightInfo::register_lite_consumer())
		} else {
			<T as Config>::WeightInfo::attest()
		}})]
		pub fn attest(
			origin: OriginFor<T>,
			candidate: T::AccountId,
			candidate_signature: T::AttestationSignature,
			ring_vrf_key: MemberOf<T>,
			proof_of_ownership: SignatureOf<T>,
			consumer_registration: Option<LiteConsumerRegistrationParamsOf<T>>,
		) -> DispatchResultWithPostInfo {
			let verifier = ensure_signed(origin)?;
			ensure!(!LitePeople::<T>::contains_key(&candidate), Error::<T>::AlreadyRegistered);
			ensure!(
				T::MemberService::member_status(LITE_PEOPLE_MEMBER_IDENTIFIER, &ring_vrf_key)
					.is_none(),
				Error::<T>::KeyAlreadyInUse,
			);
			let available = AttestationAllowance::<T>::get(&verifier)
				.checked_sub(1)
				.ok_or(Error::<T>::NoAttestationAllowance)?;
			Self::ensure_lite_collection_created()?;

			let msg = candidate.using_encoded(|c_bytes| {
				ring_vrf_key.using_encoded(|rv_bytes| [&MSG_PREFIX[..], c_bytes, rv_bytes].concat())
			});
			ensure!(
				CryptoOf::<T>::verify_signature(&proof_of_ownership, &msg[..], &ring_vrf_key),
				Error::<T>::InvalidProofOfOwnership,
			);
			ensure!(
				candidate_signature.verify(&msg[..], &candidate),
				Error::<T>::InvalidAttestationSignature,
			);

			if available > 0 {
				AttestationAllowance::<T>::insert(&verifier, available);
			} else {
				AttestationAllowance::<T>::remove(&verifier);
			}

			let ring_vrf_key_for_member_service = ring_vrf_key.clone();
			LitePeople::<T>::insert(
				&candidate,
				LitePersonInfo {
					ring_vrf_key,
					method: RecognitionMethod::UniqueDevice(verifier.clone()),
				},
			);
			T::MemberService::add_members(
				LITE_PEOPLE_MEMBER_IDENTIFIER,
				vec![ring_vrf_key_for_member_service],
			)?;
			frame_system::Pallet::<T>::inc_sufficients(&candidate);
			Self::deposit_event(Event::PersonAttested { candidate, verifier: verifier.clone() });

			// If provided with additional params and signature to register as lite consumer,
			// forward the registration to the `ConsumerRegistrar` service.
			if let Some(params) = consumer_registration {
				Self::register_lite_consumer(params, &verifier)?;
			}

			Ok(Pays::No.into())
		}

		#[pallet::call_index(5)]
		#[pallet::weight(
			<T as Config>::WeightInfo::dispatch_as_signer()
			.saturating_add(call.get_dispatch_info().call_weight)
		)]
		pub fn dispatch_as_signer(
			mut origin: OriginFor<T>,
			call: Box<T::RuntimeCall>,
		) -> DispatchResultWithPostInfo {
			let who = match origin.clone().into_caller().try_into() {
				Ok(Origin::LitePerson(account)) => account,
				_ => return Err(DispatchError::BadOrigin.into()),
			};

			origin.set_caller_from(frame_system::RawOrigin::Signed(who));

			call.dispatch(origin)
		}

		/// Set the account associated with a lite alias.
		///
		/// The call is valid from `valid_at_block` until
		/// `valid_at_block + account_setup_block_tolerance`.
		#[pallet::call_index(6)]
		#[pallet::weight(<T as Config>::WeightInfo::set_alias_account())]
		pub fn set_alias_account(
			origin: OriginFor<T>,
			account: T::AccountId,
			valid_at_block: BlockNumberFor<T>,
		) -> DispatchResultWithPostInfo {
			let rev_ca = EnsureRevisedLiteAlias::<T>::ensure_origin(origin)?;
			let current_block = frame_system::Pallet::<T>::block_number();
			let block_tolerance = Self::account_setup_block_tolerance();
			ensure!(
				valid_at_block <= current_block &&
					current_block <= valid_at_block.saturating_add(block_tolerance),
				Error::<T>::CallBlockOutOfRange
			);
			ensure!(
				rev_ca.ca.context == *LITE_PEOPLE_AUTH_CONTEXT,
				Error::<T>::InvalidAliasContext
			);
			ensure!(!LitePeople::<T>::contains_key(&account), Error::<T>::AccountInUse);

			let old_account = AliasToAccount::<T>::get(&rev_ca.ca);
			let old_rev_ca = old_account.as_ref().and_then(AccountToAlias::<T>::get);
			let needs_revision = old_rev_ca.is_some_and(|old_rev_ca| {
				old_rev_ca.revision != rev_ca.revision || old_rev_ca.ring != rev_ca.ring
			});

			ensure!(
				old_account.as_ref() != Some(&account) || needs_revision,
				Error::<T>::AliasAccountAlreadySet
			);

			match old_account.as_ref() {
				// No previous binding: create a new alias -> account mapping.
				None => {
					ensure!(!AccountToAlias::<T>::contains_key(&account), Error::<T>::AccountInUse);
					frame_system::Pallet::<T>::inc_sufficients(&account);
				},
				// Bound to a different account: swap the mapping and move sufficients.
				Some(old_account) if old_account != &account => {
					ensure!(!AccountToAlias::<T>::contains_key(&account), Error::<T>::AccountInUse);
					frame_system::Pallet::<T>::dec_sufficients(old_account);
					AccountToAlias::<T>::remove(old_account);
					frame_system::Pallet::<T>::inc_sufficients(&account);
				},
				// Same account: only the alias revision/ring is being refreshed.
				Some(_) => {},
			}

			AccountToAlias::<T>::insert(&account, &rev_ca);
			AliasToAccount::<T>::insert(&rev_ca.ca, &account);
			Self::deposit_event(Event::AliasAccountSet { alias: rev_ca.ca, account });

			if old_account.is_none() || needs_revision {
				Ok(Pays::No.into())
			} else {
				Ok(Pays::Yes.into())
			}
		}

		#[pallet::call_index(7)]
		#[pallet::weight(<T as Config>::WeightInfo::unset_alias_account())]
		pub fn unset_alias_account(origin: OriginFor<T>) -> DispatchResult {
			let rev_ca = EnsureRevisedLiteAlias::<T>::ensure_origin(origin)?;
			let account =
				AliasToAccount::<T>::take(&rev_ca.ca).ok_or(Error::<T>::AliasAccountNotSet)?;
			AccountToAlias::<T>::remove(&account);
			frame_system::Pallet::<T>::dec_sufficients(&account);
			Self::deposit_event(Event::AliasAccountUnset { alias: rev_ca.ca, account });
			Ok(())
		}
	}

	impl<T: Config> Pallet<T> {
		/// Inner body of `on_poll`. Driven by an inner `WeightMeter` capped at 50% of the
		/// outer remaining budget; the outer meter consumes whatever this body actually
		/// uses.
		fn do_on_poll(weight: &mut frame_support::weights::WeightMeter) {
			if weight.try_consume(T::WeightInfo::on_poll_initialize_check_condition()).is_err() {
				return;
			}

			if LitePeopleCollectionCreated::<T>::get() {
				return;
			}

			if weight.try_consume(T::WeightInfo::on_poll_initialize()).is_err() {
				return;
			}

			if let Err(e) = Self::ensure_lite_collection_exists() {
				log::warn!(
					target: LOG_TARGET,
					"failed to initialize lite people collection during on_poll: {e:?}",
				);
			}
		}

		/// Register a lite person as a consumer by calling into the `LiteConsumerRegistrar`
		/// service.
		///
		/// This action requires user consent, provided through a signature verified in this
		/// function. The signing payload is constructed by encoding, in order, the tuple of:
		/// - the user's account
		/// - the verifier's account
		/// - the user's identifier_key
		/// - the user's chosen username, without the `.` separator and any following digits
		/// - the user's chosen reserved_username, as an `Option`
		///
		/// For more information about the signing payload, check
		/// [types::LiteConsumerRegistrationParams::signing_payload].
		pub fn register_lite_consumer(
			params: LiteConsumerRegistrationParamsOf<T>,
			verifier: &T::AccountId,
		) -> DispatchResult {
			// Verify the candidate's signature for the consumer registration.
			ensure!(
				params.signature.verify(&params.signing_payload(verifier)[..], &params.account),
				Error::<T>::InvalidAttestationSignature,
			);
			let account = params.account.clone();
			T::LiteConsumerRegistrar::register_lite_consumer(
				params.account,
				params.identifier_key,
				params.username,
				params.reserved_username,
			)
			.map_err(|e| e.into())?;
			Self::deposit_event(Event::ConsumerRegistered { account });
			Ok(())
		}

		/// Ensure the one-time lite people member collection exists.
		pub(crate) fn ensure_lite_collection_exists() -> DispatchResult {
			if LitePeopleCollectionCreated::<T>::get() {
				return Ok(());
			}

			T::MemberService::create_collection(
				T::CollectionOwner::get(),
				LITE_PEOPLE_MEMBER_IDENTIFIER,
				T::LiteOnboardingSize::get(),
				RingMode::AppendOnly,
				T::LiteRingExponent::get(),
				None,
			)?;
			LitePeopleCollectionCreated::<T>::put(true);
			Ok(())
		}

		/// Ensure the lite people member collection was already initialized by `on_poll`.
		pub(crate) fn ensure_lite_collection_created() -> DispatchResult {
			ensure!(
				LitePeopleCollectionCreated::<T>::get(),
				Error::<T>::LitePeopleCollectionNotCreated
			);
			Ok(())
		}
	}

	/// Guard to ensure that the given origin is a lite person. The account of the lite person is
	/// provided on success.
	pub struct EnsureLitePerson<T>(PhantomData<T>);
	impl<T: Config> EnsureOrigin<OriginFor<T>> for EnsureLitePerson<T> {
		type Success = T::AccountId;

		fn try_origin(o: OriginFor<T>) -> Result<Self::Success, OriginFor<T>> {
			match o.clone().into_caller().try_into() {
				Ok(Origin::LitePerson(account)) => Ok(account),
				_ => Err(o),
			}
		}

		#[cfg(feature = "runtime-benchmarks")]
		fn try_successful_origin() -> Result<OriginFor<T>, ()> {
			let who = frame_benchmarking::account::<T::AccountId>("successful_origin", 0, 0);
			Ok(Origin::LitePerson(who).into())
		}
	}

	/// Guard to ensure that the given origin is a revised lite alias.
	///
	/// The revised contextual alias is provided on success. The revision can be used to detect
	/// whether the alias binding may have become stale.
	pub struct EnsureRevisedLiteAlias<T>(PhantomData<T>);
	impl<T: Config> EnsureOrigin<OriginFor<T>> for EnsureRevisedLiteAlias<T> {
		type Success = RevisedContextualAlias;

		fn try_origin(o: OriginFor<T>) -> Result<Self::Success, OriginFor<T>> {
			match o.clone().into_caller().try_into() {
				Ok(Origin::LiteAlias(rev_ca)) => Ok(rev_ca),
				_ => Err(o),
			}
		}

		#[cfg(feature = "runtime-benchmarks")]
		fn try_successful_origin() -> Result<OriginFor<T>, ()> {
			Ok(Origin::LiteAlias(RevisedContextualAlias {
				revision: 0,
				ring: 0,
				ca: ContextualAlias { alias: [1; 32], context: [0; 32] },
			})
			.into())
		}
	}

	/// Guard yielding `(Alias, Identifier)` when the origin carries a lite-people proof matching
	/// the supplied context. The identifier is always `PEOPLE_LITE_IDENTIFIER`. Designed to be
	/// composed with `EnsurePersonalAliasInContextWithCollection` (people-multi) under
	/// `EitherOf` so a caller can admit either collection and learn which one authenticated.
	pub struct EnsureLiteAliasInContextWithCollection<T>(PhantomData<T>);
	impl<T: Config> EnsureOriginWithArg<OriginFor<T>, Context>
		for EnsureLiteAliasInContextWithCollection<T>
	{
		type Success = (Alias, Identifier);

		fn try_origin(o: OriginFor<T>, arg: &Context) -> Result<Self::Success, OriginFor<T>> {
			match o.clone().into_caller().try_into() {
				Ok(Origin::LiteAlias(rev_ca)) if &rev_ca.ca.context == arg =>
					Ok((rev_ca.ca.alias, *PEOPLE_LITE_IDENTIFIER)),
				_ => Err(o),
			}
		}

		#[cfg(feature = "runtime-benchmarks")]
		fn try_successful_origin(context: &Context) -> Result<OriginFor<T>, ()> {
			Ok(Origin::LiteAlias(RevisedContextualAlias {
				revision: 0,
				ring: 0,
				ca: ContextualAlias { alias: [1; 32], context: *context },
			})
			.into())
		}
	}

	impl<T: Config> CountedMembers for EnsureLiteAliasInContextWithCollection<T> {
		fn active_count() -> u32 {
			T::MemberService::active_count(LITE_PEOPLE_MEMBER_IDENTIFIER)
		}

		#[cfg(feature = "runtime-benchmarks")]
		fn set_active_count(count: u32) {
			T::MemberService::set_active_count(LITE_PEOPLE_MEMBER_IDENTIFIER, count)
		}
	}

	#[cfg(feature = "runtime-benchmarks")]
	pub trait BenchmarkHelper<AccountId, Signature> {
		fn sign_message(message: &[u8]) -> (AccountId, Signature);
	}
	#[cfg(feature = "runtime-benchmarks")]
	impl BenchmarkHelper<sp_runtime::AccountId32, sp_runtime::MultiSignature> for () {
		fn sign_message(message: &[u8]) -> (sp_runtime::AccountId32, sp_runtime::MultiSignature) {
			use sp_core::Pair;
			use sp_runtime::traits::IdentifyAccount;
			let entropy = [1u8; 32];
			let pair = sp_core::ed25519::Pair::from_seed(&entropy);
			let account = pair.public().into_account().into();
			let secret = ed25519_zebra::SigningKey::from(entropy);
			let signature = sp_core::ed25519::Signature::from_raw(secret.sign(message).into());
			(account, signature.into())
		}
	}
}
