[package]
name = "origin-rs"
version = "0.9.9"
edition = "2021"
description = "Origin SDK"
license = "GPL-3.0-or-later"

[lib]
name = "oc"
path = "src/lib.rs"

[features]
default = ["dynamic-sdk", "static-codegen"]
dynamic-sdk = []
static-codegen = []
unstable-light-client = []

[dependencies]
anyhow = "1.0"
base64 = "0.22"
bs58 = { version = "0.5", default-features = false, features = ["alloc"] }
codec = { workspace = true, features = ["std"] }
origin-primitives = { path = "../origin/primitives" }
futures = "0.3"
getrandom = "0.2"
hex = "0.4"
log = "0.4"
scale-info = { workspace = true, features = ["std"] }
scale-value = { version = "0.18", features = ["serde", "__std"] }
serde = { workspace = true, features = ["derive", "std"] }
env_logger = "0.11"
serde_json = { workspace = true, features = ["std"] }
sp-core = { workspace = true, features = ["std"] }
sp-runtime = { workspace = true, features = ["std"] }
scale-decode = { version = "0.16", default-features = false, features = ["derive"] }
scale-type-resolver = { version = "0.2", features = ["scale-info"] }
lru = "0.12"
subxt = { version = "0.44", default-features = true, features = ["jsonrpsee", "native", "reconnecting-rpc-client"] }
subxt-metadata = "0.44"
thiserror = "1"
tokio = { version = "1.40", features = ["macros", "rt-multi-thread", "sync"] }
jsonrpsee-core = "0.24.10"
jsonrpsee-client-transport = "0.24.10"
url = "2.5"
