[package]
name = "origin-rs"
description = "Origin SDK"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[lib]
name = "oc"
path = "src/lib.rs"

[features]
default = ["ws"]
ws = ["subxt/jsonrpsee"]
mock = []
unstable-light-client = ["subxt/unstable-light-client"]

[dependencies]
anyhow = { workspace = true, optional = false }
backoff = { workspace = true }
codec = { workspace = true, features = ["std"] }
futures = { workspace = true }
origin-primitives = { workspace = true, features = ["std"] }
pallet-orbis-attestation-runtime-api = { workspace = true, features = ["std"] }
pallet-orbis-names-runtime-api = { workspace = true, features = ["std"] }
orbis-storage-runtime-api = { workspace = true, features = ["std"] }
orbis-identity-personhood-runtime-api = { workspace = true, features = ["std"] }
serde = { workspace = true, features = ["derive", "std"] }
serde_json = { workspace = true, features = ["std"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "sync", "time"] }
tracing = { workspace = true }
subxt = { workspace = true, default-features = false, features = ["jsonrpsee", "native", "reconnecting-rpc-client"] }
subxt-metadata = { workspace = true, optional = true }
hex = { workspace = true }
scale-value = { version = "0.18", default-features = false, features = ["serde"] }
scale-decode = { version = "0.16", features = ["derive"] }
sp-core = { workspace = true, features = ["std"] }
sp-crypto-hashing = { workspace = true, features = ["std"] }
scale-info = { workspace = true, features = ["std"] }
sp-runtime = { workspace = true, features = ["std"] }
frame-support = { workspace = true, features = ["std"] }
async-trait = "0.1"
base64 = "0.22"
clap = { version = "4.5", features = ["derive"] }
ciborium = "0.2.2"
sha2 = { workspace = true, features = ["std"] }
hkdf = { workspace = true }
ed25519-dalek = { workspace = true, features = ["std"] }
chacha20poly1305 = "0.10.1"
unicode-normalization = "0.1.24"
rand = { workspace = true, features = ["std", "std_rng"] }

[dev-dependencies]
serde_json = { workspace = true }
env_logger = "0.11"
kvdb = { workspace = true }
kvdb-rocksdb = { workspace = true }
proptest = "1"
tempfile = { workspace = true }
cddl = "0.10.6"
blake2 = { workspace = true, features = ["std"] }
ed25519-dalek = { workspace = true, features = ["std"] }
