
[workspace.package]
version = "0.9.7"
authors = ['Dhiway Networks <info@dhiway.com>']
edition = "2021"
homepage = "https://cord.network"
repository = "https://github.com/dhiway/cord"
license = "GPL-3.0"

[workspace]
resolver = "2"

members = [
	"node/cli",
	"node/rpc",
	"node/inspect",
	"node/testing",
	"origin/container",
	"origin/container/coretime",
	"origin/container/constants",
	"origin/relay",
	"origin/relay/cli",
	"origin/relay/common",
	"origin/relay/runtime",
	"origin/relay/runtime/constants",
	"pallets/collection",
	"pallets/identity",
	"pallets/identifier",
	"pallets/network-membership",
	"pallets/node-authorization",
	"pallets/offences",
	"pallets/registry",
	"pallets/remote-proxy",
	"pallets/runtime-upgrade",
	"pallets/session-benchmarking",
	"primitives/cord",
	"primitives/network-membership",
	"runtimes/common",
	"runtimes/common/api/assets",
	"runtimes/common/api/identifier",
	"runtimes/common/authorities",
	"runtimes/braid/",
	"runtimes/braid/constants",
	"runtimes/loom/",
	"runtimes/loom/constants",
	"runtimes/weave/",
	"runtimes/weave/constants",
	"test-utils/cli",
	"pallets/profile",
	"pallets/entry",
]
default-members = ["node/cli", "origin/relay", "origin/container"]

[workspace.lints.rust]
suspicious_double_ref_op = { level = "allow", priority = 2 }
unexpected_cfgs = { level = "warn", check-cfg = [
	'cfg(build_opt_level, values("3"))',
	'cfg(build_profile, values("debug", "release"))',
	'cfg(enable_alloc_error_handler)',
	'cfg(fuzzing)',
	'cfg(cord_runtime)',
] }

[workspace.lints.clippy] # `cord_runtime` is a common `cfg` condition name used in the repo.
all = { level = "allow", priority = 0 }
bind_instead_of_map = { level = "allow", priority = 2 }              # stylistic
borrowed-box = { level = "allow", priority = 2 }                     # Reasonable to fix this one
complexity = { level = "warn", priority = 1 }
correctness = { level = "warn", priority = 1 }
default_constructed_unit_structs = { level = "allow", priority = 2 } # stylistic
derivable_impls = { level = "allow", priority = 2 }                  # false positives
eq_op = { level = "allow", priority = 2 }                            # In tests we test equality.
erasing_op = { level = "allow", priority = 2 }                       # E.g. 0 * DOLLARS
extra-unused-type-parameters = { level = "allow", priority = 2 }     # stylistic
identity-op = { level = "allow", priority = 2 }                      # One case where we do 0 +
if-same-then-else = { level = "allow", priority = 2 }
needless-lifetimes = { level = "allow", priority = 2 }               # generated code
needless_option_as_deref = { level = "allow", priority = 2 }         # false positives
nonminimal-bool = { level = "allow", priority = 2 }                  # maybe
option-map-unit-fn = { level = "allow", priority = 2 }               # stylistic
stable_sort_primitive = { level = "allow", priority = 2 }            # prefer stable sort
too-many-arguments = { level = "allow", priority = 2 }               # (Turning this on would lead to)
type_complexity = { level = "allow", priority = 2 }                  # raison d'etre
unit_arg = { level = "allow", priority = 2 }                         # stylistic
unnecessary_cast = { level = "allow", priority = 2 }                 # Types may change
useless_conversion = { level = "allow", priority = 2 }               # Types may change
while_immutable_condition = { level = "allow", priority = 2 }        # false positives
zero-prefixed-literal = { level = "allow", priority = 2 }            # 00_1000_000

[workspace.dependencies]
Inflector = { version = "0.11.4" }
aes-gcm = { version = "0.10" }
ahash = { version = "0.8.2" }
alloy-core = { version = "0.8.15", default-features = false }
always-assert = { version = "0.1" }
anyhow = { version = "1.0.81", default-features = false }
approx = { version = "0.5.1" }
asset-test-utils = { version = "23.0.0" }
assets-common = { version = "0.21.0", default-features = false }
authority-discovery-primitives = { version = "36.0.0", default-features = false, package = "sp-authority-discovery" }
babe-primitives = { version = "0.42.1", default-features = false, package = "sp-consensus-babe" }
beefy-primitives = { version = "24.1.0", default-features = false, package = "sp-consensus-beefy" }
aquamarine = { version = "0.5.0" }
arbitrary = { version = "1.3.2" }
ark-bls12-377 = { version = "0.4.0", default-features = false }
ark-bls12-377-ext = { version = "0.4.1", default-features = false }
ark-bls12-381 = { version = "0.4.0", default-features = false }
ark-bls12-381-ext = { version = "0.4.1", default-features = false }
ark-bw6-761 = { version = "0.4.0", default-features = false }
ark-bw6-761-ext = { version = "0.4.1", default-features = false }
ark-ec = { version = "0.4.2", default-features = false }
ark-ed-on-bls12-377 = { version = "0.4.0", default-features = false }
ark-ed-on-bls12-377-ext = { version = "0.4.1", default-features = false }
ark-ed-on-bls12-381-bandersnatch = { version = "0.4.0", default-features = false }
ark-ed-on-bls12-381-bandersnatch-ext = { version = "0.4.1", default-features = false }
ark-scale = { version = "0.0.12", default-features = false }
ark-vrf = { version = "0.1.0", default-features = false }
array-bytes = { version = "6.2.2", default-features = false }
arrayvec = { version = "0.7.4" }
assert_cmd = { version = "2.0.14" }
assert_matches = { version = "1.5.0" }
async-channel = { version = "1.8.0" }
async-std = { version = "1.9.0" }
async-trait = { version = "0.1.88" }
asynchronous-codec = { version = "0.6" }
backoff = { version = "0.4" }
backtrace = { version = "0.3.71" }
binary-merkle-tree = { version = "16.0.0", default-features = false }
bincode = { version = "1.3.3" }
bip39 = { package = "parity-bip39", version = "2.0.1", default-features = false }
bitflags = { version = "1.3.2" }
bitvec = { version = "1.0.1", default-features = false }
blake2 = { version = "0.10.4", default-features = false }
blake2b_simd = { version = "1.0.2", default-features = false }
blake3 = { version = "1.5" }
bn = { package = "substrate-bn", version = "0.6", default-features = false }
bounded-collections = { version = "0.2.3", default-features = false }
bounded-vec = { version = "0.7" }
bs58 = { version = "0.5.1", default-features = false }
build-helper = { version = "0.1.1" }
byte-slice-cast = { version = "1.2.1", default-features = false }
byteorder = { version = "1.3.2", default-features = false }
bytes = { version = "1.4.0", default-features = false }
cargo_metadata = { version = "0.15.4" }
cfg-expr = { version = "0.15.5" }
cfg-if = { version = "1.0" }
chain-spec-builder = { version = "10.0.0", default-features = false, package = "staging-chain-spec-builder" }
chrono = { version = "0.4.31" }
cid = { version = "0.9.0" }
clap = { version = "4.5.13" }
clap_complete = { version = "4.5.13" }
cmd_lib = { version = "1.9.5" }
coarsetime = { version = "0.1.22" }
codec = { version = "3.7.4", default-features = false, package = "parity-scale-codec" }
color-eyre = { version = "0.6.3", default-features = false }
color-print = { version = "0.3.4" }
colored = { version = "2.0.4" }
comfy-table = { version = "7.1.4", default-features = false }
console = { version = "0.15.8" }
const-hex = { version = "1.10.0", default-features = false }
cpu-time = { version = "1.0.0" }
criterion = { version = "0.5.1", default-features = false }
cumulus-pallet-aura-ext = { version = "0.20.0", default-features = false }
cumulus-pallet-parachain-system = { version = "0.20.0", default-features = false }
cumulus-pallet-session-benchmarking = { version = "21.0.0", default-features = false }
cumulus-pallet-xcm = { version = "0.19.1", default-features = false }
cumulus-pallet-xcmp-queue = { version = "0.20.0", default-features = false }
cumulus-primitives-aura = { version = "0.17.0", default-features = false }
cumulus-primitives-core = { version = "0.18.1", default-features = false }
cumulus-primitives-utility = { version = "0.20.0", default-features = false }
curve25519-dalek = { version = "4.1.3" }
derive-syn-parse = { version = "0.2.0" }
derive-where = { version = "1.2.7" }
derive_more = { version = "0.99.17", default-features = false }
digest = { version = "0.10.3", default-features = false }
directories = { version = "5.0.1" }
dlmalloc = { version = "0.2.4" }
docify = { version = "0.2.9" }
dyn-clonable = { version = "0.9.0" }
dyn-clone = { version = "1.0.16" }
ed25519-dalek = { version = "2.1", default-features = false }
ed25519-zebra = { version = "4.0.3", default-features = false }
either = { version = "1.8.1", default-features = false }
emulated-integration-tests-common = { version = "20.0.1" }
enumflags2 = { version = "0.7.11" }
enumn = { version = "0.1.13" }
env_logger = { version = "0.11.2" }
ethabi = { version = "2.0.0", default-features = false, package = "ethabi-decode" }
ethbloom = { version = "0.14.1", default-features = false }
ethereum-types = { version = "0.15.1", default-features = false }
exit-future = { version = "0.2.0" }
expander = { version = "2.0.0" }
fatality = { version = "0.1.1" }
fdlimit = { version = "0.3.0" }
femme = { version = "2.2.1" }
filetime = { version = "0.2.16" }
finality-grandpa = { version = "0.16.3", default-features = false }
fnv = { version = "1.0.6" }
fork-tree = { git = "https://github.com/dhiway/sdk", default-features = false, branch = "release-v1.18.2" }
forwarded-header-value = { version = "0.1.1" }
fraction = { version = "0.13.1" }
frame = { version = "0.9.1", default-features = false, package = "polkadot-sdk-frame" }
frame-benchmarking = { version = "40.0.0", default-features = false }
frame-benchmarking-cli = { version = "47.0.0", default-features = false }
frame-benchmarking-pallet-pov = { version = "30.0.0", default-features = false }
frame-election-provider-support = { version = "40.1.0", default-features = false }
frame-executive = { version = "40.0.0", default-features = false }
frame-metadata = { version = "20.0.0", default-features = false }
frame-metadata-hash-extension = { version = "0.8.0", default-features = false }
frame-support = { version = "40.1.0", default-features = false }
frame-support-procedural = { version = "33.0.0", default-features = false }
frame-support-procedural-tools = { version = "40.1.0", default-features = false }
frame-support-procedural-tools-derive = { version = "12.0.0", default-features = false }
frame-system = { version = "40.1.0", default-features = false }
frame-system-benchmarking = { version = "40.0.0", default-features = false }
frame-system-rpc-runtime-api = { version = "36.0.0", default-features = false }
frame-try-runtime = { version = "0.46.0", default-features = false }
frame-support-test = { git = "https://github.com/dhiway/sdk", branch = "release-v1.18.2" }
fs4 = { version = "0.7.0" }
fs_extra = { version = "1.3.0" }
futures = { version = "0.3.31" }
futures-timer = { version = "3.0.2" }
futures-util = { version = "0.3.30", default-features = false }
fluent-uri = { version = "0.3.2", default-features = false }
generate-bags = { version = "40.0.0", default-features = false }
gethostname = { version = "0.2.3" }
git2 = { version = "0.20.0", default-features = false }
glob = { version = "0.3" }
governor = { version = "0.6.0" }
gum = { version = "19.0.0", default-features = false, package = "tracing-gum" }
gum-proc-macro = { version = "5.0.0", default-features = false, package = "tracing-gum-proc-macro" }
handlebars = { version = "5.1.0" }
hash-db = { version = "0.16.0", default-features = false }
hash256-std-hasher = { version = "0.15.2", default-features = false }
hex = { version = "0.4.3", default-features = false }
hex-literal = { version = "0.4.1", default-features = false }
hkdf = { version = "0.12.0" }
hmac = { version = "0.12.1" }
honggfuzz = { version = "0.5.55" }
http = { version = "1.1" }
http-body = { version = "1", default-features = false }
http-body-util = { version = "0.1.2", default-features = false }
hyper = { version = "1.3.1", default-features = false }
hyper-rustls = { version = "0.27.3", default-features = false, features = [
	"http1",
	"http2",
	"logging",
	"ring",
	"rustls-native-certs",
	"tls12",
] }
hyper-util = { version = "0.1.5", default-features = false }
impl-serde = { version = "0.5.0", default-features = false }
impl-trait-for-tuples = { version = "0.2.2" }
indexmap = { version = "2.7.1" }
indicatif = { version = "0.17.7" }
integer-sqrt = { version = "0.1.2" }
ip_network = { version = "0.4.1" }
is-terminal = { version = "0.4.9" }
is_executable = { version = "1.0.1" }
isahc = { version = "1.2" }
itertools = { version = "0.11" }
jemalloc_pprof = { version = "0.4" }
jobserver = { version = "0.1.26" }
jsonpath_lib = { version = "0.3" }
jsonrpsee = { version = "0.24.3" }
jsonrpsee-core = { version = "0.24.3" }
k256 = { version = "0.13.4", default-features = false }
kvdb = { version = "0.13.0" }
kvdb-memorydb = { version = "0.13.0" }
kvdb-rocksdb = { version = "0.19.0" }
kvdb-shared-tests = { version = "0.11.0" }
landlock = { version = "0.3.0" }
libc = { version = "0.2.155" }
libfuzzer-sys = { version = "0.4" }
libp2p = { version = "0.54.1" }
libp2p-identity = { version = "0.2.9" }
libsecp256k1 = { version = "0.7.0", default-features = false }
libp2p-kad = { version = "0.46.2", default-features = false }
linked-hash-map = { version = "0.5.4" }
linked_hash_set = { version = "0.1.4" }
linregress = { version = "0.5.1" }
lite-json = { version = "0.2.0", default-features = false }
litep2p = { version = "0.9.4", features = ["websocket"] }
log = { version = "0.4.22", default-features = false }
macro_magic = { version = "0.5.1" }
maplit = { version = "1.0.2" }
memmap2 = { version = "0.9.3" }
memory-db = { version = "0.32.0", default-features = false }
merkleized-metadata = { version = "0.4.0" }
merlin = { version = "3.0", default-features = false }
metered = { version = "0.6.1", default-features = false, package = "prioritized-metered-channel" }
milagro-bls = { version = "1.5.4", default-features = false, package = "snowbridge-milagro-bls" }
mixnet = { version = "0.7.0" }
mmr-gadget = { version = "44.0.0", default-features = false, package = "mmr-gadget" }
mmr-lib = { version = "0.5.2", package = "ckb-merkle-mountain-range" }
mmr-rpc = { version = "40.0.0", default-features = false, package = "mmr-rpc" }
mockall = { version = "0.13.1" }
multiaddr = { version = "0.18.1" }
multihash = { version = "0.19.1", default-features = false }
multistream-select = { version = "0.13.0" }
names = { version = "0.14.0", default-features = false }
nix = { version = "0.29.0" }
nohash-hasher = { version = "0.2.0" }
novelpoly = { version = "2.0.0", package = "reed-solomon-novelpoly" }
num-bigint = { version = "0.4.3", default-features = false }
num-format = { version = "0.4.3" }
num-integer = { version = "0.1.46", default-features = false }
num-rational = { version = "0.4.1" }
num-traits = { version = "0.2.17", default-features = false }
num_cpus = { version = "1.13.1" }
once_cell = { version = "1.19.0" }
orchestra = { version = "0.4.0", default-features = false }
origin-primitives = { version = "18.1.0", default-features = false, package = "polkadot-primitives" }
pallet-alliance = { version = "39.1.0", default-features = false }
pallet-asset-conversion = { version = "22.0.0", default-features = false }
pallet-asset-conversion-ops = { version = "0.8.0", default-features = false }
pallet-asset-conversion-tx-payment = { version = "22.0.0", default-features = false }
pallet-assets-freezer = { version = "0.7.0", default-features = false }
pallet-assets-holder = { version = "0.2.1", default-features = false }
pallet-asset-rate = { version = "19.0.0", default-features = false }
pallet-asset-rewards = { version = "0.2.0", default-features = false }
pallet-asset-tx-payment = { version = "40.0.0", default-features = false }
pallet-assets = { version = "42.0.0", default-features = false }
pallet-atomic-swap = { version = "40.1.0", default-features = false }
pallet-aura = { version = "39.0.0", default-features = false }
pallet-authority-discovery = { version = "40.0.0", default-features = false }
pallet-authorship = { version = "40.0.0", default-features = false }
pallet-babe = { version = "40.0.0", default-features = false }
pallet-bags-list = { version = "39.1.0", default-features = false }
pallet-bags-list-remote-tests = { version = "4.0.0", default-features = false }
pallet-balances = { version = "41.1.0", default-features = false }
pallet-beefy = { version = "41.1.0", default-features = false }
pallet-beefy-mmr = { version = "41.0.0", default-features = false }
pallet-bounties = { version = "39.0.0", default-features = false }
pallet-bridge-grandpa = { version = "0.20.0", default-features = false }
pallet-bridge-messages = { version = "0.20.1", default-features = false }
pallet-bridge-parachains = { version = "0.20.0", default-features = false }
pallet-bridge-relayers = { version = "0.20.0", default-features = false }
pallet-broker = { version = "0.19.1", default-features = false }
pallet-child-bounties = { version = "39.0.0", default-features = false }
pallet-collective-content = { version = "0.18.0", default-features = false }
pallet-contracts = { version = "40.1.0", default-features = false }
pallet-contracts-fixtures = { version = "1.0.0", default-features = false }
pallet-contracts-mock-network = { version = "17.0.0", default-features = false }
pallet-contracts-proc-macro = { version = "23.0.3", default-features = false }
pallet-contracts-uapi = { version = "14.0.0", default-features = false }
pallet-collator-selection = { version = "21.0.0", default-features = false }
pallet-collective = { version = "40.1.0", default-features = false }
pallet-conviction-voting = { version = "40.1.0", default-features = false }
pallet-core-fellowship = { version = "24.1.0", default-features = false }
pallet-democracy = { version = "40.1.0", default-features = false }
pallet-election-provider-multi-phase = { version = "39.1.0", default-features = false }
pallet-election-provider-support-benchmarking = { version = "39.0.0", default-features = false }
pallet-elections-phragmen = { version = "41.1.0", default-features = false }
pallet-fast-unstake = { version = "39.0.0", default-features = false }
pallet-glutton = { version = "26.0.0", default-features = false }
pallet-grandpa = { version = "40.0.0", default-features = false }
pallet-identity = { version = "40.1.0", default-features = false }
pallet-im-online = { version = "39.1.0", default-features = false }
pallet-indices = { version = "40.0.0", default-features = false }
pallet-insecure-randomness-collective-flip = { version = "28.0.0", default-features = false }
pallet-membership = { version = "40.0.0", default-features = false }
pallet-message-queue = { version = "43.1.0", default-features = false }
pallet-meta-tx = { version = "0.2.0", default-features = false }
pallet-mixnet = { version = "0.16.1", default-features = false }
pallet-mmr = { version = "40.0.0", default-features = false }
pallet-multisig = { version = "40.1.0", default-features = false }
pallet-nft-fractionalization = { version = "23.0.0", default-features = false }
pallet-nfts = { version = "34.1.0", default-features = false }
pallet-nfts-runtime-api = { version = "26.0.0", default-features = false }
pallet-nis = { version = "40.0.0", default-features = false }
pallet-migrations = { version = "10.1.0", default-features = false }
pallet-nomination-pools = { version = "38.1.0", default-features = false }
pallet-nomination-pools-benchmarking = { version = "38.0.0", default-features = false }
pallet-nomination-pools-runtime-api = { version = "36.0.0", default-features = false }
pallet-offences = { version = "39.0.0", default-features = false }
pallet-offences-benchmarking = { version = "40.0.0", default-features = false }
pallet-paged-list = { version = "0.18.0", default-features = false }
pallet-parameters = { version = "0.11.0", default-features = false }
pallet-preimage = { version = "40.0.0", default-features = false }
pallet-proxy = { version = "40.1.0", default-features = false }
pallet-ranked-collective = { version = "40.1.0", default-features = false }
pallet-recovery = { version = "40.0.0", default-features = false }
pallet-referenda = { version = "40.1.0", default-features = false }
pallet-remark = { version = "40.0.0", default-features = false }
pallet-root-offences = { version = "37.0.0", default-features = false }
pallet-root-testing = { version = "16.0.0", default-features = false }
pallet-safe-mode = { version = "21.1.0", default-features = false }
pallet-salary = { version = "25.0.0", default-features = false }
pallet-scored-pool = { version = "40.0.0", default-features = false }
pallet-scheduler = { version = "41.0.0", default-features = false }
pallet-session = { version = "40.0.0", default-features = false }
pallet-session-benchmarking = { version = "40.0.0", default-features = false }
pallet-skip-feeless-payment = { version = "15.0.0", default-features = false }
pallet-society = { version = "40.1.0", default-features = false }
pallet-staking = { version = "40.1.0", default-features = false }
pallet-statement = { version = "22.0.0", default-features = false }
pallet-tips = { version = "39.0.0", default-features = false }
pallet-transaction-storage = { version = "39.0.0", default-features = false }
pallet-transaction-payment-rpc = { version = "43.0.0", default-features = false }
pallet-tx-pause = { version = "21.1.0", default-features = false }
pallet-delegated-staking = { version = "7.0.0", default-features = false }
pallet-staking-reward-curve = { version = "12.0.0" }
pallet-staking-reward-fn = { version = "22.0.1", default-features = false }
pallet-staking-runtime-api = { version = "26.0.0", default-features = false }
pallet-state-trie-migration = { version = "44.1.0", default-features = false }
pallet-sudo = { version = "40.0.0", default-features = false }
pallet-timestamp = { version = "39.0.0", default-features = false }
pallet-transaction-payment = { version = "40.0.0", default-features = false }
pallet-transaction-payment-rpc-runtime-api = { version = "40.0.0", default-features = false }
pallet-treasury = { version = "39.0.0", default-features = false }
pallet-uniques = { version = "40.1.0", default-features = false }
pallet-utility = { version = "40.0.0", default-features = false }
pallet-verify-signature = { version = "0.3.0", default-features = false }
pallet-vesting = { version = "40.1.0", default-features = false }
pallet-whitelist = { version = "39.0.0", default-features = false }
pallet-xcm = { version = "19.1.0", default-features = false }
pallet-xcm-benchmarks = { version = "20.0.0", default-features = false }
pallet-xcm-bridge-hub = { version = "0.16.1", default-features = false }
pallet-xcm-bridge-hub-router = { version = "0.18.0", default-features = false }
polkadot-cli = { version = "23.0.0", default-features = false }
polkadot-core-primitives = { version = "17.1.0", default-features = false }
polkadot-node-core-pvf = { version = "22.0.0", default-features = false }
polkadot-node-core-pvf-common = { version = "19.0.0", default-features = false }
polkadot-node-core-pvf-execute-worker = { version = "19.0.0", default-features = false }
polkadot-node-core-pvf-prepare-worker = { version = "19.0.0", default-features = false }
polkadot-node-metrics = { version = "22.0.0", default-features = false }
polkadot-node-primitives = { version = "19.0.0", default-features = false }
polkadot-omni-node-lib = { git = "https://github.com/dhiway/sdk", default-features = false, branch = "release-v1.18.2" }
polkadot-overseer = { version = "22.0.0", default-features = false }
parachain-info = { version = "0.20.0", default-features = false, package = "staging-parachain-info" }
parachains-common = { version = "21.0.0", default-features = false }
polkadot-service = { version = "23.0.0", default-features = false }
parachains-runtimes-test-utils = { version = "22.0.0" }
paste = { version = "1.0.14" }
polkadot-parachain-primitives = { version = "16.1.0", default-features = false }
polkadot-primitives = { version = "18.1.0", default-features = false }
polkadot-runtime-common = { version = "19.1.0", default-features = false }
primitive-types = { version = "0.12.2", default-features = false, features = [
	"num-traits",
] }
parity-bytes = { version = "0.1.2", default-features = false }
parity-db = { version = "0.4.12" }
parity-wasm = { version = "0.45.0" }
parking_lot = { version = "0.12.1", default-features = false }
partial_sort = { version = "0.2.0" }
pbkdf2 = { version = "0.12.2", default-features = false }
pin-project = { version = "1.1.3" }
polkavm = { version = "0.18.0", default-features = false }
polkavm-derive = "0.18.0"
polkavm-linker = "0.18.0"
portpicker = { version = "0.1.1" }
pretty_assertions = { version = "1.3.0" }
proc-macro-crate = { version = "3.0.0" }
proc-macro-warning = { version = "1.0.0", default-features = false }
proc-macro2 = { version = "1.0.86" }
procfs = { version = "0.16.0" }
prometheus = { version = "0.13.0", default-features = false }
prometheus-endpoint = { version = "0.17.2", default-features = false, package = "substrate-prometheus-endpoint" }
prometheus-parse = { version = "0.2.2" }
prost = { version = "0.12.4" }
prost-build = { version = "0.13.2" }
pyroscope = { version = "0.5.8" }
pyroscope_pprofrs = { version = "0.2.8" }
quick_cache = { version = "0.3" }
quickcheck = { version = "1.0.3", default-features = false }
quote = { version = "1.0.37" }
rand = { version = "0.8.5", default-features = false }
rand_chacha = { version = "0.3.1", default-features = false }
rand_core = { version = "0.6.2" }
rand_distr = { version = "0.4.3" }
rand_pcg = { version = "0.3.1" }
rbtag = { version = "0.3" }
ref-cast = { version = "1.0.23" }
regex = { version = "1.10.2" }
remote-externalities = { version = "0.50.0", default-features = false, package = "frame-remote-externalities" }
runtime-parachains = { version = "19.1.0", default-features = false, package = "polkadot-runtime-parachains" }
ripemd = { version = "0.1.3", default-features = false }
rlp = { version = "0.6.1", default-features = false }
rpassword = { version = "7.0.0" }
rstest = { version = "0.18.2" }
rustc-hash = { version = "1.1.0" }
rustc-hex = { version = "2.1.0", default-features = false }
rustix = { version = "0.36.7", default-features = false }
rustls = { version = "0.23.18", default-features = false, features = [
	"logging",
	"ring",
	"std",
	"tls12",
] }
rustversion = { version = "1.0.17" }
rusty-fork = { version = "0.3.0", default-features = false }
safe-mix = { version = "1.0", default-features = false }
sc-allocator = { version = "31.0.0", default-features = false }
sc-authority-discovery = { version = "0.49.0", default-features = false }
sc-basic-authorship = { version = "0.49.0", default-features = false }
sc-block-builder = { version = "0.44.0", default-features = false }
sc-chain-spec = { version = "42.0.0" }
sc-chain-spec-derive = { version = "12.0.0", default-features = false }
sc-cli = { version = "0.51.0", default-features = false }
sc-client-api = { version = "39.0.0", default-features = false }
sc-client-db = { version = "0.46.0", default-features = false }
sc-consensus = { version = "0.48.0", default-features = false }
sc-consensus-aura = { version = "0.49.0", default-features = false }
sc-consensus-babe = { version = "0.49.0", default-features = false }
sc-consensus-babe-rpc = { version = "0.49.0", default-features = false }
sc-consensus-beefy = { version = "28.0.0", default-features = false }
sc-consensus-beefy-rpc = { version = "28.0.0", default-features = false }
sc-consensus-epochs = { version = "0.48.0", default-features = false }
sc-consensus-grandpa = { version = "0.34.0", default-features = false }
sc-consensus-grandpa-rpc = { version = "0.34.0", default-features = false }
sc-consensus-manual-seal = { version = "0.50.0", default-features = false }
sc-consensus-pow = { version = "0.48.0", default-features = false }
sc-consensus-slots = { version = "0.48.0", default-features = false }
sc-executor = { version = "0.42.0", default-features = false }
sc-executor-common = { version = "0.38.0", default-features = false }
sc-executor-polkavm = { version = "0.35.0", default-features = false }
sc-executor-wasmtime = { version = "0.38.0", default-features = false }
sc-informant = { version = "0.48.0", default-features = false }
sc-keystore = { version = "35.0.0", default-features = false }
sc-mixnet = { version = "0.19.0", default-features = false }
sc-network = { version = "0.49.1" }
sc-network-common = { version = "0.48.0", default-features = false }
sc-network-gossip = { version = "0.49.0", default-features = false }
sc-network-light = { version = "0.48.0", default-features = false }
sc-network-statement = { version = "0.31.0", default-features = false }
sc-network-sync = { version = "0.48.0", default-features = false }
sc-network-test = { version = "0.8.0", default-features = false }
sc-network-transactions = { version = "0.48.0", default-features = false }
sc-network-types = { version = "0.15.3", default-features = false }
sc-offchain = { version = "44.0.0", default-features = false }
sc-proposer-metrics = { version = "0.20.0", default-features = false }
sc-rpc = { version = "44.0.0", default-features = false }
sc-rpc-api = { version = "0.48.0", default-features = false }
sc-rpc-server = { version = "21.0.0", default-features = false }
sc-rpc-spec-v2 = { version = "0.49.1", default-features = false }
sc-runtime-test = { version = "2.0.0", default-features = false }
sc-runtime-utilities = { version = "0.2.0", default-features = false }
sc-service = { version = "0.50.0", default-features = false }
sc-service-test = { version = "2.0.0", default-features = false }
sc-state-db = { version = "0.38.0", default-features = false }
sc-statement-store = { version = "21.0.0", default-features = false }
sc-storage-monitor = { version = "0.24.0", default-features = false }
sc-sync-state-rpc = { version = "0.49.0", default-features = false }
sc-sysinfo = { version = "42.0.0", default-features = false }
sc-telemetry = { version = "28.1.0", default-features = false }
sc-tracing = { version = "39.0.0", default-features = false }
sc-tracing-proc-macro = { version = "11.1.0", default-features = false }
sc-transaction-pool = { version = "39.0.0", default-features = false }
sc-transaction-pool-api = { version = "39.0.0", default-features = false }
sc-utils = { version = "18.0.1", default-features = false }
scale-info = { version = "2.11.6", default-features = false }
separator = { version = "0.4.1" }
schemars = { version = "0.8.13", default-features = false }
schnellru = { version = "0.2.3" }
schnorrkel = { version = "0.11.4", default-features = false }
seccompiler = { version = "0.4.0" }
secp256k1 = { version = "0.28.0", default-features = false }
secrecy = { version = "0.8.0", default-features = false }
serde = { version = "1.0.214", default-features = false }
serde-big-array = { version = "0.3.2" }
serde_derive = { version = "1.0.117" }
serde_json = { version = "1.0.132", default-features = false }
serde_yaml = { version = "0.9" }
sha1 = { version = "0.10.6" }
sha2 = { version = "0.10.7", default-features = false }
sha3 = { version = "0.10.0", default-features = false }
shlex = { version = "1.3.0" }
slot-range-helper = { version = "17.0.0", default-features = false }
slotmap = { version = "1.0" }
smallvec = { version = "1.11.0", default-features = false }
smoldot = { version = "0.11.0", default-features = false }
smoldot-light = { version = "0.9.0", default-features = false }
soketto = { version = "0.8.0" }
sp-api = { version = "36.0.1", default-features = false }
sp-api-proc-macro = { version = "22.0.0", default-features = false }
sp-application-crypto = { version = "40.1.0", default-features = false }
sp-arithmetic = { version = "26.1.0", default-features = false }
sp-authority-discovery = { version = "36.0.0", default-features = false }
sp-block-builder = { version = "36.0.0", default-features = false }
sp-blockchain = { version = "39.0.0", default-features = false }
sp-consensus = { version = "0.42.0", default-features = false }
sp-consensus-aura = { version = "0.42.0", default-features = false }
sp-consensus-babe = { version = "0.42.1", default-features = false }
sp-consensus-beefy = { version = "24.1.0", default-features = false }
sp-consensus-grandpa = { version = "23.1.0", default-features = false }
sp-consensus-pow = { version = "0.42.0", default-features = false }
sp-consensus-slots = { version = "0.42.1", default-features = false }
sp-core = { version = "36.1.0", default-features = false }
sp-core-hashing = { version = "16.0.0", default-features = false }
sp-core-hashing-proc-macro = { version = "16.0.0", default-features = false }
sp-crypto-ec-utils = { version = "0.15.0", default-features = false }
sp-crypto-hashing = { version = "0.1.0", default-features = false }
sp-crypto-hashing-proc-macro = { version = "0.1.0", default-features = false }
sp-database = { version = "10.0.0", default-features = false }
sp-debug-derive = { version = "14.0.0", default-features = false }
sp-externalities = { version = "0.30.0", default-features = false }
sp-genesis-builder = { version = "0.17.0", default-features = false }
sp-inherents = { version = "36.0.0", default-features = false }
sp-io = { version = "40.0.1", default-features = false }
sp-keyring = { version = "41.0.0", default-features = false }
sp-keystore = { version = "0.42.0", default-features = false }
sp-maybe-compressed-blob = { version = "11.0.0", default-features = false }
sp-metadata-ir = { version = "0.10.0", default-features = false }
sp-mixnet = { version = "0.14.0", default-features = false }
sp-mmr-primitives = { version = "36.1.0", default-features = false }
sp-npos-elections = { version = "36.1.0", default-features = false }
sp-offchain = { version = "36.0.0", default-features = false }
sp-panic-handler = { version = "13.0.2", default-features = false }
sp-rpc = { version = "34.0.0", default-features = false }
sp-runtime = { version = "41.1.0", default-features = false }
sp-runtime-interface = { version = "29.0.1", default-features = false }
sp-runtime-interface-proc-macro = { version = "18.0.0", default-features = false }
sp-runtime-interface-test-wasm = { version = "2.0.0", default-features = false }
sp-session = { version = "38.1.0", default-features = false }
sp-staking = { version = "38.0.0", default-features = false }
sp-std = { version = "14.0.0", default-features = false }
sp-state-machine = { version = "0.45.0", default-features = false }
sp-statement-store = { version = "20.1.0", default-features = false }
# sp-std = { version = "14.0.0", default-features = false }
sp-storage = { version = "22.0.0", default-features = false }
sp-test-primitives = { version = "2.0.0", default-features = false }
sp-timestamp = { version = "36.0.0", default-features = false }
sp-tracing = { version = "17.1.0", default-features = false }
sp-transaction-pool = { version = "36.0.0", default-features = false }
sp-transaction-storage-proof = { version = "36.1.0", default-features = false }
sp-trie = { version = "39.1.0", default-features = false }
sp-version = { version = "39.0.0", default-features = false }
sp-version-proc-macro = { version = "15.0.0", default-features = false }
sp-wasm-interface = { version = "21.0.1", default-features = false }
sp-weights = { version = "31.1.0", default-features = false }
subkey = { version = "24.0.0", default-features = false, package = "subkey" }
substrate-bip39 = { version = "0.6.0", default-features = false }
substrate-build-script-utils = { version = "11.0.0", default-features = false }
substrate-frame-rpc-support = { version = "44.0.0", default-features = false }
substrate-frame-rpc-system = { version = "43.0.0", default-features = false }
substrate-rpc-client = { version = "0.48.0", default-features = false }
substrate-state-trie-migration-rpc = { version = "42.0.0", default-features = false }
substrate-wasm-builder = { version = "26.0.1" }

spinners = { version = "4.1.1" }
ss58-registry = { version = "1.34.0", default-features = false }
ssz_rs = { version = "0.9.0", default-features = false }
ssz_rs_derive = { version = "0.9.0", default-features = false }
static_assertions = { version = "1.1.0", default-features = false }
static_init = { version = "1.0.3" }
strum = { version = "0.26.3", default-features = false }
substrate-cli-test-utils = { git = "https://github.com/dhiway/sdk", branch = "release-v1.18.2" }
substrate-test-client = { git = "https://github.com/dhiway/sdk", default-features = false, branch = "release-v1.18.2" }
subxt = { version = "0.38.1", default-features = false }
subxt-metadata = { version = "0.38.0", default-features = false }
subxt-signer = { version = "0.38" }
syn = { version = "2.0.87" }
sysinfo = { version = "0.30" }
tar = { version = "0.4" }
tempfile = { version = "3.8.1" }
test-log = { version = "0.2.14" }
thiserror = { version = "1.0.64" }
thousands = { version = "0.2.0" }
threadpool = { version = "1.7" }
tikv-jemalloc-ctl = { version = "0.5.0" }
tikv-jemallocator = { version = "0.5.0" }
time = { version = "0.3" }
tiny-keccak = { version = "2.0.2" }
tokio = { version = "1.40.0", default-features = false }
tokio-retry = { version = "0.3.0" }
tokio-stream = { version = "0.1.14" }
tokio-test = { version = "0.4.4" }
tokio-tungstenite = { version = "0.26.2" }
tokio-util = { version = "0.7.8" }
toml = { version = "0.8.12" }
toml_edit = { version = "0.19" }
tower = { version = "0.4.13" }
tower-http = { version = "0.5.2" }
tracing = { version = "0.1.37", default-features = false }
tracing-core = { version = "0.1.32", default-features = false }
tracing-futures = { version = "0.2.4" }
tracing-log = { version = "0.2.0" }
tracing-subscriber = { version = "0.3.18" }
tracking-allocator = { version = "2.0.0", default-features = false, package = "staging-tracking-allocator" }
trie-bench = { version = "0.40.0" }
trie-db = { version = "0.30.0", default-features = false }
trie-root = { version = "0.18.0", default-features = false }
trie-standardmap = { version = "0.16.0" }
trybuild = { version = "1.0.103" }
tt-call = { version = "1.0.8" }
tuplex = { version = "0.1", default-features = false }
twox-hash = { version = "1.6.3", default-features = false }
txtesttool = { version = "0.4.0", package = "substrate-txtesttool" }
unsigned-varint = { version = "0.7.2" }
url = { version = "2.5.4" }
void = { version = "1.0.2" }
w3f-bls = { version = "0.1.3", default-features = false }
wait-timeout = { version = "0.2" }
walkdir = { version = "2.5.0" }
wasm-instrument = { version = "0.4", default-features = false }
wasm-opt = { version = "0.116" }
wasm-timer = { version = "0.2.5" }
wasmi = { version = "0.32.3", default-features = false }
wasmtime = { version = "8.0.1", default-features = false }
wat = { version = "1.0.0" }
x25519-dalek = { version = "2.0" }
xcm = { version = "16.1.0", default-features = false, package = "staging-xcm" }
xcm-builder = { version = "20.1.0", default-features = false, package = "staging-xcm-builder" }
xcm-emulator = { version = "0.19.2" }
xcm-executor = { version = "19.1.0", default-features = false, package = "staging-xcm-executor" }
xcm-runtime-apis = { version = "0.7.0", default-features = false }
zeroize = { version = "1.7.0", default-features = false }
zstd = { version = "0.12.4", default-features = false }

# local dependencies
authority-membership = { path = "runtimes/common/authorities", default-features = false }
cord-identifier-runtime-api = { path = "runtimes/common/api/identifier", default-features = false }
cord-node-cli = { path = "node/cli", default-features = false }
cord-primitives = { path = "primitives/cord", default-features = false }
network-membership = { path = "primitives/network-membership", default-features = false }
cord-braid-runtime = { path = "runtimes/braid", default-features = false }
cord-braid-runtime-constants = { path = "runtimes/braid/constants", default-features = false }
cord-runtime-common = { path = "runtimes/common", default-features = false }
cord-loom-runtime = { path = "runtimes/loom", default-features = false }
cord-loom-runtime-constants = { path = "runtimes/loom/constants", default-features = false }
cord-origin-relay-staging-runtime = { path = "origin/relay/runtime" }
cord-origin-relay-staging-runtime-constants = { path = "origin/relay/runtime/constants", default-features = false }
cord-origin-relay-cli = { path = "origin/relay/cli", default-features = false }
cord-weave-runtime = { path = "runtimes/weave", default-features = false }
cord-weave-runtime-constants = { path = "runtimes/weave/constants", default-features = false }
cord-node-service = { path = "node/service", default-features = false }
cord-node-inspect = { path = "node/inspect", default-features = false }
cord-node-rpc = { path = "node/rpc", default-features = false }
cord-node-testing = { path = "node/testing", default-features = false }
cord-cli-test-utils = { path = "test-utils/cli", default-features = false }
pallet-council-membership = { path = 'pallets/membership/', default-features = false }
pallet-collection = { path = 'pallets/collection/', default-features = false }
pallet-network-membership = { path = 'pallets/network-membership', default-features = false }
pallet-registry = { path = 'pallets/registry/', default-features = false }
pallet-remote-proxy = { path = 'pallets/remote-proxy/', default-features = false }
pallet-entry = { path = 'pallets/entry', default-features = false }
pallet-runtime-upgrade = { path = 'pallets/runtime-upgrade', default-features = false }
pallet-cord-identity = { path = 'pallets/identity', default-features = false }
pallet-cord-offences = { path = 'pallets/offences', default-features = false }
pallet-cord-node-authorization = { path = "pallets/node-authorization", default-features = false }
pallet-network-score = { path = 'pallets/network-score', default-features = false }
pallet-cord-session-benchmarking = { path = 'pallets/session-benchmarking', default-features = false }
pallet-assets-runtime-api = { path = "runtimes/common/api/assets", default-features = false }
pallet-identifier = { path = "pallets/identifier", default-features = false }
pallet-registries = { path = "pallets/registries", default-features = false }
pallet-entries = { path = "pallets/entries", default-features = false }
pallet-schema-accounts = { path = "pallets/schema-accounts", default-features = false }
pallet-namespace = { path = 'pallets/namespace', default-features = false }
pallet-profile = { path = "pallets/profile", default-features = false }
people-origin-runtime = { path = "system-parachains/people" }
relay-common = { path = "origin/relay/common", default-features = false }
cord-origin-container = { path = "origin/container", default-features = false }
cord-origin-system-chains-staging-constants = { path = "origin/container/constants", default-features = false }
# cord-origin-asset-staging-runtime = { path = "origin/container/asset", default-features = false }
cord-origin-coretime-staging-runtime = { path = "origin/container/coretime", default-features = false }

[profile.release]
panic = 'unwind'
opt-level = 3

[profile.production]
codegen-units = 1
inherits = "release"
lto = true

[profile.dev]
split-debuginfo = "unpacked"

# make sure dev builds with backtrace do
# not slow us down
[profile.dev.package.backtrace]
inherits = "release"

[profile.testnet]
inherits = "release"
debug = 1               # debug symbols are useful for profilers
debug-assertions = true
overflow-checks = true

[profile.dev.package]
ark-vrf = { opt-level = 3 }
blake2 = { opt-level = 3 }
blake2b_simd = { opt-level = 3 }
chacha20poly1305 = { opt-level = 3 }
cranelift-codegen = { opt-level = 3 }
cranelift-wasm = { opt-level = 3 }
crc32fast = { opt-level = 3 }
crossbeam-deque = { opt-level = 3 }
crypto-mac = { opt-level = 3 }
curve25519-dalek = { opt-level = 3 }
ed25519-dalek = { opt-level = 3 }
futures-channel = { opt-level = 3 }
hash-db = { opt-level = 3 }
hashbrown = { opt-level = 3 }
hmac = { opt-level = 3 }
httparse = { opt-level = 3 }
integer-sqrt = { opt-level = 3 }
keccak = { opt-level = 3 }
libm = { opt-level = 3 }
librocksdb-sys = { opt-level = 3 }
libsecp256k1 = { opt-level = 3 }
libz-sys = { opt-level = 3 }
mio = { opt-level = 3 }
nalgebra = { opt-level = 3 }
num-bigint = { opt-level = 3 }
parking_lot = { opt-level = 3 }
parking_lot_core = { opt-level = 3 }
percent-encoding = { opt-level = 3 }
polkavm-linker = { opt-level = 3 }
primitive-types = { opt-level = 3 }
ring = { opt-level = 3 }
rustls = { opt-level = 3 }
sha2 = { opt-level = 3 }
sha3 = { opt-level = 3 }
smallvec = { opt-level = 3 }
snow = { opt-level = 3 }
substrate-bip39 = { opt-level = 3 }
twox-hash = { opt-level = 3 }
uint = { opt-level = 3 }
wasmi = { opt-level = 3 }
x25519-dalek = { opt-level = 3 }
yamux = { opt-level = 3 }
zeroize = { opt-level = 3 }
