# This is the build stage for CORD. Here we create the binary in a temporary image.
FROM docker.io/paritytech/ci-linux:production as builder

LABEL maintainer="engineering@dhiway.com"
ARG PROFILE=production

WORKDIR /build
COPY . /build

RUN cargo build --locked --profile ${PROFILE}

# test
# RUN cargo test --release --all
