[package]
name = "cord-subxt-sdk"
version = "0.1.0"
edition = "2021"
description = "Origin SDK prototype built on Subxt"
license = "GPL-3.0-or-later"

[lib]
name = "oc"
path = "src/lib.rs"

[features]
default = []
unstable-light-client = []

[dependencies]
base64 = "0.22"
bs58 = { version = "0.5", default-features = false, features = ["alloc"] }
codec = { workspace = true, features = ["std"] }
cord-primitives = { path = "../primitives/cord" }
futures = "0.3"
getrandom = "0.2"
hex = "0.4"
log = "0.4"
scale-info = { workspace = true, features = ["std"] }
scale-value = { version = "0.18", features = ["serde", "__std"] }
serde = { workspace = true, features = ["derive", "std"] }
env_logger = "0.11"
serde_json = { workspace = true, features = ["std"] }
sp-core = { workspace = true, features = ["std"] }
sp-runtime = { workspace = true, features = ["std"] }
scale-decode = { version = "0.16", default-features = false, features = ["derive"] }
scale-type-resolver = { version = "0.2" }
subxt = { version = "0.44", default-features = true, features = ["jsonrpsee", "native", "reconnecting-rpc-client"] }
subxt-signer = { version = "0.44", default-features = false, features = ["sr25519", "std", "subxt"] }
thiserror = "1"
tokio = { version = "1.40", features = ["macros", "rt-multi-thread"] }

[dev-dependencies]
anyhow = "1.0"
