[package]
name = "origin-hub"
version.workspace = true
authors.workspace = true
edition.workspace = true
build = "build.rs"
description = "Origin Hub"
license.workspace = true
repository.workspace = true
publish = false

[lints]
workspace = true

[[bin]]
name = "origin-hub"
path = "src/main.rs"

[dependencies]
color-eyre = { workspace = true }
clap = { features = ["derive"], workspace = true }
futures = { workspace = true }
jsonrpsee = { features = ["server"], workspace = true }
log = { workspace = true, default-features = true }
prometheus-endpoint = { workspace = true, default-features = true }
serde = { features = ["derive"], workspace = true, default-features = true }
serde_json = { workspace = true, default-features = true }

# Local runtime + constants
origin-hub-system-runtime = { default-features = true, workspace = true }
origin-runtime-constants = { workspace = true, default-features = true }
origin-hub-system-runtime-constants = { workspace = true, default-features = true }
parachains-common = { workspace = true, default-features = true }

# Cumulus / Substrate
cumulus-client-cli = { workspace = true, default-features = true }
cumulus-client-collator = { workspace = true, default-features = true }
cumulus-client-consensus-aura = { workspace = true, default-features = true }
cumulus-client-consensus-common = { workspace = true, default-features = true }
cumulus-client-consensus-proposer = { workspace = true, default-features = true }
cumulus-client-service = { workspace = true, default-features = true }
cumulus-client-bootnodes = { workspace = true, default-features = true }
cumulus-primitives-core = { workspace = true, default-features = true }
cumulus-relay-chain-interface = { workspace = true, default-features = true }
frame-benchmarking-cli = { workspace = true, default-features = true }
polkadot-cli = { workspace = true, default-features = true }
sc-basic-authorship = { workspace = true, default-features = true }
sc-chain-spec = { workspace = true, default-features = true }
sc-cli = { workspace = true, default-features = true }
sc-client-api = { workspace = true, default-features = true }
sc-consensus = { workspace = true, default-features = true }
sc-executor = { workspace = true, default-features = true }
sc-network = { workspace = true, default-features = true }
sc-offchain = { workspace = true, default-features = true }
sc-service = { workspace = true, default-features = true }
sc-sysinfo = { workspace = true, default-features = true }
sc-telemetry = { workspace = true, default-features = true }
sc-transaction-pool = { workspace = true, default-features = true }
sc-transaction-pool-api = { workspace = true, default-features = true }
sc-tracing = { workspace = true, default-features = true }
sp-api = { workspace = true, default-features = true }
sp-block-builder = { workspace = true, default-features = true }
sp-blockchain = { workspace = true, default-features = true }
sp-consensus-aura = { workspace = true, default-features = true }
sp-core = { workspace = true, default-features = true }
sp-keystore = { workspace = true, default-features = true }
sp-runtime = { workspace = true, default-features = true }
sp-timestamp = { workspace = true, default-features = true }
sp-tracing = { workspace = true, default-features = true }

xcm = { workspace = true, default-features = true }

# RPC helpers
pallet-transaction-payment-rpc = { workspace = true, default-features = true }
substrate-frame-rpc-system = { workspace = true, default-features = true }

[build-dependencies]
substrate-build-script-utils = { workspace = true, default-features = true }

[features]
default = []
runtime-benchmarks = [
	"cumulus-primitives-core/runtime-benchmarks",
	"parachains-common/runtime-benchmarks",
	"sc-service/runtime-benchmarks",
	"origin-hub-system-runtime/runtime-benchmarks",
]
try-runtime = ["origin-hub-system-runtime/try-runtime"]
fast-runtime = ["origin-hub-system-runtime/fast-runtime"]
