[package]
name = "origin-hub"
version.workspace = true
authors.workspace = true
edition.workspace = true
build = "build.rs"
description = "Origin Hub"
license.workspace = true
repository.workspace = true
publish = false

[lints]
workspace = true

[[bin]]
name = "origin-hub"
path = "src/main.rs"

[dependencies]
color-eyre = { workspace = true }
hex-literal = { workspace = true, default-features = true }
log = { workspace = true, default-features = true }
serde = { features = ["derive"], workspace = true, default-features = true }
serde_json = { workspace = true, default-features = true }

#Local
origin-hub-system-runtime = { default-features = true, workspace = true }
origin-orbis-runtime = { default-features = true, workspace = true }
origin-runtime-constants = { workspace = true, default-features = true }
origin-hub-system-runtime-constants = { workspace = true, default-features = true }

#Substrate, Cumulus, Polkadot
cumulus-primitives-core = { workspace = true, default-features = true }
polkadot-omni-node-lib = { workspace = true }
parachains-common = { workspace = true, default-features = true }
sc-chain-spec = { workspace = true, default-features = true }
sc-cli = { workspace = true, default-features = true }
sc-service = { workspace = true, default-features = true }
sp-core = { workspace = true, default-features = true }
sp-genesis-builder = { workspace = true, default-features = true }
sp-keyring = { workspace = true, default-features = true }
xcm = { workspace = true, default-features = true }

[build-dependencies]
substrate-build-script-utils = { workspace = true, default-features = true }

[features]
default = []
runtime-benchmarks = [
	"cumulus-primitives-core/runtime-benchmarks",
	"parachains-common/runtime-benchmarks",
	"polkadot-omni-node-lib/runtime-benchmarks",
	"sc-service/runtime-benchmarks",
	"origin-hub-system-runtime/runtime-benchmarks",
	"origin-orbis-runtime/runtime-benchmarks",
]
try-runtime = [
	"polkadot-omni-node-lib/try-runtime",
	"origin-hub-system-runtime/try-runtime",
	"origin-orbis-runtime/try-runtime",
]
fast-runtime = ["origin-hub-system-runtime/fast-runtime", "origin-orbis-runtime/fast-runtime"]
