[package]
name = "origin-storage-cli"
description = "CLI to interact with Origin blob store pallets (publisher/aggregator flows)."
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
publish = false

[lints]
workspace = true

[[bin]]
name = "origin-storage"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
codec = { workspace = true }
clap = { workspace = true, features = ["derive"] }
hex = { workspace = true }
origin-primitives = { workspace = true }
sp-core = { workspace = true }
sp-crypto-hashing = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "fmt"] }

oc = { package = "origin-rs", path = "../../origin-rs" }
