import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "../..");
const source = JSON.parse(readFileSync(resolve(root, "docs/sdk/native-route-contract.json"), "utf8"));
if (source.schema !== "cord.native-route-contract.v1" || source.route_count !== source.routes?.length)
  throw new Error("invalid native route contract");
if (source.route_count !== 143 || new Set(source.routes.map(({ id }: any) => id)).size !== source.route_count)
  throw new Error("native route contract must contain 143 unique routes");
const allowedRuntimeKinds = new Set(["runtime-api", "pallet-call", "sdk-host-operation"]);
for (const route of source.routes) {
  if (!allowedRuntimeKinds.has(route.runtime?.kind)) throw new Error(`${route.id}: unsupported runtime binding kind`);
  if (Object.keys(route.sample_payload).join() !== route.parameters.map(({ name }: any) => name).join())
    throw new Error(`${route.id}: canonical payload order does not match parameters`);
}
const sdkHostOperations = source.routes.filter(({ runtime }: any) => runtime.kind === "sdk-host-operation");
if (sdkHostOperations.length !== 1 || sdkHostOperations[0].id !== "transaction:prepare_sponsored_intent")
  throw new Error("prepare_sponsored_intent must be the sole SDK host operation");
const prepare = sdkHostOperations[0];
if (prepare.rust?.binding_kind !== "sdk-function"
  || prepare.rust.source !== prepare.runtime.source
  || prepare.rust.declaration !== prepare.runtime.target)
  throw new Error("prepare_sponsored_intent SDK function binding is inconsistent");
for (const field of ["pallet", "pallet_index", "call_index", "runtime_api_version", "implementation_source"])
  if (Object.hasOwn(prepare.runtime, field)) throw new Error(`prepare_sponsored_intent must not expose ${field}`);
const output = `// Generated by tools/generate-route-contract.ts. Do not edit.\nexport const NATIVE_ROUTE_CONTRACT = ${JSON.stringify(source, null, 2)} as const;\n`;
const path = resolve(import.meta.dirname, "../packages/descriptors/generated/native-route-contract.ts");
if (process.argv.includes("--check")) {
  if (readFileSync(path, "utf8") !== output) throw new Error("native route projection drift; run npm run generate:routes");
} else writeFileSync(path, output);
process.stdout.write(`PASS native route projection: ${source.route_count} routes\n`);
