import { createHash, createPublicKey, verify } from "node:crypto";
type Json=null|boolean|number|string|Json[]|{[key:string]:Json};
export const REQUIRED_ROLES=["runtime-owner","sdk-owner","security-owner","performance-owner","architecture-owner"] as const;
export function canonicalJson(v:any):string{if(v===null||typeof v!=="object")return JSON.stringify(v);if(Array.isArray(v))return`[${v.map(canonicalJson).join(",")}]`;return`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${canonicalJson(v[k])}`).join(",")}}`}
export const canonicalSha256=(v:any)=>createHash("sha256").update(canonicalJson(v)).digest("hex");
export function contractView(name:string,value:any):any{const v=structuredClone(value);if(["compatibility","extensions","slo"].includes(name))delete v.ratification;if(name==="descriptor")delete v.ratificationPayloadSha256;return v}
export const contractDigest=(name:string,value:any)=>canonicalSha256(contractView(name,value));
export function ratificationStatus(e:any,at=new Date()):{p0TargetsRatified:boolean;productionActivationReady:boolean;verifiedRoles:string[];payloadSha256:string}{
 const exact=(o:any,keys:string[])=>o&&typeof o==="object"&&!Array.isArray(o)&&Object.keys(o).sort().join()===keys.sort().join();if(!exact(e,["schema_version","canonicalization","signature_algorithm","payload","payload_sha256","signatures","derived_status","blocker"])||e.schema_version!==2||e.signature_algorithm!=="Ed25519"||!Array.isArray(e.signatures))throw Error("invalid ratification envelope");
 const hash=canonicalSha256(e.payload);if(hash!==e.payload_sha256)throw Error("ratification payload hash mismatch");
 const policy=e.payload.approval_policy,roles=policy?.required_roles;if(JSON.stringify(roles)!==JSON.stringify(REQUIRED_ROLES)||new Set(roles).size!==5)throw Error("required roles must be exact and unique");
 if(!exact(policy,["key_registry_version","required_roles","approver_slots","authorized_keys"])||policy.key_registry_version!==1||!Array.isArray(policy.authorized_keys)||!Array.isArray(policy.approver_slots))throw Error("invalid key registry");
 if(JSON.stringify(policy.approver_slots.map((x:any)=>x.role))!==JSON.stringify(REQUIRED_ROLES)||policy.approver_slots.some((x:any)=>!exact(x,["role","tracker","status","authorized_key_fingerprint_sha256"])||typeof x.tracker!=="string"||!x.tracker||x.status!=="PENDING"&&x.status!=="READY"))throw Error("approver slots are not exact/tracker-backed");
 const keys=new Map<string,any>(),spkis=new Set<string>(),now=at.getTime();for(const k of policy.authorized_keys){if(!exact(k,["role","fingerprint_sha256","public_key_spki_der_base64","valid_from","valid_until","revoked_at"])||!REQUIRED_ROLES.includes(k.role)||!k.fingerprint_sha256?.match(/^[0-9a-f]{64}$/)||keys.has(k.fingerprint_sha256)||spkis.has(k.public_key_spki_der_base64))throw Error("duplicate or invalid authorized key");const der=Buffer.from(k.public_key_spki_der_base64,"base64");if(createHash("sha256").update(der).digest("hex")!==k.fingerprint_sha256)throw Error("authorized key fingerprint mismatch");if(!k.valid_from||!k.valid_until||Date.parse(k.valid_from)>=Date.parse(k.valid_until)||now<Date.parse(k.valid_from)||now>Date.parse(k.valid_until))throw Error("authorized key validity invalid");if(k.revoked_at!==null)throw Error("authorized key is revoked");keys.set(k.fingerprint_sha256,k);spkis.add(k.public_key_spki_der_base64)}
 for(const slot of policy.approver_slots){if(slot.status==="PENDING"&&slot.authorized_key_fingerprint_sha256!==null)throw Error("pending approver slot must not authorize a key");if(slot.status==="READY"){const key=keys.get(slot.authorized_key_fingerprint_sha256);if(!key||key.role!==slot.role)throw Error("ready approver slot key is not allowlisted")}}
 const payload=Buffer.from(canonicalJson(e.payload)),verified=new Set<string>();for(const s of e.signatures){if(!exact(s,["role","key_fingerprint_sha256","payload_sha256","public_key_spki_der_base64","signature_base64","signed_at"]))throw Error("invalid detached signature shape");const allowed=keys.get(s.key_fingerprint_sha256);if(!allowed||allowed.role!==s.role||s.payload_sha256!==hash||s.public_key_spki_der_base64!==allowed.public_key_spki_der_base64||verified.has(s.role))throw Error("signature is duplicate, unauthorized or misbound");const when=Date.parse(s.signed_at);if(!Number.isFinite(when)||when<Date.parse(allowed.valid_from)||when>Date.parse(allowed.valid_until))throw Error("signature key expired/not-yet-valid/revoked");const key=createPublicKey({key:Buffer.from(s.public_key_spki_der_base64,"base64"),format:"der",type:"spki"});if(!verify(null,payload,key,Buffer.from(s.signature_base64,"base64")))throw Error(`invalid Ed25519 signature for ${s.role}`);verified.add(s.role)}
 const p0=REQUIRED_ROLES.every(r=>verified.has(r));const prod=p0&&e.payload.production_activation.final_genesis_status==="FINAL"&&e.payload.production_activation.campaign_authorized===true;
 if(e.derived_status.p0_targets_ratified!==p0||e.derived_status.production_activation_ready!==prod)throw Error("declared derived statuses drift");return{p0TargetsRatified:p0,productionActivationReady:prod,verifiedRoles:[...verified].sort(),payloadSha256:hash}
}
