# To run the network, execute the following command:
# zombienet -p native spawn zombienet/entity.toml

[settings]
timeout = 300

[relaychain]
chain = "origin-local"
default_command = "target/release/origin"

[[relaychain.nodes]]
name = "alice"
rpc_port = 9900
validator = true
args = ["--trie-cache-size=0", "--disable-worker-version-check"]

[[relaychain.nodes]]
name = "bob"
rpc_port = 9901
validator = true
args = ["--trie-cache-size=0", "--disable-worker-version-check"]

[[parachains]]
id = 1000
addToGenesis = true
cumulus_based = true
chain = "origin-system-local"

[parachains.collator]
name = "entity-collator01"
rpc_port = 9920
collator = true
command = "target/release/origin-hub"
args = ["--trie-cache-size=0", "--execution=wasm"]
