# Build pieces:
#   cargo build -p origin-hub -p origin-hub-system-runtime --release
# Launch network:
#   zombienet -p native spawn testnet.toml

[settings]
timeout = 300

[relaychain]
chain = "origin-local"
default_command = "../target/release/origin"

[[relaychain.nodes]]
name = "alice"
rpc_port = 9900
validator = true
args = [
	"--trie-cache-size=0",
	"--disable-worker-version-check",
	"--execution=wasm",
]

[[relaychain.nodes]]
name = "bob"
rpc_port = 9901
validator = true
args = [
	"--trie-cache-size=0",
	"--disable-worker-version-check",
	"--execution=wasm",
]

[[relaychain.nodes]]
name = "charlie"
rpc_port = 9902
validator = true
args = [
	"--trie-cache-size=0",
	"--disable-worker-version-check",
	"--execution=wasm",
]

[[parachains]]
id = 1000
addToGenesis = true
cumulus_based = true
chain = "origin-system-local"

[parachains.collator]
name = "hub-in-collator"
rpc_port = 9910
collator = true
command = "../target/release/origin-hub"
args = ["--trie-cache-size=0", "--execution=wasm"]

[[parachains]]
id = 1001
addToGenesis = true
cumulus_based = true
chain = "origin-system-na-local"

[parachains.collator]
name = "hub-na-collator"
rpc_port = 9911
collator = true
command = "../target/release/origin-hub"
args = ["--trie-cache-size=0", "--execution=wasm"]
