[package]
name = "origin-node-cli"
description = "Origin Client Node"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[package.metadata.wasm-pack.profile.release]
# `wasm-opt` has some problems on Linux, see
# https://github.com/rustwasm/wasm-pack/issues/781 etc.
wasm-opt = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cfg-if = { workspace = true }
clap = { features = ["derive"], optional = true, workspace = true }
log = { workspace = true, default-features = true }
thiserror = { workspace = true }
futures = { workspace = true }
pyroscope = { optional = true, workspace = true }
pyroscope_pprofrs = { optional = true, workspace = true }
polkadot-primitives = { workspace = true, default-features = true }
polkadot-service = { optional = true, workspace = true }
runtime-parachains = { workspace = true }
serde_json = { workspace = true }
serde = { features = ["derive"], workspace = true }
sc-client-api.workspace = true
sc-client-api.default-features = true
sc-sync-state-rpc.workspace = true
sc-sync-state-rpc.default-features = true
sp-io.workspace = true
sp-io.default-features = true
sp-maybe-compressed-blob.workspace = true
sp-maybe-compressed-blob.default-features = true
frame-system = { workspace = true, default-features = true }
frame-benchmarking-cli = { optional = true, workspace = true, default-features = true }
frame-metadata-hash-extension = { optional = true, workspace = true, default-features = true }
sc-cli = { optional = true, workspace = true, default-features = true }
sc-service = { optional = true, workspace = true, default-features = true }
pallet-transaction-payment = { workspace = true, default-features = true }
pallet-transaction-payment-rpc-runtime-api = { workspace = true, default-features = true }
polkadot-node-metrics = { workspace = true, default-features = true }
sc-storage-monitor = { workspace = true, default-features = true }
sc-sysinfo = { workspace = true, default-features = true }
sc-tracing = { optional = true, workspace = true, default-features = true }
sp-core = { workspace = true, default-features = true }
sp-keyring = { workspace = true, default-features = true }
sp-runtime = { workspace = true, default-features = true }
sc-chain-spec.workspace = true
sc-chain-spec.default-features = true
sc-telemetry.workspace = true
sc-telemetry.default-features = true
sc-executor.workspace = true
sc-executor.default-features = true
origin-staging-runtime = { optional = true, workspace = true, default-features = true }
origin-staging-runtime-constants = { optional = true, workspace = true, default-features = true }

[build-dependencies]
substrate-build-script-utils = { workspace = true, default-features = true }

[features]
default = ["cli", "db", "full-node", "origin-native"]
db = ["polkadot-service/db"]
metadata-hash = ["origin-staging-runtime/metadata-hash"]
service = ["dep:polkadot-service"]
cli = [
	"clap",
	"frame-benchmarking-cli",
	"sc-cli",
	"sc-service",
	"sc-tracing",
	"service",
]
runtime-benchmarks = [
	"frame-benchmarking-cli?/runtime-benchmarks",
	"polkadot-node-metrics/runtime-benchmarks",
	"origin-staging-runtime/runtime-benchmarks",
	"sc-service?/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
]
full-node = ["polkadot-service/full-node"]
origin-native = [
	"frame-metadata-hash-extension",
	"origin-staging-runtime",
	"origin-staging-runtime-constants",
]
try-runtime = [
	"frame-system/try-runtime",
	"pallet-transaction-payment/try-runtime",
	"runtime-parachains/try-runtime",
	"origin-staging-runtime/try-runtime",
	"sp-runtime/try-runtime",
]
fast-runtime = [
	"origin-staging-runtime/fast-runtime",
	"origin-staging-runtime-constants/fast-runtime",
]
pyroscope = ["dep:pyroscope", "pyroscope_pprofrs"]
malus = ["full-node"]
runtime-metrics = [
	"polkadot-node-metrics/runtime-metrics",
	"origin-staging-runtime/runtime-metrics",
]
