import { createHash } from "node:crypto"; import { readFileSync } from "node:fs"; import { contractDigest, ratificationStatus } from "../../core/src/ratification.ts"; export { contractDigest };
type J=Record<string,any>; const hex=/^[0-9a-f]{64}$/; const exact=(o:J,keys:string[],label:string)=>{if(!o||typeof o!=="object"||Array.isArray(o)||Object.keys(o).sort().join()!==[...keys].sort().join())throw new Error(`${label} has unknown or missing fields`)};
const finite=(v:any,min:number,max=Number.MAX_SAFE_INTEGER,label="number")=>{if(typeof v!=="number"||!Number.isFinite(v)||v<min||v>max)throw new Error(`${label} out of bounds`)};
const integer=(v:any,min:number,max=Number.MAX_SAFE_INTEGER,label="integer")=>{if(!Number.isInteger(v)||v<min||v>max)throw new Error(`${label} out of bounds`)};
export const sha256File=(p:string)=>createHash("sha256").update(readFileSync(p)).digest("hex");
export function validateSloManifest(m:J,envelope:J):{ratified:boolean}{
 exact(m,["manifest_version","status","network","campaign","E","Q","C","ratification"],"SLO manifest"); if(m.manifest_version!==1||m.status!=="proposed-unratified")throw Error("unsupported SLO version/status");
 exact(m.network,["aura_slot_ms","orbis_collators","orbis_cores","origin_validators","para_id","relay_parent_offset","target_block_rate","unincluded_segment_capacity"],"network");
 if(JSON.stringify(m.network)!==JSON.stringify({aura_slot_ms:6000,orbis_collators:2,orbis_cores:[1,3],origin_validators:6,para_id:1006,relay_parent_offset:1,target_block_rate:3,unincluded_segment_capacity:12}))throw Error("topology drift");
 exact(m.campaign,["cooldown_seconds","interleaved_runs","max_clock_offset_ms","max_cv_percent","max_finality_lag_blocks","measurement_seconds","seed","warmup_seconds"],"campaign");
 for(const k of ["cooldown_seconds","interleaved_runs","max_clock_offset_ms","max_cv_percent","max_finality_lag_blocks","measurement_seconds","seed","warmup_seconds"])integer(m.campaign[k],0,Number.MAX_SAFE_INTEGER,`campaign.${k}`);if(m.campaign.seed!==20260713||m.campaign.interleaved_runs<5||m.campaign.warmup_seconds<600||m.campaign.measurement_seconds<1800||m.campaign.cooldown_seconds<300||m.campaign.max_clock_offset_ms>50||m.campaign.max_cv_percent>10||m.campaign.max_finality_lag_blocks>15)throw Error("campaign bounds weakened");
 const keys:any={E:["mix_percent","observed_resource_utilization_max_percent","p95_finality_ms","p95_inclusion_ms","p95_resource_utilization_max_percent","sponsored_intent_success_percent","storage_headroom_min_percent","target_finalized_successful_extrinsics_per_second"],Q:["finalized_hash_required","mix_percent","reconnect_catchup_p95_ms","request_p95_ms","request_success_percent","subscription_completeness_percent","subscription_delivery_p95_ms"],C:["cid_integrity_percent","completion_p95_ms","concurrency","content_buckets","failover_success_percent","mix_percent","network","provider_count","provider_topology","request_rate_per_second","retries","success_percent","throughput_floor_mib_per_second","timeout_ms","ttfb_p95_ms"]};
 for(const k of ["E","Q","C"]){exact(m[k],keys[k],k);for(const v of Object.values(m[k].mix_percent))finite(v,0,100,`${k} mix member`);if(Object.values(m[k].mix_percent).reduce((a:any,b:any)=>a+b,0)!==100)throw Error(`${k} mix`);for(const [n,v] of Object.entries(m[k]))if(typeof v==="number")finite(v,0,n.endsWith("percent")?100:Number.MAX_SAFE_INTEGER,`${k}.${n}`)}
 for(const [n,v] of Object.entries(m.E))if(n!=="mix_percent")finite(v,0,n.endsWith("percent")?100:Number.MAX_SAFE_INTEGER,`E.${n}`);for(const [n,v] of Object.entries(m.Q))if(!["mix_percent","finalized_hash_required"].includes(n))finite(v,0,n.endsWith("percent")?100:Number.MAX_SAFE_INTEGER,`Q.${n}`);for(const [n,v] of Object.entries(m.C))if(!["mix_percent","content_buckets","network","provider_topology"].includes(n))finite(v,0,n.endsWith("percent")?100:Number.MAX_SAFE_INTEGER,`C.${n}`);
 if(m.Q.finalized_hash_required!==true||typeof m.C.provider_topology!=="string"||!m.C.provider_topology)throw Error("invalid boolean/string target");for(const k of ["concurrency","provider_count","request_rate_per_second","retries","timeout_ms"])integer(m.C[k],0,Number.MAX_SAFE_INTEGER,`C.${k}`);if(!Array.isArray(m.C.content_buckets)||m.C.content_buckets.length!==4||m.C.content_buckets.reduce((a:number,x:J)=>a+x.proportion_percent,0)!==100)throw Error("C buckets");for(const x of m.C.content_buckets){exact(x,["proportion_percent","range"],"C bucket");finite(x.proportion_percent,0,100,"C bucket proportion");if(typeof x.range!=="string"||!x.range)throw Error("C bucket range")} exact(m.C.network,["bandwidth_mbps","latency_ms","loss_percent"],"C.network");finite(m.C.network.bandwidth_mbps,1,Number.MAX_SAFE_INTEGER,"bandwidth");finite(m.C.network.latency_ms,0,Number.MAX_SAFE_INTEGER,"latency");finite(m.C.network.loss_percent,0,100,"loss");
 exact(m.ratification,["canonical_envelope","payload_sha256","p0_targets_status","production_activation_status"],"ratification ref");const status=ratificationStatus(envelope);if(m.ratification.payload_sha256!==status.payloadSha256||m.ratification.p0_targets_status!==(status.p0TargetsRatified?"RATIFIED":"PENDING")||m.ratification.production_activation_status!==(status.productionActivationReady?"READY":"BLOCKED"))throw Error("ratification reference drift");return{ratified:status.p0TargetsRatified};
}
const metricKeys:any={E:["finalized_successful_eps","inclusion_p95_ms","finality_p95_ms","sponsored_success_percent","storage_headroom_percent","p95_resource_percent","max_resource_percent","finality_lag_blocks","cv_percent"],Q:["request_success_percent","request_p95_ms","subscription_completeness_percent","subscription_delivery_p95_ms","reconnect_catchup_p95_ms","finality_lag_blocks","cv_percent"],C:["cid_integrity_percent","success_percent","ttfb_p95_ms","completion_p95_ms","throughput_mib_per_second","failover_success_percent","finality_lag_blocks","cv_percent"]};
export function recomputeFailures(k:string,o:J,s:J):string[]{const f:string[]=[];const min=(n:string,v:number)=>{if(o[n]<v)f.push(n)},max=(n:string,v:number)=>{if(o[n]>v)f.push(n)};max("finality_lag_blocks",s.campaign.max_finality_lag_blocks);max("cv_percent",s.campaign.max_cv_percent);if(k==="E"){min("finalized_successful_eps",s.E.target_finalized_successful_extrinsics_per_second);max("inclusion_p95_ms",s.E.p95_inclusion_ms);max("finality_p95_ms",s.E.p95_finality_ms);min("sponsored_success_percent",s.E.sponsored_intent_success_percent);min("storage_headroom_percent",s.E.storage_headroom_min_percent);max("p95_resource_percent",s.E.p95_resource_utilization_max_percent);max("max_resource_percent",s.E.observed_resource_utilization_max_percent)}if(k==="Q"){min("request_success_percent",s.Q.request_success_percent);max("request_p95_ms",s.Q.request_p95_ms);min("subscription_completeness_percent",s.Q.subscription_completeness_percent);max("subscription_delivery_p95_ms",s.Q.subscription_delivery_p95_ms);max("reconnect_catchup_p95_ms",s.Q.reconnect_catchup_p95_ms)}if(k==="C"){min("cid_integrity_percent",s.C.cid_integrity_percent);min("success_percent",s.C.success_percent);max("ttfb_p95_ms",s.C.ttfb_p95_ms);max("completion_p95_ms",s.C.completion_p95_ms);min("throughput_mib_per_second",s.C.throughput_floor_mib_per_second);min("failover_success_percent",s.C.failover_success_percent)}return f.sort()}
export function validateEqcResult(r:J,manifestHash:string,slo:J,ratified:boolean):void{
 const top=["schema_version","scope","campaign_executed","class","manifest_sha256","runtime","environment","raw_uri","raw_sha256","samples","observations","verdict"];exact(r,top,"result");if(r.schema_version!==1||typeof r.scope!=="string"||typeof r.campaign_executed!=="boolean"||!["E","Q","C"].includes(r.class)||typeof r.manifest_sha256!=="string"||r.manifest_sha256!==manifestHash||typeof r.raw_sha256!=="string"||!hex.test(r.raw_sha256)||typeof r.raw_uri!=="string"||!r.raw_uri)throw Error("result identity/hash mismatch");
 exact(r.runtime,["genesis_identity","genesis_status","wasm_sha256","metadata_hash","descriptor_contract_sha256","spec_version","transaction_version"],"runtime");if(typeof r.runtime.genesis_identity!=="string"||typeof r.runtime.genesis_status!=="string"||typeof r.runtime.wasm_sha256!=="string"||typeof r.runtime.metadata_hash!=="string"||typeof r.runtime.descriptor_contract_sha256!=="string"||r.runtime.genesis_identity!=="0x40519e2e0e894e9b68defd9df6697619116ea693d0864913c98b5c65cd4e511a"||r.runtime.metadata_hash!=="0x8519557667f87eb7ee32cd109d40acfd48d9c53a7ed915fe1733b03573ab9ef9"||r.runtime.spec_version!==29||r.runtime.transaction_version!==8||!hex.test(r.runtime.wasm_sha256)||!hex.test(r.runtime.descriptor_contract_sha256))throw Error("runtime binding mismatch");
 exact(r.environment,["topology_sha256","origin_validators","orbis_collators","orbis_cores","clock_offset_ms","seed","warmup_seconds","measurement_seconds","cooldown_seconds"],"environment");for(const k of["origin_validators","orbis_collators","orbis_cores","clock_offset_ms","seed","warmup_seconds","measurement_seconds","cooldown_seconds"])integer(r.environment[k],k==="clock_offset_ms"?-50:0,k==="clock_offset_ms"?50:Number.MAX_SAFE_INTEGER,`environment.${k}`);if(typeof r.environment.topology_sha256!=="string"||!hex.test(r.environment.topology_sha256)||r.environment.origin_validators!==6||r.environment.orbis_collators!==2||![1,3].includes(r.environment.orbis_cores)||r.environment.seed!==20260713)throw Error("environment bounds");
 exact(r.verdict,["pass","failures","bottleneck_attribution","recomputed"],"verdict");if(typeof r.verdict.pass!=="boolean"||r.verdict.recomputed!==true||!Array.isArray(r.verdict.failures)||r.verdict.failures.some((x:any)=>typeof x!=="string")||!Array.isArray(r.verdict.bottleneck_attribution)||r.verdict.bottleneck_attribution.some((x:any)=>typeof x!=="string"))throw Error("verdict not recomputed/typed");
 if(!r.campaign_executed){if(r.scope!=="schema-validation-only"||r.samples!==0||Object.keys(r.observations).length||r.verdict.pass||JSON.stringify(r.verdict.failures)!==JSON.stringify(["schema-only-no-network-campaign"]))throw Error("schema-only result made a campaign claim");return}
 if(!ratified||r.scope!=="network-campaign"||r.runtime.genesis_status!=="production-genesis-final")throw Error("campaign is not ratified/final-genesis");if(r.samples<1||r.environment.warmup_seconds<slo.campaign.warmup_seconds||r.environment.measurement_seconds<slo.campaign.measurement_seconds||r.environment.cooldown_seconds<slo.campaign.cooldown_seconds||r.raw_uri.startsWith("schema-only:"))throw Error("campaign sampling/window evidence invalid");exact(r.observations,metricKeys[r.class],`${r.class} observations`);for(const[k,v]of Object.entries(r.observations))finite(v,0,k.endsWith("percent")?100:Number.MAX_SAFE_INTEGER,k);const failures=recomputeFailures(r.class,r.observations,slo);if(r.verdict.pass!==(failures.length===0)||JSON.stringify([...r.verdict.failures].sort())!==JSON.stringify(failures))throw Error("dishonest threshold verdict");
}
export function validateResultSchemaContract(s:J):void{if(s.$id!=="https://cord.network/schemas/eqc-result-v1.json"||s.additionalProperties!==false||s.properties.runtime.additionalProperties!==false||s.properties.environment.additionalProperties!==false||s.properties.verdict.additionalProperties!==false||s.oneOf?.length!==4||s.oneOf.some((x:J)=>x.properties.observations.additionalProperties!==false))throw Error("result schema not recursively closed")}
export function validateServiceSchemaContract(s:J):void{if(s.$id!=="https://cord.network/schemas/service-slo-manifest-v1.json")throw Error("SLO schema identity");const walk=(node:J,path:string)=>{if(node?.type==="object"){if(node.additionalProperties!==false)throw Error(`${path} schema is open`);for(const[k,v]of Object.entries(node.properties??{}))walk(v as J,`${path}.${k}`)}if(node?.type==="array")walk(node.items,`${path}[]`)};walk(s,"SLO")}
