// This file is part of CORD – https://cord.network

// Copyright (C) Dhiway Networks Pvt. Ltd.
// SPDX-License-Identifier: GPL-3.0-or-later

// CORD is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// CORD is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with CORD. If not, see <https://www.gnu.org/licenses/>.

//! Autogenerated weights for `pallet_did`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2024-05-17, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `cord-benchmark-16gb`, CPU: `AMD EPYC 7B13`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: 1024

// Executed Command:
// ./target/production/cord
// benchmark
// pallet
// --chain=dev
// --steps=50
// --repeat=20
// --pallet=pallet_did
// --extrinsic=*
// --wasm-execution=compiled
// --heap-pages=4096
// --header=./HEADER-GPL3
// --output=./runtime/src/weights/

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_did`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_did::WeightInfo for WeightInfo<T> {
	/// Storage: `Did::DidBlacklist` (r:1 w:0)
	/// Proof: `Did::DidBlacklist` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2184), added: 4659, mode: `MaxEncodedLen`)
	/// Storage: `Did::DidEndpointsCount` (r:0 w:1)
	/// Proof: `Did::DidEndpointsCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Did::ServiceEndpoints` (r:0 w:25)
	/// Proof: `Did::ServiceEndpoints` (`max_values`: None, `max_size`: Some(413), added: 2888, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 10]`.
	/// The range of component `c` is `[1, 25]`.
	fn create_ed25519_keys(n: u32, c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `42`
		//  Estimated: `5649`
		// Minimum execution time: 104_580_000 picoseconds.
		Weight::from_parts(93_931_156, 0)
			.saturating_add(Weight::from_parts(0, 5649))
			// Standard Error: 42_551
			.saturating_add(Weight::from_parts(868_561, 0).saturating_mul(n.into()))
			// Standard Error: 16_451
			.saturating_add(Weight::from_parts(6_981_083, 0).saturating_mul(c.into()))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(c.into())))
	}
	/// Storage: `Did::DidBlacklist` (r:1 w:0)
	/// Proof: `Did::DidBlacklist` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2184), added: 4659, mode: `MaxEncodedLen`)
	/// Storage: `Did::DidEndpointsCount` (r:0 w:1)
	/// Proof: `Did::DidEndpointsCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Did::ServiceEndpoints` (r:0 w:25)
	/// Proof: `Did::ServiceEndpoints` (`max_values`: None, `max_size`: Some(413), added: 2888, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 10]`.
	/// The range of component `c` is `[1, 25]`.
	fn create_sr25519_keys(n: u32, c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `42`
		//  Estimated: `5649`
		// Minimum execution time: 86_230_000 picoseconds.
		Weight::from_parts(73_287_818, 0)
			.saturating_add(Weight::from_parts(0, 5649))
			// Standard Error: 70_401
			.saturating_add(Weight::from_parts(1_224_170, 0).saturating_mul(n.into()))
			// Standard Error: 27_219
			.saturating_add(Weight::from_parts(8_065_578, 0).saturating_mul(c.into()))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(c.into())))
	}
	/// Storage: `Did::DidBlacklist` (r:1 w:0)
	/// Proof: `Did::DidBlacklist` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2184), added: 4659, mode: `MaxEncodedLen`)
	/// Storage: `Did::DidEndpointsCount` (r:0 w:1)
	/// Proof: `Did::DidEndpointsCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Did::ServiceEndpoints` (r:0 w:25)
	/// Proof: `Did::ServiceEndpoints` (`max_values`: None, `max_size`: Some(413), added: 2888, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 10]`.
	/// The range of component `c` is `[1, 25]`.
	fn create_ecdsa_keys(n: u32, c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `42`
		//  Estimated: `5649`
		// Minimum execution time: 83_380_000 picoseconds.
		Weight::from_parts(73_398_725, 0)
			.saturating_add(Weight::from_parts(0, 5649))
			// Standard Error: 41_631
			.saturating_add(Weight::from_parts(1_187_983, 0).saturating_mul(n.into()))
			// Standard Error: 16_095
			.saturating_add(Weight::from_parts(6_881_485, 0).saturating_mul(c.into()))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(c.into())))
	}
	/// Storage: `Did::DidEndpointsCount` (r:1 w:1)
	/// Proof: `Did::DidEndpointsCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Did::ServiceEndpoints` (r:25 w:25)
	/// Proof: `Did::ServiceEndpoints` (`max_values`: None, `max_size`: Some(413), added: 2888, mode: `MaxEncodedLen`)
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2184), added: 4659, mode: `MaxEncodedLen`)
	/// Storage: `Did::DidBlacklist` (r:0 w:1)
	/// Proof: `Did::DidBlacklist` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// The range of component `c` is `[1, 25]`.
	fn delete(c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `364 + c * (105 ±0)`
		//  Estimated: `5649 + c * (2888 ±0)`
		// Minimum execution time: 24_590_000 picoseconds.
		Weight::from_parts(25_813_499, 0)
			.saturating_add(Weight::from_parts(0, 5649))
			// Standard Error: 6_833
			.saturating_add(Weight::from_parts(1_230_236, 0).saturating_mul(c.into()))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(c.into())))
			.saturating_add(T::DbWeight::get().writes(3))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(c.into())))
			.saturating_add(Weight::from_parts(0, 2888).saturating_mul(c.into()))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2184), added: 4659, mode: `MaxEncodedLen`)
	fn submit_did_call_ed25519_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `233`
		//  Estimated: `5649`
		// Minimum execution time: 77_900_000 picoseconds.
		Weight::from_parts(84_040_000, 0)
			.saturating_add(Weight::from_parts(0, 5649))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2184), added: 4659, mode: `MaxEncodedLen`)
	fn submit_did_call_sr25519_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `233`
		//  Estimated: `5649`
		// Minimum execution time: 66_860_000 picoseconds.
		Weight::from_parts(69_780_000, 0)
			.saturating_add(Weight::from_parts(0, 5649))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2184), added: 4659, mode: `MaxEncodedLen`)
	fn submit_did_call_ecdsa_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `234`
		//  Estimated: `5649`
		// Minimum execution time: 67_229_000 picoseconds.
		Weight::from_parts(70_671_000, 0)
			.saturating_add(Weight::from_parts(0, 5649))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2184), added: 4659, mode: `MaxEncodedLen`)
	fn set_ed25519_authentication_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1457`
		//  Estimated: `5649`
		// Minimum execution time: 23_760_000 picoseconds.
		Weight::from_parts(25_909_000, 0)
			.saturating_add(Weight::from_parts(0, 5649))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2184), added: 4659, mode: `MaxEncodedLen`)
	fn set_sr25519_authentication_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1457`
		//  Estimated: `5649`
		// Minimum execution time: 24_960_000 picoseconds.
		Weight::from_parts(26_430_000, 0)
			.saturating_add(Weight::from_parts(0, 5649))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2184), added: 4659, mode: `MaxEncodedLen`)
	fn set_ecdsa_authentication_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1460`
		//  Estimated: `5649`
		// Minimum execution time: 25_030_000 picoseconds.
		Weight::from_parts(26_200_000, 0)
			.saturating_add(Weight::from_parts(0, 5649))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2184), added: 4659, mode: `MaxEncodedLen`)
	fn set_ed25519_delegation_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1457`
		//  Estimated: `5649`
		// Minimum execution time: 22_800_000 picoseconds.
		Weight::from_parts(25_330_000, 0)
			.saturating_add(Weight::from_parts(0, 5649))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2184), added: 4659, mode: `MaxEncodedLen`)
	fn set_sr25519_delegation_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1457`
		//  Estimated: `5649`
		// Minimum execution time: 23_170_000 picoseconds.
		Weight::from_parts(26_380_000, 0)
			.saturating_add(Weight::from_parts(0, 5649))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2184), added: 4659, mode: `MaxEncodedLen`)
	fn set_ecdsa_delegation_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1460`
		//  Estimated: `5649`
		// Minimum execution time: 24_740_000 picoseconds.
		Weight::from_parts(25_760_000, 0)
			.saturating_add(Weight::from_parts(0, 5649))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2184), added: 4659, mode: `MaxEncodedLen`)
	fn remove_ed25519_delegation_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1457`
		//  Estimated: `5649`
		// Minimum execution time: 21_050_000 picoseconds.
		Weight::from_parts(24_229_000, 0)
			.saturating_add(Weight::from_parts(0, 5649))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2184), added: 4659, mode: `MaxEncodedLen`)
	fn remove_sr25519_delegation_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1457`
		//  Estimated: `5649`
		// Minimum execution time: 22_920_000 picoseconds.
		Weight::from_parts(24_070_000, 0)
			.saturating_add(Weight::from_parts(0, 5649))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2184), added: 4659, mode: `MaxEncodedLen`)
	fn remove_ecdsa_delegation_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1460`
		//  Estimated: `5649`
		// Minimum execution time: 22_220_000 picoseconds.
		Weight::from_parts(23_810_000, 0)
			.saturating_add(Weight::from_parts(0, 5649))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2184), added: 4659, mode: `MaxEncodedLen`)
	fn set_ed25519_assertion_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1457`
		//  Estimated: `5649`
		// Minimum execution time: 25_010_000 picoseconds.
		Weight::from_parts(26_380_000, 0)
			.saturating_add(Weight::from_parts(0, 5649))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2184), added: 4659, mode: `MaxEncodedLen`)
	fn set_sr25519_assertion_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1457`
		//  Estimated: `5649`
		// Minimum execution time: 24_750_000 picoseconds.
		Weight::from_parts(26_100_000, 0)
			.saturating_add(Weight::from_parts(0, 5649))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2184), added: 4659, mode: `MaxEncodedLen`)
	fn set_ecdsa_assertion_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1460`
		//  Estimated: `5649`
		// Minimum execution time: 25_051_000 picoseconds.
		Weight::from_parts(26_270_000, 0)
			.saturating_add(Weight::from_parts(0, 5649))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2184), added: 4659, mode: `MaxEncodedLen`)
	fn remove_ed25519_assertion_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1457`
		//  Estimated: `5649`
		// Minimum execution time: 22_260_000 picoseconds.
		Weight::from_parts(24_369_000, 0)
			.saturating_add(Weight::from_parts(0, 5649))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2184), added: 4659, mode: `MaxEncodedLen`)
	fn remove_sr25519_assertion_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1457`
		//  Estimated: `5649`
		// Minimum execution time: 23_090_000 picoseconds.
		Weight::from_parts(24_120_000, 0)
			.saturating_add(Weight::from_parts(0, 5649))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2184), added: 4659, mode: `MaxEncodedLen`)
	fn remove_ecdsa_assertion_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1460`
		//  Estimated: `5649`
		// Minimum execution time: 23_410_000 picoseconds.
		Weight::from_parts(24_780_000, 0)
			.saturating_add(Weight::from_parts(0, 5649))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2184), added: 4659, mode: `MaxEncodedLen`)
	fn add_ed25519_key_agreement_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1355`
		//  Estimated: `5649`
		// Minimum execution time: 23_510_000 picoseconds.
		Weight::from_parts(24_940_000, 0)
			.saturating_add(Weight::from_parts(0, 5649))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2184), added: 4659, mode: `MaxEncodedLen`)
	fn add_sr25519_key_agreement_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1355`
		//  Estimated: `5649`
		// Minimum execution time: 22_450_000 picoseconds.
		Weight::from_parts(24_650_000, 0)
			.saturating_add(Weight::from_parts(0, 5649))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2184), added: 4659, mode: `MaxEncodedLen`)
	fn add_ecdsa_key_agreement_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1358`
		//  Estimated: `5649`
		// Minimum execution time: 24_291_000 picoseconds.
		Weight::from_parts(25_360_000, 0)
			.saturating_add(Weight::from_parts(0, 5649))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2184), added: 4659, mode: `MaxEncodedLen`)
	fn remove_ed25519_key_agreement_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1457`
		//  Estimated: `5649`
		// Minimum execution time: 23_290_000 picoseconds.
		Weight::from_parts(24_091_000, 0)
			.saturating_add(Weight::from_parts(0, 5649))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2184), added: 4659, mode: `MaxEncodedLen`)
	fn remove_sr25519_key_agreement_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1457`
		//  Estimated: `5649`
		// Minimum execution time: 23_520_000 picoseconds.
		Weight::from_parts(24_331_000, 0)
			.saturating_add(Weight::from_parts(0, 5649))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2184), added: 4659, mode: `MaxEncodedLen`)
	fn remove_ecdsa_key_agreement_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1460`
		//  Estimated: `5649`
		// Minimum execution time: 22_090_000 picoseconds.
		Weight::from_parts(24_020_000, 0)
			.saturating_add(Weight::from_parts(0, 5649))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2184), added: 4659, mode: `MaxEncodedLen`)
	/// Storage: `Did::DidEndpointsCount` (r:1 w:1)
	/// Proof: `Did::DidEndpointsCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Did::ServiceEndpoints` (r:1 w:1)
	/// Proof: `Did::ServiceEndpoints` (`max_values`: None, `max_size`: Some(413), added: 2888, mode: `MaxEncodedLen`)
	fn add_service_endpoint() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `905`
		//  Estimated: `5649`
		// Minimum execution time: 30_680_000 picoseconds.
		Weight::from_parts(31_790_000, 0)
			.saturating_add(Weight::from_parts(0, 5649))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2184), added: 4659, mode: `MaxEncodedLen`)
	/// Storage: `Did::ServiceEndpoints` (r:1 w:1)
	/// Proof: `Did::ServiceEndpoints` (`max_values`: None, `max_size`: Some(413), added: 2888, mode: `MaxEncodedLen`)
	/// Storage: `Did::DidEndpointsCount` (r:1 w:1)
	/// Proof: `Did::DidEndpointsCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn remove_service_endpoint() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1286`
		//  Estimated: `5649`
		// Minimum execution time: 27_240_000 picoseconds.
		Weight::from_parts(30_340_000, 0)
			.saturating_add(Weight::from_parts(0, 5649))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `Did::Did` (r:1 w:0)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2184), added: 4659, mode: `MaxEncodedLen`)
	/// The range of component `l` is `[1, 5242880]`.
	fn signature_verification_sr25519(l: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1459`
		//  Estimated: `5649`
		// Minimum execution time: 56_330_000 picoseconds.
		Weight::from_parts(195_287_780, 0)
			.saturating_add(Weight::from_parts(0, 5649))
			// Standard Error: 5
			.saturating_add(Weight::from_parts(4_783, 0).saturating_mul(l.into()))
			.saturating_add(T::DbWeight::get().reads(1))
	}
	/// Storage: `Did::Did` (r:1 w:0)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2184), added: 4659, mode: `MaxEncodedLen`)
	/// The range of component `l` is `[1, 5242880]`.
	fn signature_verification_ed25519(l: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1459`
		//  Estimated: `5649`
		// Minimum execution time: 67_090_000 picoseconds.
		Weight::from_parts(205_873_583, 0)
			.saturating_add(Weight::from_parts(0, 5649))
			// Standard Error: 5
			.saturating_add(Weight::from_parts(1_830, 0).saturating_mul(l.into()))
			.saturating_add(T::DbWeight::get().reads(1))
	}
	/// Storage: `Did::Did` (r:1 w:0)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2184), added: 4659, mode: `MaxEncodedLen`)
	/// The range of component `l` is `[1, 5242880]`.
	fn signature_verification_ecdsa(l: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1460`
		//  Estimated: `5649`
		// Minimum execution time: 54_170_000 picoseconds.
		Weight::from_parts(165_802_838, 0)
			.saturating_add(Weight::from_parts(0, 5649))
			// Standard Error: 5
			.saturating_add(Weight::from_parts(1_045, 0).saturating_mul(l.into()))
			.saturating_add(T::DbWeight::get().reads(1))
	}
	/// Storage: `Did::Did` (r:1 w:0)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2184), added: 4659, mode: `MaxEncodedLen`)
	fn dispatch_as() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `234`
		//  Estimated: `5649`
		// Minimum execution time: 16_440_000 picoseconds.
		Weight::from_parts(17_140_000, 0)
			.saturating_add(Weight::from_parts(0, 5649))
			.saturating_add(T::DbWeight::get().reads(1))
	}
	/// Storage: `Did::DidBlacklist` (r:1 w:0)
	/// Proof: `Did::DidBlacklist` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2184), added: 4659, mode: `MaxEncodedLen`)
	fn create_from_account() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `42`
		//  Estimated: `5649`
		// Minimum execution time: 13_880_000 picoseconds.
		Weight::from_parts(14_590_000, 0)
			.saturating_add(Weight::from_parts(0, 5649))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}
