// Copyright (C) Parity Technologies (UK) Ltd.
// This file is part of Individuality.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Core types for the honour system.

use codec::{Decode, Encode, MaxEncodedLen};
use frame_support::pallet_prelude::DecodeWithMemTracking;
use indiv_support::traits::{Alias, Context, MembershipProver};
use scale_info::TypeInfo;
use verifiable::GenerateVerifiable;

use crate::Config;

pub type CryptoOf<T> = <<T as Config>::MemberService as MembershipProver>::Crypto;
pub type RingProofOf<T> = <CryptoOf<T> as GenerateVerifiable>::Proof;

/// Unique ID of a subject that can receive honour.
///
/// This could be anything: a shop vendor, a phone app, a meetup host, etc.
pub type SubjectId = [u8; 32];

/// Ring alias of a [`SubjectId`] generated by a specific voter.
///
/// Uniquely derived from [`SubjectId`] and can only be generated by the voter's private key.
///
/// Used to ensure that a voter can't vote for the same subject multiple times.
pub type SubjectAlias = [u8; 32];

/// Index of a point that may be directed to a subject through a vote.
///
/// Each voter can direct up to 256 points at once.
pub type PointId = u8;

/// Ring alias of a [`PointId`] generated by a specific voter.
///
/// Uniquely derived from [`PointId`] and can only be generated by the voter's private key.
///
/// Used to ensure that a voter can't assign the same point multiple times.
pub type PointAlias = [u8; 32];

/// Absolute honour score of a subject.
pub type Honour = i32;

/// Measure `UnixTime` durations in seconds.
pub type Seconds = u64;

/// Information associated with every used point that gets stored.
#[derive(Encode, Decode, Clone, PartialEq, Eq, Debug, TypeInfo, MaxEncodedLen)]
pub struct PointInfo {
	/// ID of the subject toward which the point is directed.
	pub subject: SubjectId,
	/// Alias of the subject toward which the point is directed.
	pub subject_alias: SubjectAlias,
	/// Current direction of the point.
	pub direction: Direction,
	/// The time when the point was used the last time.
	///
	/// Timestamp in seconds since Unix epoch.
	pub last_used_at: Seconds,
}

/// Direction of an honour vote.
#[derive(
	Clone,
	Copy,
	Decode,
	DecodeWithMemTracking,
	Encode,
	Eq,
	MaxEncodedLen,
	PartialEq,
	Debug,
	TypeInfo,
)]
pub enum Direction {
	/// Increase the honour of the subject by one.
	Honourable,

	/// Decrease the honour of the subject by one.
	Dishonourable,
}

impl Direction {
	/// Returns the signed value of this direction for score arithmetic.
	pub fn score(&self) -> Honour {
		match self {
			Direction::Honourable => 1,
			Direction::Dishonourable => -1,
		}
	}

	/// The opposite direction.
	pub fn opposite(&self) -> Self {
		match self {
			Direction::Honourable => Direction::Dishonourable,
			Direction::Dishonourable => Direction::Honourable,
		}
	}
}

/// Direct a point to a subject.
#[derive(
	Clone, Decode, DecodeWithMemTracking, Encode, Eq, MaxEncodedLen, PartialEq, Debug, TypeInfo,
)]
pub struct VoteData {
	/// The subject that is being voted for.
	pub subject: SubjectId,
	/// The point that will be used for voting.
	pub point: PointId,
	/// In which direction this vote will influence the honour of the subject.
	pub direction: Direction,
}

/// Aliases for corresponding fields of [`VoteData`].
#[derive(
	Clone, Decode, DecodeWithMemTracking, Encode, Eq, MaxEncodedLen, PartialEq, Debug, TypeInfo,
)]
pub struct VoteAliases {
	/// Alias for [`VoteData::subject`].
	pub subject_alias: SubjectAlias,
	/// Alias for [`VoteData::point`].
	pub point_alias: PointAlias,
}

impl VoteAliases {
	/// Unpack aliases produced by proof verification from the array.
	pub fn from_aliases(aliases: [Alias; 2]) -> Self {
		Self { subject_alias: aliases[0], point_alias: aliases[1] }
	}
}

impl VoteData {
	/// Pack the contexts for proof verification into an array.
	pub fn get_contexts(&self) -> [Context; 2] {
		[context::subject(&self.subject), context::point(self.point)]
	}
}

/// Low-level context generation functions.
pub mod context {
	use super::*;
	use indiv_support::traits::Context;

	const POINT_CONTEXT_PREFIX: &[u8; 34] = b"pop:polkadot.network/honour/point:";
	const SUBJECT_CONTEXT_PREFIX: &[u8; 36] = b"pop:polkadot.network/honour/subject:";

	/// Canonical context of a point.
	pub fn point(point: PointId) -> Context {
		let mut input = POINT_CONTEXT_PREFIX.to_vec();
		input.push(point);
		sp_io::hashing::twox_256(&input).into()
	}

	/// Canonical context of a subject.
	pub fn subject(subject: &SubjectId) -> Context {
		let mut input = SUBJECT_CONTEXT_PREFIX.to_vec();
		input.extend_from_slice(subject);
		sp_io::hashing::twox_256(&input).into()
	}
}

/// The default score that a subject will start out with.
///
/// This is -1 to offset self-votes.
pub const SUBJECT_DEFAULT_SCORE: Honour = -1;

/// Read-only traits to inspect the honour system.
pub mod inspect {
	use super::*;

	/// Access honour scores.
	pub trait Score {
		/// Read the honour score of a subject.
		///
		/// Returns the default score value if the subject does not have any ratings yet.
		fn read(subject: &SubjectId) -> Honour;
	}
}
