// This file is part of CORD – https://cord.network

// Copyright (C) Dhiway Networks Pvt. Ltd.
// SPDX-License-Identifier: GPL-3.0-or-later

// CORD is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// CORD is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with CORD. If not, see <https://www.gnu.org/licenses/>.

import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { CLOSED_SCHEMAS, CLOSED_TYPES, CROSS_FIELD_RULES, ERROR_CODES, JSON_PROJECTION_SHA256, OPERATION_CODES, REGISTRY_SHA256, SEMANTIC_SCHEMA_SHA256, SEMANTIC_TABLE_JSON, type CddlTypeName, type ClosedSchemaNode } from './generated/origin-host-registry-v2.ts';

type Cbor = number | bigint | boolean | string | Uint8Array | Cbor[] | Map<Cbor,Cbor>;
const root=process.cwd();
const readJson=(p:string)=>JSON.parse(fs.readFileSync(path.join(root,p),'utf8'));
const hex=(s:string)=>new Uint8Array(Buffer.from(s,'hex'));
const sha=(b:Uint8Array)=>crypto.createHash('sha256').update(b).digest('hex');
function head(major:number,n:number|bigint):Uint8Array { const x=BigInt(n); if(x<24n)return Uint8Array.of((major<<5)|Number(x)); if(x<=255n)return Uint8Array.of((major<<5)|24,Number(x)); const bytes=x<=65535n?2:x<=4294967295n?4:8; const b=Buffer.alloc(1+bytes);b[0]=(major<<5)|(bytes===2?25:bytes===4?26:27);let y=x;for(let i=bytes;i>=1;i--){b[i]=Number(y&255n);y>>=8n}return b; }
const cat=(xs:Uint8Array[])=>new Uint8Array(Buffer.concat(xs.map(x=>Buffer.from(x))));
function encode(v:Cbor):Uint8Array {
 if(typeof v==='boolean')return Uint8Array.of(v?245:244);
 if(typeof v==='number'||typeof v==='bigint')return head(0,v);
 if(typeof v==='string'){const b=new TextEncoder().encode(v);return cat([head(3,b.length),b])}
 if(v instanceof Uint8Array)return cat([head(2,v.length),v]);
 if(Array.isArray(v))return cat([head(4,v.length),...v.map(encode)]);
 if(v instanceof Map){const ps=[...v].map(([k,x])=>[encode(k),encode(x)] as [Uint8Array,Uint8Array]).sort((a,b)=>a[0].length-b[0].length||Buffer.compare(a[0],b[0]));return cat([head(5,ps.length),...ps.flat()])}
 throw new Error('unsupported cbor value');
}
function decode(data:Uint8Array):Cbor {
 let p=0; const take=(n:number)=>{if(p+n>data.length)throw Error('truncated');const b=data.slice(p,p+n);p+=n;return b};
 const uint=(ai:number):bigint=>{if(ai<24)return BigInt(ai);const n=ai===24?1:ai===25?2:ai===26?4:ai===27?8:-1;if(n<0)throw Error('indefinite/reserved');let x=0n;for(const b of take(n))x=(x<<8n)|BigInt(b);return x};
 const one=():Cbor=>{const ib=take(1)[0],m=ib>>5,ai=ib&31,n=uint(ai); if(m===0)return n<=BigInt(Number.MAX_SAFE_INTEGER)?Number(n):n; if(m===2)return take(Number(n)); if(m===3){const s=new TextDecoder('utf-8',{fatal:true}).decode(take(Number(n)));return s} if(m===4){const a:Cbor[]=[];for(let i=0;i<Number(n);i++)a.push(one());return a} if(m===5){const x=new Map<Cbor,Cbor>();for(let i=0;i<Number(n);i++){const k=one();if([...x.keys()].some(q=>Buffer.from(encode(q)).equals(Buffer.from(encode(k)))))throw Error('duplicate map key');x.set(k,one())}return x} if(m===7&&ai===20)return false;if(m===7&&ai===21)return true;throw Error('tags/floats/simple unsupported')};
 const v=one();if(p!==data.length)throw Error('trailing bytes');return v;
}
const map=(v:Cbor)=>{if(!(v instanceof Map))throw Error('expected map');return v};
function isCanonical(raw:Uint8Array):boolean {try{return Buffer.from(encode(decode(raw))).equals(Buffer.from(raw))}catch{return false}}
function mapGet(v:Cbor,k:number):Cbor {const m=map(v);for(const [x,y] of m)if(x===k)return y;throw Error('missing key '+k)}
function verifyEd(publicHex:string,messageHex:string,signatureHex:string){const der=Buffer.concat([Buffer.from('302a300506032b6570032100','hex'),Buffer.from(publicHex,'hex')]);const k=crypto.createPublicKey({key:der,format:'der',type:'spki'});if(!crypto.verify(null,Buffer.from(messageHex,'hex'),k,Buffer.from(signatureHex,'hex')))throw Error('Ed25519 verification failed')}
const rotl=(x:number,n:number)=>(x<<n)|(x>>>(32-n));
function hchacha(key:Uint8Array,nonce:Uint8Array){const s=new Uint32Array(16),c=new TextEncoder().encode('expand 32-byte k');for(let i=0;i<4;i++)s[i]=new DataView(c.buffer).getUint32(i*4,true);for(let i=0;i<8;i++)s[4+i]=new DataView(key.buffer,key.byteOffset).getUint32(i*4,true);for(let i=0;i<4;i++)s[12+i]=new DataView(nonce.buffer,nonce.byteOffset).getUint32(i*4,true);const q=(a:number,b:number,c:number,d:number)=>{s[a]=(s[a]+s[b])>>>0;s[d]=rotl(s[d]^s[a],16);s[c]=(s[c]+s[d])>>>0;s[b]=rotl(s[b]^s[c],12);s[a]=(s[a]+s[b])>>>0;s[d]=rotl(s[d]^s[a],8);s[c]=(s[c]+s[d])>>>0;s[b]=rotl(s[b]^s[c],7)};for(let i=0;i<10;i++){q(0,4,8,12);q(1,5,9,13);q(2,6,10,14);q(3,7,11,15);q(0,5,10,15);q(1,6,11,12);q(2,7,8,13);q(3,4,9,14)}const out=Buffer.alloc(32);[0,1,2,3,12,13,14,15].forEach((j,i)=>out.writeUInt32LE(s[j],i*4));return out}
function xdecrypt(key:Uint8Array,nonce:Uint8Array,aad:Uint8Array,cipherTag:Uint8Array){const sub=hchacha(key,nonce.slice(0,16));const n=Buffer.concat([Buffer.alloc(4),Buffer.from(nonce.slice(16))]);const ct=Buffer.from(cipherTag.slice(0,-16)),tag=Buffer.from(cipherTag.slice(-16));const d=crypto.createDecipheriv('chacha20-poly1305',sub,n,{authTagLength:16});d.setAAD(Buffer.from(aad),{plaintextLength:ct.length});d.setAuthTag(tag);return Buffer.concat([d.update(ct),d.final()])}

class SemanticError extends Error { readonly code:string;constructor(code:string){super(code);this.code=code} }
const fail=(owner:string,path:string,rule:string):never=>{throw new SemanticError(`${owner}:${path}:${rule}`)};
const utf8Length=(value:string)=>new TextEncoder().encode(value).length;
const valueAt=(value:Cbor,key:number):Cbor=>mapGet(value,key);
function validateCross(production:CddlTypeName,value:Cbor):void {
 for(const rule of CROSS_FIELD_RULES)if(rule.production===production){
  const m=map(value);const get=(key:number)=>{for(const [k,v]of m)if(k===key)return v;fail(production,'$','cross:'+rule.id)};
  let ok=true;
  const getUint=(key:number)=>BigInt(get(key) as number|bigint);
  if(rule.kind==='uint-positive')ok=getUint(rule.key)>0n;
  else if(rule.kind==='uint-greater')ok=getUint(rule.left)>getUint(rule.right);
  else if(rule.kind==='uint-delta-max')ok=getUint(rule.left)-getUint(rule.right)<=BigInt(rule.max);
  else if(rule.kind==='bytes-nonzero'){const b=get(rule.key);ok=b instanceof Uint8Array&&b.some(x=>x!==0)}
  else if(rule.kind==='bytes-no-nul'){const b=get(rule.key);ok=b instanceof Uint8Array&&!b.some(x=>x===0)}
  else if(rule.kind==='bytes-array-sorted-unique'){const a=get(rule.key);ok=Array.isArray(a)&&a.every((x,i)=>i===0||Buffer.compare(Buffer.from(encode(a[i-1])),Buffer.from(encode(x)))<0)}
  if(!ok)fail(production,'$','cross:'+rule.id);
 }
}
function validateNode(node:ClosedSchemaNode,value:Cbor,owner:CddlTypeName,p:string):void {
 switch(node.kind){
  case 'ref':validateNamed(node.name,value,p);return;
  case 'union':for(const variant of node.variants){try{validateNode(variant,value,owner,p);return}catch(e){if(!(e instanceof SemanticError))throw e}}return fail(owner,p,'union');
  case 'map':{if(!(value instanceof Map))fail(owner,p,'type-map');const mv=value as Map<Cbor,Cbor>;const fields=new Map(node.fields.map(f=>[f.key,f]));for(const [key]of mv){if(typeof key!=='number'||!Number.isSafeInteger(key)||key<0)fail(owner,p,'integer-key');if(!fields.has(key as number))fail(owner,p,`additionalProperties:${key}`)}for(const field of node.fields){let found=false;let child:Cbor|undefined;for(const [key,v]of mv)if(key===field.key){found=true;child=v;break}if(!found&&field.required)fail(owner,p,`required:${field.key}`);if(found)validateNode(field.schema,child!,owner,`${p}/${field.key}`)}return}
  case 'array':{if(!Array.isArray(value))fail(owner,p,'type-array');const av=value as Cbor[];if(av.length<node.min)fail(owner,p,'minItems');if(av.length>node.max)fail(owner,p,'maxItems');av.forEach((x,i)=>validateNode(node.items,x,owner,`${p}/${i}`));return}
  case 'uint':{if(typeof value!=='number'&&typeof value!=='bigint')fail(owner,p,'type-uint');const n=BigInt(value as number|bigint);if(n<0n)fail(owner,p,'type-uint');if(n<BigInt(node.min))fail(owner,p,'minimum');if(n>BigInt(node.max))fail(owner,p,'maximum');return}
  case 'bytes':{if(!(value instanceof Uint8Array))fail(owner,p,'type-bytes');const bv=value as Uint8Array;if(bv.length<node.min)fail(owner,p,'minBytes');if(bv.length>node.max)fail(owner,p,'maxBytes');return}
  case 'text':{if(typeof value!=='string')fail(owner,p,'type-text');const sv=value as string;if(utf8Length(sv)<node.min)fail(owner,p,'minUtf8Bytes');if(utf8Length(sv)>node.max)fail(owner,p,'maxUtf8Bytes');if(node.nfc&&sv.normalize('NFC')!==sv)fail(owner,p,'nfc');return}
  case 'bool':if(typeof value!=='boolean')fail(owner,p,'type-bool');return;
  case 'const':if(value!==node.value)fail(owner,p,'const');return;
 }
}
function validateNamed(name:CddlTypeName,value:Cbor,p='$'):void {validateNode(CLOSED_SCHEMAS[name],value,name,p);if(p==='$')validateCross(name,value)}
function setMap(value:Cbor,key:number,next:Cbor):void {const m=map(value);for(const [k]of m)if(k===key){m.set(k,next);return}m.set(key,next)}
function sampleNode(node:ClosedSchemaNode):Cbor {switch(node.kind){
 case 'ref':return sampleNamed(node.name);case 'union':return sampleNode(node.variants[0]);case 'map':return new Map(node.fields.filter(f=>f.required).map(f=>[f.key,sampleNode(f.schema)]));case 'array':return Array.from({length:node.min},()=>sampleNode(node.items));case 'uint':{const x=BigInt(node.min);return x<=BigInt(Number.MAX_SAFE_INTEGER)?Number(x):x}case 'bytes':return new Uint8Array(node.min);case 'text':return 'a'.repeat(node.min);case 'bool':return false;case 'const':return node.value}}
function sampleNamed(name:CddlTypeName):Cbor {const value=sampleNode(CLOSED_SCHEMAS[name]);for(const rule of CROSS_FIELD_RULES)if(rule.production===name){if(rule.kind==='uint-positive')setMap(value,rule.key,1);else if(rule.kind==='uint-greater')setMap(value,rule.left,1);else if(rule.kind==='bytes-nonzero'){const b=valueAt(value,rule.key) as Uint8Array;b[0]=1}else if(rule.kind==='bytes-no-nul'){const b=valueAt(value,rule.key) as Uint8Array;b.fill(1)}else if(rule.kind==='bytes-array-sorted-unique'){const item=(CLOSED_SCHEMAS[name] as any).fields.find((f:any)=>f.key===rule.key).schema.items as ClosedSchemaNode;const first=sampleNode(item);let second:Cbor;if(first instanceof Uint8Array){second=first.slice();second[second.length-1]=1}else if(typeof first==='string')second=first+'b';else second=sampleNode(item);setMap(value,rule.key,[first,second])}}return value}
type Mutation={id:string;expected:string;value:Cbor};
function wrongType(node:ClosedSchemaNode):Cbor {if(node.kind==='map'||node.kind==='union'||node.kind==='ref')return [];if(node.kind==='array')return new Map();if(node.kind==='bytes'||node.kind==='text')return 0;if(node.kind==='uint'||node.kind==='const')return new Uint8Array();if(node.kind==='bool')return 0;return 0}
function mutationsNode(node:ClosedSchemaNode,base:Cbor,owner:CddlTypeName,p:string):Mutation[]{const out:Mutation[]=[];
 if(node.kind==='ref'){const nested=mutationsNamed(node.name)[0];if(nested)out.push({id:`${p}:ref:${node.name}:${nested.id}`,expected:nested.expected.replace(`${node.name}:$`,`${node.name}:${p}`),value:nested.value});return out}
 if(node.kind==='union'){out.push({id:`${p}:union`,expected:`${owner}:${p}:union`,value:new Map([[999,0]])});return out}
 if(node.kind==='map'){out.push({id:`${p}:type-map`,expected:`${owner}:${p}:type-map`,value:[]});const unknown=structuredClone(base) as Map<Cbor,Cbor>;unknown.set(65535,0);out.push({id:`${p}:additionalProperties`,expected:`${owner}:${p}:additionalProperties:65535`,value:unknown});for(const f of node.fields){if(f.required){const x=structuredClone(base) as Map<Cbor,Cbor>;x.delete(f.key);out.push({id:`${p}:required:${f.key}`,expected:`${owner}:${p}:required:${f.key}`,value:x})}let child:Cbor|undefined;for(const [k,v]of map(base))if(k===f.key)child=v;if(child===undefined)child=sampleNode(f.schema);for(const n of mutationsNode(f.schema,child,owner,`${p}/${f.key}`)){const x=structuredClone(base);setMap(x,f.key,n.value);out.push({...n,value:x})}}return out}
 if(node.kind==='array'){out.push({id:`${p}:type-array`,expected:`${owner}:${p}:type-array`,value:new Map()});if(node.min>0)out.push({id:`${p}:minItems`,expected:`${owner}:${p}:minItems`,value:[]});if(node.max<4097)out.push({id:`${p}:maxItems`,expected:`${owner}:${p}:maxItems`,value:Array.from({length:node.max+1},()=>sampleNode(node.items))});const a=Array.from({length:Math.max(1,node.min)},()=>sampleNode(node.items));const child=mutationsNode(node.items,a[0],owner,`${p}/0`)[0];if(child){a[0]=child.value;out.push({id:`${p}:items`,expected:child.expected,value:a})}return out}
 if(node.kind==='uint'){out.push({id:`${p}:type-uint`,expected:`${owner}:${p}:type-uint`,value:new Uint8Array()});if(BigInt(node.min)>0n)out.push({id:`${p}:minimum`,expected:`${owner}:${p}:minimum`,value:BigInt(node.min)-1n});if(BigInt(node.max)<18446744073709551615n)out.push({id:`${p}:maximum`,expected:`${owner}:${p}:maximum`,value:BigInt(node.max)+1n});return out}
 if(node.kind==='bytes'){out.push({id:`${p}:type-bytes`,expected:`${owner}:${p}:type-bytes`,value:0});if(node.min>0)out.push({id:`${p}:minBytes`,expected:`${owner}:${p}:minBytes`,value:new Uint8Array(node.min-1)});if(node.max<4194400)out.push({id:`${p}:maxBytes`,expected:`${owner}:${p}:maxBytes`,value:new Uint8Array(node.max+1)});return out}
 if(node.kind==='text'){out.push({id:`${p}:type-text`,expected:`${owner}:${p}:type-text`,value:0});if(node.min>0)out.push({id:`${p}:minUtf8Bytes`,expected:`${owner}:${p}:minUtf8Bytes`,value:'a'.repeat(node.min-1)});if(node.max<10000)out.push({id:`${p}:maxUtf8Bytes`,expected:`${owner}:${p}:maxUtf8Bytes`,value:'a'.repeat(node.max+1)});if(node.nfc&&node.max>=3)out.push({id:`${p}:nfc`,expected:`${owner}:${p}:nfc`,value:'e\u0301'+'a'.repeat(Math.max(0,node.min-3))});return out}
 if(node.kind==='bool')out.push({id:`${p}:type-bool`,expected:`${owner}:${p}:type-bool`,value:0});else if(node.kind==='const')out.push({id:`${p}:const`,expected:`${owner}:${p}:const`,value:typeof node.value==='number'?node.value+1:typeof node.value==='boolean'?!node.value:node.value+'x'});return out}
function mutationsNamed(name:CddlTypeName):Mutation[]{const base=sampleNamed(name);const out=mutationsNode(CLOSED_SCHEMAS[name],base,name,'$');for(const rule of CROSS_FIELD_RULES)if(rule.production===name){const value=sampleNamed(name);if(rule.kind==='uint-positive')setMap(value,rule.key,0);else if(rule.kind==='uint-greater')setMap(value,rule.left,valueAt(value,rule.right));else if(rule.kind==='uint-delta-max')setMap(value,rule.left,BigInt(valueAt(value,rule.right) as number|bigint)+BigInt(rule.max)+1n);else if(rule.kind==='bytes-nonzero')(valueAt(value,rule.key) as Uint8Array).fill(0);else if(rule.kind==='bytes-no-nul')(valueAt(value,rule.key) as Uint8Array)[0]=0;else if(rule.kind==='bytes-array-sorted-unique'){const a=valueAt(value,rule.key) as Cbor[];a[1]=structuredClone(a[0])}out.push({id:`$:cross:${rule.id}`,expected:`${name}:$:cross:${rule.id}`,value})}return out}
const cddl=fs.readFileSync(path.join(root,'docs/specs/origin-host-registry-v2.cddl'),'utf8');if(sha(new TextEncoder().encode(cddl))!==REGISTRY_SHA256)throw Error('generated type drift');
const projectionBytes=new Uint8Array(fs.readFileSync(path.join(root,'docs/specs/origin-host-registry-v2.schema.json')));if(sha(projectionBytes)!==JSON_PROJECTION_SHA256)throw Error('JSON projection drift');if(sha(new TextEncoder().encode(SEMANTIC_TABLE_JSON))!==SEMANTIC_SCHEMA_SHA256)throw Error('semantic table drift');
const operations=readJson('docs/specs/origin-host-registry-v2.operations.json').operations;const errors=readJson('docs/specs/origin-host-registry-v2.errors.json').errors;const schema=readJson('docs/specs/origin-host-registry-v2.schema.json');const host=readJson('docs/specs/origin-host-registry-v2.vectors.json');const protocol=readJson('docs/specs/protocol-executable-v2.vectors.json');const checkpoint=readJson('docs/specs/checkpoint-v2.vectors.json');const providerVectors=readJson('docs/specs/provider-protocol-v1.vectors.json');const outboxVectors=readJson('docs/specs/host-outbox-v1.vectors.json');const identityVectors=readJson('docs/specs/identity-v2.vectors.json');const driveS3Vectors=readJson('docs/specs/drive-s3-v1.vectors.json');
const defs=new Set<string>([...cddl.matchAll(/^([A-Za-z][A-Za-z0-9]*)\s*=/gm)].map(x=>x[1]));const schemaDefs=new Set<string>(Object.keys(schema.$defs));const generatedDefs=new Set<string>(CLOSED_TYPES.map(x=>x.name));
const missingTypes=[...defs].filter(x=>!schemaDefs.has(x)||!generatedDefs.has(x));const extraTypes=[...new Set([...schemaDefs,...generatedDefs])].filter(x=>!defs.has(x));
const productionCoverage:{name:string;positive:number;negative_constraints:string[]}[]=[];const constraintClasses=new Map<string,number>();
for(const name of [...generatedDefs].sort() as CddlTypeName[]){const positive=sampleNamed(name);validateNamed(name,decode(encode(positive)));const negatives=mutationsNamed(name);if(!negatives.length)throw Error('production has no negative coverage '+name);for(const mutation of negatives){const wire=encode(mutation.value);let actual='accepted';try{validateNamed(name,decode(wire))}catch(e){if(e instanceof SemanticError)actual=e.code;else throw e}if(actual!==mutation.expected)throw Error(`semantic mutation mismatch ${name}/${mutation.id}: expected ${mutation.expected}, got ${actual}`);const parts=mutation.expected.split(':');const cls=parts.includes('required')?'required':parts.includes('additionalProperties')?'additionalProperties':parts.includes('cross')?'cross':parts.at(-1)!;constraintClasses.set(cls,(constraintClasses.get(cls)||0)+1)}productionCoverage.push({name,positive:1,negative_constraints:negatives.map(x=>x.id)})}
const opCodes=new Set(operations.map((o:any)=>o.code));const generatedOps=new Set(Object.values(OPERATION_CODES));const missingOps=[...opCodes].filter(x=>!generatedOps.has(x as never));const errorCodes=new Set(errors.map((e:any)=>e.code));const generatedErrors=new Set(Object.values(ERROR_CODES));const missingErrors=[...errorCodes].filter(x=>!generatedErrors.has(x as never));
const hostIds=new Set(host.vectors.map((v:any)=>v.id));const missingVectors:string[]=[];for(const o of operations)for(const id of [...o.positive_vectors,...o.negative_vectors])if(!hostIds.has(id))missingVectors.push(id);for(const e of errors)if(!host.vectors.some((v:any)=>v.code===e.code&&v.kind==='exact-error-event'))missingVectors.push('error-'+e.code);
let canonicalAccepted=0,canonicalRejected=0,schemaRejected=0,semanticVectorAccepted=0,semanticVectorRejected=0;
const operationByCode=new Map<number,any>(operations.map((o:any)=>[o.code,o]));
for(const v of host.vectors){const raw=hex(v.wire_hex);if(v.wire_sha256&&sha(raw)!==v.wire_sha256)throw Error('host wire hash drift '+v.id);const canonical=isCanonical(raw);if(v.valid===false){if(canonical)throw Error('accepted noncanonical '+v.id);canonicalRejected++;continue}if(!canonical)throw Error('rejected canonical '+v.id);canonicalAccepted++;const decoded=decode(raw);let type:CddlTypeName;if(v.kind==='exact-error-event')type='ErrorEventV2';else{const code=Number(mapGet(decoded,3));const op=operationByCode.get(code);if(!op)throw Error('unknown operation code '+code);type=op.cddl.Request.replace(/Request$/,'Frame') as CddlTypeName}try{validateNamed(type,decoded);if(v.kind==='operation-negative'&&v.id.includes('schema-negative'))throw Error('schema negative accepted '+v.id);semanticVectorAccepted++}catch(e){if(v.kind==='operation-negative'&&v.id.includes('schema-negative')&&e instanceof SemanticError&&e.code===`${type}:$:required:8`){schemaRejected++;semanticVectorRejected++}else throw e}}
const corpus=decode(new Uint8Array(fs.readFileSync(path.join(root,'docs/specs/origin-host-registry-v2.vectors.cbor'))));if(!isCanonical(new Uint8Array(fs.readFileSync(path.join(root,'docs/specs/origin-host-registry-v2.vectors.cbor')))))throw Error('vector corpus noncanonical');const rows=mapGet(corpus,1);if(!Array.isArray(rows)||rows.length!==host.concrete_wire_vectors)throw Error('corpus/vector count drift');
let cryptoVerified=0,exactVectors=0,negativeStateAssertions=0;
for(const v of protocol.vectors){const raw=hex(v.canonical_cbor_hex);if(!isCanonical(raw)||sha(raw)!==v.canonical_sha256)throw Error('protocol canonical/hash '+v.id);try{validateNamed(v.type as CddlTypeName,decode(raw))}catch(e){throw Error(`protocol semantic ${v.id}: ${e}`)}semanticVectorAccepted++;if(isCanonical(hex(v.noncanonical_cbor_hex)))throw Error('protocol noncanonical accepted '+v.id);for(const state of ['pre','post'] as const){const stateRaw=hex(v[`${state}_state_cbor_hex`]);if(sha(stateRaw)!==v[`${state}_state_sha256`])throw Error('state hash '+v.id);validateNamed('DurableStateV1',decode(stateRaw));semanticVectorAccepted++}if(sha(hex(v.exact_response_cbor_hex))!==v.exact_response_sha256)throw Error('response hash '+v.id);for(const n of v.negative_vectors){if(!Number.isInteger(n.effect_count)||n.effect_count<0||!Number.isInteger(n.event_count)||n.event_count<0||!/^[0-9a-f]{64}$/.test(n.post_state_sha256))throw Error('inexact negative '+n.id);if(n.expected_error){const registered=errors.find((e:any)=>e.name===n.expected_error);if(!registered||registered.code!==n.expected_error_code)throw Error('negative error registry drift '+n.id)}if(n.id==='outbox-ciphertext-bitflip'){const c=v.crypto;const env=hex(n.canonical_cbor_hex);let rejected=false;try{xdecrypt(hex(c.key_hex),env.slice(1,25),hex(c.aad_cbor_hex),env.slice(25))}catch{rejected=true}if(!rejected)throw Error('outbox corruption accepted')}else{const negativeType=(n.id==='transfer-corrupt-chunk'?'ProviderTransferChunkV1':n.id==='recovery-changed-request'?'StorageObjectPutFrame':v.type) as CddlTypeName;{const expectedSemantic:any={"recovery-install-zero-seed":"RecoveryInstallV2:$:cross:recovery-seed-nonzero","drive-noncanonical-order":"DriveManifestV1:$:cross:drive-cids-sorted-unique","s3-invalid-key-nul":"S3ObjectVersionV1:$:cross:s3-key-no-nul"};let actual='accepted';try{validateNamed(negativeType,decode(hex(n.canonical_cbor_hex)))}catch(e){if(e instanceof SemanticError)actual=e.code;else throw e}if(expectedSemantic[n.id]){if(actual!==expectedSemantic[n.id])throw Error(`protocol negative semantic ${n.id}: expected ${expectedSemantic[n.id]}, got ${actual}`);semanticVectorRejected++}else{if(actual!=='accepted')throw Error(`protocol negative schema ${n.id}/${negativeType}: ${actual}`);semanticVectorAccepted++}}}negativeStateAssertions++}const c=v.crypto||{};if(c.public_key_hex){verifyEd(c.public_key_hex,c.signed_bytes_hex,c.signature_hex);cryptoVerified++}if(c.receipt_public_key_hex){verifyEd(c.receipt_public_key_hex,c.receipt_signed_bytes_hex,c.receipt_signature_hex);cryptoVerified++}if(c.algorithm==='XChaCha20-Poly1305'){const env=hex(c.envelope_hex);const plain=xdecrypt(hex(c.key_hex),env.slice(1,25),hex(c.aad_cbor_hex),env.slice(25));if(Buffer.from(plain).toString('hex')!==c.plaintext_cbor_hex)throw Error('xchacha vector');cryptoVerified++}exactVectors++}
const p=checkpoint.positive;verifyEd(p.public_key_hex,p.digest_hex,p.signature_hex);cryptoVerified++;if(!isCanonical(hex(p.canonical_cbor_hex))||isCanonical(hex(p.noncanonical_cbor_hex)))throw Error('checkpoint canonical');validateNamed('CheckpointSubmissionV2',decode(hex(p.canonical_cbor_hex)));semanticVectorAccepted++;for(const n of checkpoint.negative){let checkpointSemantic='accepted';try{validateNamed('CheckpointSubmissionV2',decode(hex(n.canonical_cbor_hex)))}catch(e){if(e instanceof SemanticError)checkpointSemantic=e.code;else throw e}const expectedCheckpointSemantic=n.id==='checkpoint-wrong-version'?'CheckpointSubmissionV2:$/0:const':'accepted';if(checkpointSemantic!==expectedCheckpointSemantic)throw Error(`checkpoint semantic ${n.id}: expected ${expectedCheckpointSemantic}, got ${checkpointSemantic}`);if(checkpointSemantic==='accepted')semanticVectorAccepted++;else semanticVectorRejected++;if(sha(hex(n.canonical_cbor_hex))!==n.canonical_sha256||sha(hex(n.exact_response_cbor_hex))!==n.exact_response_sha256)throw Error('checkpoint exact hash '+n.id);validateNamed('ErrorEventV2',decode(hex(n.exact_response_cbor_hex)));semanticVectorAccepted++;if(n.expected_error_code!==241&&(n.effect_count!==0||n.event_count!==0||n.pre_state_sha256!==n.post_state_sha256))throw Error('checkpoint rejection state/effect '+n.id);negativeStateAssertions++}
const protocolById=new Map<string,any>(protocol.vectors.map((v:any)=>[v.id,v]));for(const v of [...providerVectors.vectors,...identityVectors.executable_vectors,...driveS3Vectors.vectors]){const a:any=protocolById.get(v.id);if(!a||a.canonical_sha256!==v.canonical_sha256)throw Error('derived exact vector drift '+v.id)}if(outboxVectors.base_vector.canonical_sha256!==protocolById.get('host-outbox-entry-v1').canonical_sha256)throw Error('outbox base drift');let outboxDriftRejections=0;for(const v of outboxVectors.crash_vectors){for(const [hexKey,hashKey]of [['exact_request_cbor_hex','exact_request_sha256'],['pre_state_cbor_hex','pre_state_sha256'],['post_state_cbor_hex','post_state_sha256'],['exact_response_cbor_hex','exact_response_sha256']] as const){const raw=hex(v[hexKey]);if(sha(raw)!==v[hashKey])throw Error(`HostOutboxCrashVector:$:${hashKey}`);const changed=raw.slice();changed[changed.length-1]^=1;if(sha(changed)===v[hashKey])throw Error('outbox hostile drift accepted');outboxDriftRejections++}}
const checkpointExpected=new Map([[220,'STORAGE_CHECKPOINT_WRONG_DOMAIN'],[221,'STORAGE_CHECKPOINT_WRONG_VERSION'],[222,'STORAGE_CHECKPOINT_WRONG_BUCKET'],[223,'STORAGE_CHECKPOINT_WRONG_KEY'],[224,'STORAGE_CHECKPOINT_STALE_NONCE'],[225,'STORAGE_CHECKPOINT_WRONG_WINDOW'],[239,'STORAGE_CHECKPOINT_INSUFFICIENT_QUORUM'],[240,'STORAGE_CHECKPOINT_SEQUENCE_INVALID'],[241,'STORAGE_CHECKPOINT_EQUIVOCATION']]);for(const [code,name] of checkpointExpected){const e=errors.find((x:any)=>x.code===code);if(!e||e.name!==name)throw Error('checkpoint vocabulary');if(!checkpoint.negative.some((x:any)=>x.expected_error_code===code&&x.expected_error===name))throw Error('checkpoint vector missing '+code)}
const rustArg=process.argv.indexOf('--rust-report');const rustReport=rustArg>=0?readJson(process.argv[rustArg+1]):null;if(rustReport&&rustReport.status!=='pass')throw Error('rust conformance failed');const semanticCoverageHash=sha(new TextEncoder().encode(productionCoverage.map(x=>`${x.name}\0${x.negative_constraints.join('\0')}`).join('\n')));if(rustReport&&(rustReport.semantic_schema_sha256!==SEMANTIC_SCHEMA_SHA256||rustReport.semantic_coverage_sha256!==semanticCoverageHash||rustReport.unmatched_productions.length||rustReport.uncovered_constraints.length))throw Error('cross-language semantic coverage drift');
const report={schema_version:2,status:missingTypes.length||extraTypes.length||missingOps.length||missingErrors.length||missingVectors.length?'fail':'pass',authority:{cddl_sha256:REGISTRY_SHA256,json_projection_sha256:JSON_PROJECTION_SHA256,semantic_schema_sha256:SEMANTIC_SCHEMA_SHA256,operations_sha256:sha(new Uint8Array(fs.readFileSync(path.join(root,'docs/specs/origin-host-registry-v2.operations.json')))),errors_sha256:sha(new Uint8Array(fs.readFileSync(path.join(root,'docs/specs/origin-host-registry-v2.errors.json')))),host_vectors_sha256:sha(new Uint8Array(fs.readFileSync(path.join(root,'docs/specs/origin-host-registry-v2.vectors.cbor')))),protocol_vectors_sha256:sha(new Uint8Array(fs.readFileSync(path.join(root,'docs/specs/protocol-executable-v2.vectors.json')))),checkpoint_vectors_sha256:sha(new Uint8Array(fs.readFileSync(path.join(root,'docs/specs/checkpoint-v2.vectors.json')))),provider_vectors_sha256:sha(new Uint8Array(fs.readFileSync(path.join(root,'docs/specs/provider-protocol-v1.vectors.json')))),outbox_vectors_sha256:sha(new Uint8Array(fs.readFileSync(path.join(root,'docs/specs/host-outbox-v1.vectors.json')))),identity_vectors_sha256:sha(new Uint8Array(fs.readFileSync(path.join(root,'docs/specs/identity-v2.vectors.json')))),drive_s3_vectors_sha256:sha(new Uint8Array(fs.readFileSync(path.join(root,'docs/specs/drive-s3-v1.vectors.json'))))},coverage:{operations:operations.length,errors:errors.length,types:defs.size,host_vectors:host.vectors.length,exact_protocol_vectors:exactVectors,missing_operations:missingOps,missing_errors:missingErrors,missing_types:missingTypes,extra_types:extraTypes,missing_vectors:missingVectors,unmatched_productions:[],uncovered_constraints:[],semantic_coverage_sha256:semanticCoverageHash,production_coverage:productionCoverage,constraint_class_coverage:Object.fromEntries([...constraintClasses].sort()),semantic_vector_accepted:semanticVectorAccepted,semantic_vector_rejected:semanticVectorRejected,outbox_drift_rejections:outboxDriftRejections},typescript:{status:'pass',canonical_accepted:canonicalAccepted,canonical_rejected:canonicalRejected,schema_rejected:schemaRejected,crypto_verified:cryptoVerified,negative_state_assertions:negativeStateAssertions,semantic_schema_sha256:SEMANTIC_SCHEMA_SHA256,semantic_coverage_sha256:semanticCoverageHash,unmatched_productions:[],uncovered_constraints:[]},rust:rustReport};
if(report.status!=='pass')throw Error(JSON.stringify(report.coverage));const outArg=process.argv.indexOf('--report');const out=outArg>=0?process.argv[outArg+1]:'target/p0-origin-host-conformance.json';fs.mkdirSync(path.dirname(path.join(root,out)),{recursive:true});fs.writeFileSync(path.join(root,out),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));
