import assert from "node:assert/strict";import{readFileSync}from"node:fs";import{resolve}from"node:path";import test from"node:test";
import{contractDigest,sha256File,validateEqcResult,validateResultSchemaContract,validateServiceSchemaContract,validateSloManifest}from"../../packages/eqc/src/validate.ts";
const repo=resolve(import.meta.dirname,"../../.."),load=(p:string)=>JSON.parse(readFileSync(resolve(repo,p),"utf8")),mp=resolve(repo,"docs/evidence/performance/service-slo-manifest.json"),slo=load("docs/evidence/performance/service-slo-manifest.json"),env=load("docs/evidence/verification/p5/sdk-freeze-ratification-envelope.json"),hash=sha256File(mp),descriptor=contractDigest("descriptor",load("product-sdk/packages/descriptors/generated/orbis-descriptor.json"));
const fixture=(k:string)=>{const r=load(`product-sdk/tests/eqc/fixtures/${k}.schema-only.json`);r.manifest_sha256=hash;r.runtime.descriptor_contract_sha256=descriptor;return r};
test("strict SLO/result contracts derive current target ratification",()=>{const status=validateSloManifest(slo,env);assert.equal(status.ratified,env.derived_status.p0_targets_ratified);validateServiceSchemaContract(load("docs/evidence/performance/service-slo-manifest.schema.json"));validateResultSchemaContract(load("docs/evidence/performance/benchmark-result.schema.json"));for(const k of["E","Q","C"])validateEqcResult(fixture(k),hash,slo,status.ratified)});
test("schema-only inputs cannot smuggle campaign or performance verdicts",()=>{for(const mutation of[(r:any)=>r.verdict.pass=true,(r:any)=>r.samples=1,(r:any)=>r.observations={finalized_successful_eps:999},(r:any)=>r.environment.origin_validators=5,(r:any)=>r.runtime.metadata_hash=`0x${"00".repeat(32)}`,(r:any)=>r.environment.extra=true]){const r=fixture("E");mutation(r);assert.throws(()=>validateEqcResult(r,hash,slo,false))}});
test("campaign claims require ratification/final genesis and recompute thresholds",()=>{const r=fixture("E");r.scope="network-campaign";r.campaign_executed=true;r.samples=100;r.runtime.genesis_status="production-genesis-final";r.environment.warmup_seconds=600;r.environment.measurement_seconds=1800;r.environment.cooldown_seconds=300;r.raw_uri="file://campaign/raw.json";r.observations={finalized_successful_eps:999,inclusion_p95_ms:1,finality_p95_ms:1,sponsored_success_percent:100,storage_headroom_percent:99,p95_resource_percent:1,max_resource_percent:1,finality_lag_blocks:1,cv_percent:1};r.verdict={pass:true,failures:[],bottleneck_attribution:[],recomputed:true};assert.throws(()=>validateEqcResult(r,hash,slo,false),/not ratified/);const signedStatus=true;validateEqcResult(r,hash,slo,signedStatus);r.observations.finalized_successful_eps=1;assert.throws(()=>validateEqcResult(r,hash,slo,signedStatus),/dishonest/)});
test("hostile nested SLO drift is rejected",()=>{for(const mutation of[(m:any)=>m.network.extra=1,(m:any)=>m.campaign.max_cv_percent=11,(m:any)=>m.E.mix_percent.assets=11,(m:any)=>m.C.network.loss_percent=101]){const m=structuredClone(slo);mutation(m);assert.throws(()=>validateSloManifest(m,env))}});
test("manual schema validation rejects numeric strings, boolean strings and bad seeds",()=>{for(const mutation of[(m:any)=>m.campaign.seed="20260713",(m:any)=>m.campaign.seed=20260714,(m:any)=>m.Q.finalized_hash_required="true",(m:any)=>m.C.provider_count="3",(m:any)=>m.E.p95_inclusion_ms=true]){const m=structuredClone(slo);mutation(m);assert.throws(()=>validateSloManifest(m,env))}for(const mutation of[(r:any)=>r.campaign_executed="false",(r:any)=>r.environment.seed="20260713",(r:any)=>r.environment.seed=1,(r:any)=>r.runtime.spec_version="29",(r:any)=>r.verdict.pass="false"]){const r=fixture("E");mutation(r);assert.throws(()=>validateEqcResult(r,hash,slo,false))}});
