#!/usr/bin/env bash
set -euo pipefail

function usage() {
	cat <<'EOF'
Usage: bootstrap.sh [options]

Generate a cord-node-cli bootstrap configuration for the cord-orb runtime.

Options:
  -a, --authorities <count>   Number of validator authority key sets to derive (default: 3)
  -s, --secret <uri>          Secret URI seed used to derive keys (default: development test seed)
  -n, --chain-name <name>     Chain name placed into the configuration (default: "CORD Orb Custom Chain")
  -t, --chain-type <type>     Chain type: dev | local | live (default: local)
  -i, --network-id <id>       Network identifier for SS58 format (default: 105)
  -o, --output <dir>          Directory for generated files (default: current directory)
  -h, --help                  Show this help message

The script writes:
  * config.toml – input for `cord bootstrap-chain`
  * accounts.txt – human-readable key material reference
EOF
}

NUM_AUTHORITIES=3
SECRET="0xf32255f569d8b1a12086dfd194653a5377fafcb67345753987741ec5542920ce"
CHAIN_NAME="CORD Orb Custom Chain"
CHAIN_TYPE="local"
NETWORK_ID=105
OUTPUT_DIR="."

while [[ $# -gt 0 ]]; do
	case "$1" in
	-a|--authorities)
		NUM_AUTHORITIES="$2"
		shift 2
		;;
	-s|--secret)
		SECRET="$2"
		shift 2
		;;
	-n|--chain-name)
		CHAIN_NAME="$2"
		shift 2
		;;
	-t|--chain-type)
		case "$2" in
		dev|local|live)
			CHAIN_TYPE="$2"
			;;
		*)
			echo "Invalid chain type '$2'. Expected one of: dev, local, live." >&2
			exit 1
			;;
		esac
		shift 2
		;;
	-i|--network-id)
		NETWORK_ID="$2"
		shift 2
		;;
	-o|--output)
		OUTPUT_DIR="$2"
		shift 2
		;;
	-h|--help)
		usage
		exit 0
		;;
	*)
		echo "Unknown option: $1" >&2
		usage
		exit 1
		;;
	esac
done

if ! [[ "$NUM_AUTHORITIES" =~ ^[0-9]+$ ]] || [[ "$NUM_AUTHORITIES" -le 0 ]]; then
	echo "Number of authorities must be a positive integer." >&2
	exit 1
fi

mkdir -p "$OUTPUT_DIR"

CONFIG_FILE="$OUTPUT_DIR/config.toml"
ACCOUNTS_FILE="$OUTPUT_DIR/accounts.txt"

CORD_BIN="${CORD_BIN:-./target/release/cord}"
if [[ ! -x "$CORD_BIN" ]]; then
	echo "CORD binary not found at '$CORD_BIN'. Build the node (cargo build --release) or set CORD_BIN." >&2
	exit 1
fi

derive_uri() {
	local path="$1"
	echo "${SECRET}//${path}"
}

inspect_key() {
	local scheme="$1"
	local uri="$2"
	"$CORD_BIN" key inspect -n cord --scheme "$scheme" "$uri"
}

account_id_hex() {
	inspect_key Sr25519 "$1" | awk '/Account ID/ { print $3; exit }'
}

public_key_hex() {
	inspect_key "$1" "$2" | awk '/Public key \(hex\)/ { print $4; exit }'
}

write_accounts_reference() {
	local index="$1"
	local scheme="$2"
	local uri="$3"
	{
		echo "=== Authority $index :: $scheme ==="
		inspect_key "$scheme" "$uri"
		echo ""
	} >>"$ACCOUNTS_FILE"
}

cat >"$CONFIG_FILE" <<EOF
# Custom Orb Chain Configuration
# Auto-generated by scripts/bootstrap.sh

chain_name = "${CHAIN_NAME}"
chain_type = "${CHAIN_TYPE}"
network_id = ${NETWORK_ID}

EOF

printf "# Generated accounts for %s (derived from %s)\n\n" "$CHAIN_NAME" "$SECRET" >"$ACCOUNTS_FILE"

AUTHORITY_ROWS=""
sudo_key_hex=""
sudo_key_ss58=""

for i in $(seq 1 "$NUM_AUTHORITIES"); do
	stash_uri="$(derive_uri "$i")"
	babe_uri="$(derive_uri "${i}//babe")"
	grandpa_uri="$(derive_uri "${i}//gran")"
	audi_uri="$(derive_uri "${i}//audi")"

	stash_hex="$(account_id_hex "$stash_uri")"
	stash_ss58="$(inspect_key Sr25519 "$stash_uri" | awk '/SS58 Address/ { print $3; exit }')"
	babe_hex="$(public_key_hex Sr25519 "$babe_uri")"
	grandpa_hex="$(public_key_hex Ed25519 "$grandpa_uri")"
	audi_hex="$(public_key_hex Sr25519 "$audi_uri")"

	if [[ -z "$sudo_key_hex" ]]; then
		sudo_key_hex="$stash_hex"
		sudo_key_ss58="$stash_ss58"
	fi

	AUTHORITY_ROWS+="  # Authority ${i} (SS58: ${stash_ss58})"$'\n'
	AUTHORITY_ROWS+="  [\"$stash_hex\", \"$babe_hex\", \"$grandpa_hex\", \"$audi_hex\"],"$'\n'

	write_accounts_reference "$i" Sr25519 "$stash_uri"
	write_accounts_reference "$i/babe" Sr25519 "$babe_uri"
	write_accounts_reference "$i/grandpa" Ed25519 "$grandpa_uri"
	write_accounts_reference "$i/authority_discovery" Sr25519 "$audi_uri"
done

{
	echo ""
	if [[ -n "$sudo_key_ss58" ]]; then
		echo "# Sudo (SS58: ${sudo_key_ss58})"
	fi
	echo "sudo_key = \"${sudo_key_hex}\""
	echo ""
	echo "authorities = ["
	printf "%b" "$AUTHORITY_ROWS"
	echo "]"
} >>"$CONFIG_FILE"

echo "Bootstrap configuration written to $CONFIG_FILE"
echo "Reference key material written to $ACCOUNTS_FILE"
