// Copyright (C) Parity Technologies (UK) Ltd.
// This file is part of Individuality.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for `indiv_pallet_score`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 54.0.0
//! DATE: 2026-05-29, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `parity-weights-47fd77b76ec8d751`, CPU: `Intel(R) Xeon(R) CPU @ 2.60GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --extrinsic=*
// --runtime=target/production/wbuild/next-people-paseo-runtime/next_people_paseo_runtime.wasm
// --pallet=indiv_pallet_score
// --header=/home/cattery/actions-runner/_work/individuality/individuality/.github/scripts/cmd/file_header.txt
// --output=/home/cattery/actions-runner/_work/individuality/individuality/pallets/score/src/weights.rs
// --wasm-execution=compiled
// --steps=50
// --repeat=20
// --min-duration=0
// --heap-pages=4096
// --genesis-builder=runtime
// --no-storage-info
// --no-min-squares
// --no-median-slopes
// --template=templates/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `indiv_pallet_score`.
pub trait WeightInfo {
	fn schedule_payout_rounds() -> Weight;
	fn remove_payout_schedule() -> Weight;
	fn transition_round() -> Weight;
	fn operate_payout_round(l: u32, ) -> Weight;
	fn cash_out() -> Weight;
	fn redeem_credit() -> Weight;
	fn register() -> Weight;
	fn set_absence_grace_schedule() -> Weight;
	fn set_personhood_threshold_schedule() -> Weight;
	fn set_manager_account() -> Weight;
	fn as_participant_tx_ext() -> Weight;
}

/// Weights for `indiv_pallet_score` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:1 w:1)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
	/// Storage: `AssetsHolder::BalancesOnHold` (r:1 w:1)
	/// Proof: `AssetsHolder::BalancesOnHold` (`max_values`: None, `max_size`: Some(682), added: 3157, mode: `MaxEncodedLen`)
	/// Storage: `AssetsHolder::Holds` (r:1 w:1)
	/// Proof: `AssetsHolder::Holds` (`max_values`: None, `max_size`: Some(847), added: 3322, mode: `MaxEncodedLen`)
	/// Storage: `Score::RoundSchedules` (r:1 w:1)
	/// Proof: `Score::RoundSchedules` (`max_values`: Some(1), `max_size`: Some(241), added: 736, mode: `MaxEncodedLen`)
	fn schedule_payout_rounds() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `832`
		//  Estimated: `4312`
		// Minimum execution time: 65_831_000 picoseconds.
		Weight::from_parts(67_985_000, 4312)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
			.saturating_add(T::DbWeight::get().reads(1_u64))
	}
	/// Storage: `Score::RoundSchedules` (r:1 w:1)
	/// Proof: `Score::RoundSchedules` (`max_values`: Some(1), `max_size`: Some(241), added: 736, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:1 w:1)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
	/// Storage: `AssetsHolder::Holds` (r:1 w:1)
	/// Proof: `AssetsHolder::Holds` (`max_values`: None, `max_size`: Some(847), added: 3322, mode: `MaxEncodedLen`)
	/// Storage: `AssetsHolder::BalancesOnHold` (r:1 w:1)
	/// Proof: `AssetsHolder::BalancesOnHold` (`max_values`: None, `max_size`: Some(682), added: 3157, mode: `MaxEncodedLen`)
	fn remove_payout_schedule() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1091`
		//  Estimated: `4312`
		// Minimum execution time: 58_816_000 picoseconds.
		Weight::from_parts(60_564_000, 4312)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
			.saturating_add(T::DbWeight::get().reads(1_u64))
	}
	/// Storage: `Score::CurrentRoundIndex` (r:1 w:1)
	/// Proof: `Score::CurrentRoundIndex` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Score::RoundPlanning` (r:1 w:1)
	/// Proof: `Score::RoundPlanning` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `Score::RoundSchedules` (r:1 w:1)
	/// Proof: `Score::RoundSchedules` (`max_values`: Some(1), `max_size`: Some(241), added: 736, mode: `MaxEncodedLen`)
	/// Storage: `Score::CurrentRoundPoints` (r:1 w:1)
	/// Proof: `Score::CurrentRoundPoints` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Score::RoundPayouts` (r:0 w:1)
	/// Proof: `Score::RoundPayouts` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	fn transition_round() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `474`
		//  Estimated: `1726`
		// Minimum execution time: 23_265_000 picoseconds.
		Weight::from_parts(24_445_000, 1726)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: `Score::RoundPayouts` (r:1 w:1)
	/// Proof: `Score::RoundPayouts` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `Score::RoundsPointsForParticipant` (r:10001 w:10000)
	/// Proof: `Score::RoundsPointsForParticipant` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `Score::Participants` (r:10000 w:10000)
	/// Proof: `Score::Participants` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:1 w:1)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
	/// Storage: `AssetsHolder::Holds` (r:1 w:1)
	/// Proof: `AssetsHolder::Holds` (`max_values`: None, `max_size`: Some(847), added: 3322, mode: `MaxEncodedLen`)
	/// Storage: `AssetsHolder::BalancesOnHold` (r:1 w:1)
	/// Proof: `AssetsHolder::BalancesOnHold` (`max_values`: None, `max_size`: Some(682), added: 3157, mode: `MaxEncodedLen`)
	/// The range of component `l` is `[1, 10000]`.
	fn operate_payout_round(l: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2274 + l * (143 ±0)`
		//  Estimated: `4312 + l * (2563 ±0)`
		// Minimum execution time: 123_441_000 picoseconds.
		Weight::from_parts(125_680_000, 4312)
			// Standard Error: 22_375
			.saturating_add(Weight::from_parts(17_224_349, 0).saturating_mul(l.into()))
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(l.into())))
			.saturating_add(T::DbWeight::get().writes(5_u64))
			.saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(l.into())))
			.saturating_add(Weight::from_parts(0, 2563).saturating_mul(l.into()))
	}
	/// Storage: `Score::Participants` (r:1 w:1)
	/// Proof: `Score::Participants` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `Score::CurrentRoundIndex` (r:1 w:0)
	/// Proof: `Score::CurrentRoundIndex` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Score::CurrentRoundPoints` (r:1 w:1)
	/// Proof: `Score::CurrentRoundPoints` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Score::RoundsPointsForParticipant` (r:1 w:1)
	/// Proof: `Score::RoundsPointsForParticipant` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	fn cash_out() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `248`
		//  Estimated: `3553`
		// Minimum execution time: 21_246_000 picoseconds.
		Weight::from_parts(22_011_000, 3553)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `Score::Participants` (r:1 w:1)
	/// Proof: `Score::Participants` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:2 w:2)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
	/// Storage: `AssetsHolder::Holds` (r:1 w:1)
	/// Proof: `AssetsHolder::Holds` (`max_values`: None, `max_size`: Some(847), added: 3322, mode: `MaxEncodedLen`)
	/// Storage: `AssetsHolder::BalancesOnHold` (r:1 w:1)
	/// Proof: `AssetsHolder::BalancesOnHold` (`max_values`: None, `max_size`: Some(682), added: 3157, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn redeem_credit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `929`
		//  Estimated: `7404`
		// Minimum execution time: 108_112_000 picoseconds.
		Weight::from_parts(109_934_000, 7404)
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(7_u64))
	}
	/// Storage: `Score::Participants` (r:1 w:1)
	/// Proof: `Score::Participants` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `People::NextPersonalId` (r:1 w:1)
	/// Proof: `People::NextPersonalId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `People::Keys` (r:1 w:1)
	/// Proof: `People::Keys` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Members::Collections` (r:1 w:0)
	/// Proof: `Members::Collections` (`max_values`: None, `max_size`: Some(646), added: 3121, mode: `MaxEncodedLen`)
	/// Storage: `Members::Members` (r:1 w:1)
	/// Proof: `Members::Members` (`max_values`: None, `max_size`: Some(93), added: 2568, mode: `MaxEncodedLen`)
	/// Storage: `Members::QueuePageIndices` (r:1 w:1)
	/// Proof: `Members::QueuePageIndices` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
	/// Storage: `Members::OnboardingQueue` (r:1 w:1)
	/// Proof: `Members::OnboardingQueue` (`max_values`: None, `max_size`: Some(8206), added: 10681, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `People::CounterForKeys` (r:1 w:1)
	/// Proof: `People::CounterForKeys` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `People::People` (r:0 w:1)
	/// Proof: `People::People` (`max_values`: None, `max_size`: Some(89), added: 2564, mode: `MaxEncodedLen`)
	/// Storage: `People::ReservedPersonalId` (r:0 w:1)
	/// Proof: `People::ReservedPersonalId` (`max_values`: None, `max_size`: Some(16), added: 2491, mode: `MaxEncodedLen`)
	fn register() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `501`
		//  Estimated: `11671`
		// Minimum execution time: 2_601_982_000 picoseconds.
		Weight::from_parts(2_630_878_000, 11671)
			.saturating_add(T::DbWeight::get().reads(9_u64))
			.saturating_add(T::DbWeight::get().writes(9_u64))
	}
	/// Storage: `Score::AbsenceGraceSchedule` (r:0 w:1)
	/// Proof: `Score::AbsenceGraceSchedule` (`max_values`: Some(1), `max_size`: Some(49), added: 544, mode: `MaxEncodedLen`)
	fn set_absence_grace_schedule() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 6_177_000 picoseconds.
		Weight::from_parts(6_659_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
			.saturating_add(T::DbWeight::get().reads(1_u64))
	}
	/// Storage: `Score::PersonhoodThresholdSchedule` (r:0 w:1)
	/// Proof: `Score::PersonhoodThresholdSchedule` (`max_values`: Some(1), `max_size`: Some(129), added: 624, mode: `MaxEncodedLen`)
	fn set_personhood_threshold_schedule() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 6_200_000 picoseconds.
		Weight::from_parts(6_585_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
			.saturating_add(T::DbWeight::get().reads(1_u64))
	}
	fn set_manager_account() -> Weight {
		Weight::from_parts(12_000_000, 3_553)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Score::Participants` (r:1 w:0)
	/// Proof: `Score::Participants` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	fn as_participant_tx_ext() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `248`
		//  Estimated: `3553`
		// Minimum execution time: 13_263_000 picoseconds.
		Weight::from_parts(13_781_000, 3553)
			.saturating_add(T::DbWeight::get().reads(1_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:1 w:1)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
	/// Storage: `AssetsHolder::BalancesOnHold` (r:1 w:1)
	/// Proof: `AssetsHolder::BalancesOnHold` (`max_values`: None, `max_size`: Some(682), added: 3157, mode: `MaxEncodedLen`)
	/// Storage: `AssetsHolder::Holds` (r:1 w:1)
	/// Proof: `AssetsHolder::Holds` (`max_values`: None, `max_size`: Some(847), added: 3322, mode: `MaxEncodedLen`)
	/// Storage: `Score::RoundSchedules` (r:1 w:1)
	/// Proof: `Score::RoundSchedules` (`max_values`: Some(1), `max_size`: Some(241), added: 736, mode: `MaxEncodedLen`)
	fn schedule_payout_rounds() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `832`
		//  Estimated: `4312`
		// Minimum execution time: 65_831_000 picoseconds.
		Weight::from_parts(67_985_000, 4312)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
			.saturating_add(RocksDbWeight::get().reads(1_u64))
	}
	/// Storage: `Score::RoundSchedules` (r:1 w:1)
	/// Proof: `Score::RoundSchedules` (`max_values`: Some(1), `max_size`: Some(241), added: 736, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:1 w:1)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
	/// Storage: `AssetsHolder::Holds` (r:1 w:1)
	/// Proof: `AssetsHolder::Holds` (`max_values`: None, `max_size`: Some(847), added: 3322, mode: `MaxEncodedLen`)
	/// Storage: `AssetsHolder::BalancesOnHold` (r:1 w:1)
	/// Proof: `AssetsHolder::BalancesOnHold` (`max_values`: None, `max_size`: Some(682), added: 3157, mode: `MaxEncodedLen`)
	fn remove_payout_schedule() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1091`
		//  Estimated: `4312`
		// Minimum execution time: 58_816_000 picoseconds.
		Weight::from_parts(60_564_000, 4312)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
			.saturating_add(RocksDbWeight::get().reads(1_u64))
	}
	/// Storage: `Score::CurrentRoundIndex` (r:1 w:1)
	/// Proof: `Score::CurrentRoundIndex` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Score::RoundPlanning` (r:1 w:1)
	/// Proof: `Score::RoundPlanning` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `Score::RoundSchedules` (r:1 w:1)
	/// Proof: `Score::RoundSchedules` (`max_values`: Some(1), `max_size`: Some(241), added: 736, mode: `MaxEncodedLen`)
	/// Storage: `Score::CurrentRoundPoints` (r:1 w:1)
	/// Proof: `Score::CurrentRoundPoints` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Score::RoundPayouts` (r:0 w:1)
	/// Proof: `Score::RoundPayouts` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	fn transition_round() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `474`
		//  Estimated: `1726`
		// Minimum execution time: 23_265_000 picoseconds.
		Weight::from_parts(24_445_000, 1726)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
	/// Storage: `Score::RoundPayouts` (r:1 w:1)
	/// Proof: `Score::RoundPayouts` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `Score::RoundsPointsForParticipant` (r:10001 w:10000)
	/// Proof: `Score::RoundsPointsForParticipant` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `Score::Participants` (r:10000 w:10000)
	/// Proof: `Score::Participants` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:1 w:1)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
	/// Storage: `AssetsHolder::Holds` (r:1 w:1)
	/// Proof: `AssetsHolder::Holds` (`max_values`: None, `max_size`: Some(847), added: 3322, mode: `MaxEncodedLen`)
	/// Storage: `AssetsHolder::BalancesOnHold` (r:1 w:1)
	/// Proof: `AssetsHolder::BalancesOnHold` (`max_values`: None, `max_size`: Some(682), added: 3157, mode: `MaxEncodedLen`)
	/// The range of component `l` is `[1, 10000]`.
	fn operate_payout_round(l: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2274 + l * (143 ±0)`
		//  Estimated: `4312 + l * (2563 ±0)`
		// Minimum execution time: 123_441_000 picoseconds.
		Weight::from_parts(125_680_000, 4312)
			// Standard Error: 22_375
			.saturating_add(Weight::from_parts(17_224_349, 0).saturating_mul(l.into()))
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().reads((2_u64).saturating_mul(l.into())))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
			.saturating_add(RocksDbWeight::get().writes((2_u64).saturating_mul(l.into())))
			.saturating_add(Weight::from_parts(0, 2563).saturating_mul(l.into()))
	}
	/// Storage: `Score::Participants` (r:1 w:1)
	/// Proof: `Score::Participants` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `Score::CurrentRoundIndex` (r:1 w:0)
	/// Proof: `Score::CurrentRoundIndex` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Score::CurrentRoundPoints` (r:1 w:1)
	/// Proof: `Score::CurrentRoundPoints` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Score::RoundsPointsForParticipant` (r:1 w:1)
	/// Proof: `Score::RoundsPointsForParticipant` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	fn cash_out() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `248`
		//  Estimated: `3553`
		// Minimum execution time: 21_246_000 picoseconds.
		Weight::from_parts(22_011_000, 3553)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `Score::Participants` (r:1 w:1)
	/// Proof: `Score::Participants` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:2 w:2)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
	/// Storage: `AssetsHolder::Holds` (r:1 w:1)
	/// Proof: `AssetsHolder::Holds` (`max_values`: None, `max_size`: Some(847), added: 3322, mode: `MaxEncodedLen`)
	/// Storage: `AssetsHolder::BalancesOnHold` (r:1 w:1)
	/// Proof: `AssetsHolder::BalancesOnHold` (`max_values`: None, `max_size`: Some(682), added: 3157, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn redeem_credit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `929`
		//  Estimated: `7404`
		// Minimum execution time: 108_112_000 picoseconds.
		Weight::from_parts(109_934_000, 7404)
			.saturating_add(RocksDbWeight::get().reads(7_u64))
			.saturating_add(RocksDbWeight::get().writes(7_u64))
	}
	/// Storage: `Score::Participants` (r:1 w:1)
	/// Proof: `Score::Participants` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `People::NextPersonalId` (r:1 w:1)
	/// Proof: `People::NextPersonalId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `People::Keys` (r:1 w:1)
	/// Proof: `People::Keys` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Members::Collections` (r:1 w:0)
	/// Proof: `Members::Collections` (`max_values`: None, `max_size`: Some(646), added: 3121, mode: `MaxEncodedLen`)
	/// Storage: `Members::Members` (r:1 w:1)
	/// Proof: `Members::Members` (`max_values`: None, `max_size`: Some(93), added: 2568, mode: `MaxEncodedLen`)
	/// Storage: `Members::QueuePageIndices` (r:1 w:1)
	/// Proof: `Members::QueuePageIndices` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
	/// Storage: `Members::OnboardingQueue` (r:1 w:1)
	/// Proof: `Members::OnboardingQueue` (`max_values`: None, `max_size`: Some(8206), added: 10681, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `People::CounterForKeys` (r:1 w:1)
	/// Proof: `People::CounterForKeys` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `People::People` (r:0 w:1)
	/// Proof: `People::People` (`max_values`: None, `max_size`: Some(89), added: 2564, mode: `MaxEncodedLen`)
	/// Storage: `People::ReservedPersonalId` (r:0 w:1)
	/// Proof: `People::ReservedPersonalId` (`max_values`: None, `max_size`: Some(16), added: 2491, mode: `MaxEncodedLen`)
	fn register() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `501`
		//  Estimated: `11671`
		// Minimum execution time: 2_601_982_000 picoseconds.
		Weight::from_parts(2_630_878_000, 11671)
			.saturating_add(RocksDbWeight::get().reads(9_u64))
			.saturating_add(RocksDbWeight::get().writes(9_u64))
	}
	/// Storage: `Score::AbsenceGraceSchedule` (r:0 w:1)
	/// Proof: `Score::AbsenceGraceSchedule` (`max_values`: Some(1), `max_size`: Some(49), added: 544, mode: `MaxEncodedLen`)
	fn set_absence_grace_schedule() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 6_177_000 picoseconds.
		Weight::from_parts(6_659_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
			.saturating_add(RocksDbWeight::get().reads(1_u64))
	}
	/// Storage: `Score::PersonhoodThresholdSchedule` (r:0 w:1)
	/// Proof: `Score::PersonhoodThresholdSchedule` (`max_values`: Some(1), `max_size`: Some(129), added: 624, mode: `MaxEncodedLen`)
	fn set_personhood_threshold_schedule() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 6_200_000 picoseconds.
		Weight::from_parts(6_585_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
			.saturating_add(RocksDbWeight::get().reads(1_u64))
	}
	fn set_manager_account() -> Weight {
		Weight::from_parts(12_000_000, 3_553)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Score::Participants` (r:1 w:0)
	/// Proof: `Score::Participants` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	fn as_participant_tx_ext() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `248`
		//  Estimated: `3553`
		// Minimum execution time: 13_263_000 picoseconds.
		Weight::from_parts(13_781_000, 3553)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
	}
}
