// This file is part of CORD – https://cord.network

// Copyright (C) Dhiway Networks Pvt. Ltd.
// SPDX-License-Identifier: GPL-3.0-or-later

// CORD is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// CORD is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with CORD. If not, see <https://www.gnu.org/licenses/>.

import { ProductSdkError } from "../../core/src/contract.ts";
import type { TypedFinalizedEvent, TypedFinalizedEventSource } from "./attestation-events.ts";
import { storageNativeEventOutcome, type FinalizedStorageNativeEvent, type StorageNativeEvent, type StorageNativeEventKind, type StorageNativeEventSubscription, type StorageNativeOutcome } from "@cord-network/origin-sdk-cloud-storage";
import type { AccountId, AgreementId, BlockHash, BlockNumber, BucketId, ChallengeId, ContentCommitment, DecimalU64, DriveId, ObjectId, ProviderId } from "@cord-network/origin-sdk-cloud-storage";
export interface FinalizedStorageNativeOutcome{readonly event:FinalizedStorageNativeEvent;readonly outcome:StorageNativeOutcome}
const HASH=/^0x[0-9a-f]{64}$/i,DECIMAL=/^(0|[1-9][0-9]*)$/,U64=18_446_744_073_709_551_615n;
function reject(m:string):never{throw new ProductSdkError("runtime_rejected",m)}
function hash(v:unknown,f:string):string{if(typeof v!=="string"||!HASH.test(v))reject(`Storage.${f} is not a hash`);return v.toLowerCase()}
function account(v:unknown,f:string):AccountId{if(typeof v!=="string"||v.length<1||v.length>128)reject(`Storage.${f} is not an account`);return v as AccountId}
function dec(v:unknown,f:string):DecimalU64{const s=typeof v==="bigint"||typeof v==="number"||typeof v==="string"?String(v):"";if(!DECIMAL.test(s)||BigInt(s)>U64)reject(`Storage.${f} is not u64`);return s as DecimalU64}
function block(v:unknown,f:string):BlockNumber{const s=dec(v,f);if(BigInt(s)>0xffff_ffffn)reject(`Storage.${f} is not block number`);return s as BlockNumber}
function bool(v:unknown,f:string):boolean{if(typeof v!=="boolean")reject(`Storage.${f} is not boolean`);return v}
function bytes(v:unknown,f:string):string{if(typeof v==="string"&&!v.startsWith("0x"))return v;let b:Uint8Array|undefined;if(typeof v==="string"&&/^0x(?:[0-9a-f]{2})*$/i.test(v))b=Uint8Array.from(v.slice(2).match(/../g)?.map(x=>parseInt(x,16))??[]);else if(v instanceof Uint8Array)b=v;else if(Array.isArray(v)&&v.every(x=>Number.isInteger(x)&&x>=0&&x<=255))b=Uint8Array.from(v);else if(v&&typeof v==="object"){const x=v as any;if(typeof x.asBytes==="function")return bytes(x.asBytes(),f);if(typeof x.toHex==="function")return bytes(x.toHex(),f);if("value" in x)return bytes(x.value,f)}if(!b)reject(`Storage.${f} is not descriptor bytes`);try{return new TextDecoder("utf-8",{fatal:true}).decode(b)}catch{reject(`Storage.${f} is not UTF-8`)}}
function data(n:TypedFinalizedEvent):Readonly<Record<string,unknown>>{if(!n.data||typeof n.data!=="object"||Array.isArray(n.data))reject(`Storage.${n.event} data is not object`);return n.data}
const provider=(v:unknown)=>account(v,"provider") as ProviderId, agreement=(v:unknown)=>hash(v,"agreement") as AgreementId,challenge=(v:unknown)=>hash(v,"challenge") as ChallengeId,drive=(v:unknown)=>hash(v,"drive") as DriveId,bucket=(v:unknown)=>hash(v,"bucket") as BucketId,object=(v:unknown)=>hash(v,"object") as ObjectId,commit=(v:unknown,f:string)=>hash(v,f) as ContentCommitment;
export function decodeStorageNativeEvent(n:TypedFinalizedEvent):StorageNativeEvent|null{if(!["StorageProvider","Drive","S3"].includes(n.pallet))return null;const d=data(n);switch(`${n.pallet}.${n.event}`){
case"StorageProvider.ProviderRegistered":return{event:"provider_registered",data:{provider:provider(d.provider),capacity_bytes:dec(d.capacity_bytes,"capacity_bytes")}};case"StorageProvider.ProviderUpdated":return{event:"provider_updated",data:{provider:provider(d.provider),capacity_bytes:dec(d.capacity_bytes,"capacity_bytes")}};case"StorageProvider.ProviderStatusChanged":{const s=String(d.status).toLowerCase();if(!["active","suspended"].includes(s))reject("Storage.status unknown");return{event:"provider_status_changed",data:{provider:provider(d.provider),status:s as "active"|"suspended"}}}case"StorageProvider.ProviderRemoved":return{event:"provider_removed",data:{provider:provider(d.provider)}};case"StorageProvider.Heartbeat":return{event:"heartbeat",data:{provider:provider(d.provider),at:block(d.at,"at")}};
case"StorageProvider.AgreementProposed":return{event:"agreement_proposed",data:{agreement:agreement(d.agreement_id),owner:account(d.owner,"owner"),provider:provider(d.provider)}};case"StorageProvider.AgreementAccepted":return{event:"agreement_accepted",data:{agreement:agreement(d.agreement_id)}};case"StorageProvider.AgreementCancelled":return{event:"agreement_cancelled",data:{agreement:agreement(d.agreement_id)}};case"StorageProvider.AgreementRenewalRequested":return{event:"agreement_renewal_requested",data:{agreement:agreement(d.agreement_id),expires_at:block(d.expires_at,"expires_at")}};case"StorageProvider.AgreementRenewed":return{event:"agreement_renewed",data:{agreement:agreement(d.agreement_id),expires_at:block(d.expires_at,"expires_at")}};case"StorageProvider.AgreementExpired":return{event:"agreement_expired",data:{agreement:agreement(d.agreement_id)}};case"StorageProvider.AgreementPruned":return{event:"agreement_pruned",data:{agreement:agreement(d.agreement_id)}};
case"StorageProvider.ChallengeIssued":return{event:"challenge_issued",data:{challenge:challenge(d.challenge_id),provider:provider(d.provider),due_at:block(d.due_at,"due_at")}};case"StorageProvider.CheckpointSubmitted":return{event:"checkpoint_submitted",data:{challenge:challenge(d.challenge_id),proof_commitment:commit(d.proof_commitment,"proof_commitment")}};case"StorageProvider.ChallengeTimedOut":return{event:"challenge_timed_out",data:{challenge:challenge(d.challenge_id),provider:provider(d.provider)}};case"StorageProvider.ProviderRootCommitted":return{event:"provider_root_committed",data:{provider:provider(d.provider),sequence:dec(d.sequence,"sequence"),root:commit(d.root,"root"),leaf_count:dec(d.leaf_count,"leaf_count")}};case"StorageProvider.DeletionAcknowledged":return{event:"deletion_acknowledged",data:{agreement:agreement(d.agreement_id),provider:provider(d.provider),content_commitment:commit(d.content_commitment,"content_commitment"),tombstone_root:commit(d.tombstone_root,"tombstone_root"),root_sequence:dec(d.root_sequence,"root_sequence"),leaf_index:dec(d.leaf_index,"leaf_index"),leaf_count:dec(d.leaf_count,"leaf_count"),proof_commitment:commit(d.proof_commitment,"proof_commitment")}};
case"Drive.DriveCreated":return{event:"drive_created",data:{drive:drive(d.drive_id),owner:account(d.owner,"owner")}};case"Drive.DriveRootUpdated":return{event:"drive_root_updated",data:{drive:drive(d.drive_id),version:dec(d.version,"version")}};case"Drive.ControllerChanged":return{event:"drive_controller_changed",data:{drive:drive(d.drive_id),controller:account(d.controller,"controller"),enabled:bool(d.enabled,"enabled")}};case"Drive.DriveTransferred":return{event:"drive_transferred",data:{drive:drive(d.drive_id),old_owner:account(d.old_owner,"old_owner"),new_owner:account(d.new_owner,"new_owner")}};case"Drive.DriveArchived":return{event:"drive_archived",data:{drive:drive(d.drive_id)}};
case"S3.BucketCreated":return{event:"bucket_created",data:{bucket:bucket(d.bucket),name:bytes(d.name,"name"),owner:account(d.owner,"owner")}};case"S3.ControllerChanged":return{event:"bucket_controller_changed",data:{bucket:bucket(d.bucket),controller:account(d.controller,"controller"),enabled:bool(d.enabled,"enabled"),version:dec(d.version,"version")}};case"S3.BucketTransferred":return{event:"bucket_transferred",data:{bucket:bucket(d.bucket),from:account(d.from,"from"),to:account(d.to,"to"),version:dec(d.version,"version")}};case"S3.BucketArchived":return{event:"bucket_archived",data:{bucket:bucket(d.bucket),archived:bool(d.archived,"archived"),version:dec(d.version,"version")}};case"S3.BucketVersioningChanged":return{event:"bucket_versioning_changed",data:{bucket:bucket(d.bucket),enabled:bool(d.enabled,"enabled"),version:dec(d.version,"version")}};case"S3.ObjectPut":return{event:"object_put",data:{bucket:bucket(d.bucket),object:object(d.object),key:bytes(d.key,"key"),content_commitment:commit(d.content_hash,"content_hash"),version:dec(d.version,"version")}};case"S3.ObjectDeleted":return{event:"object_deleted",data:{bucket:bucket(d.bucket),object:object(d.object),key:bytes(d.key,"key"),version:dec(d.version,"version")}};case"S3.BucketDeleted":return{event:"bucket_deleted",data:{bucket:bucket(d.bucket),name:bytes(d.name,"name"),owner:account(d.owner,"owner")}};default:throw new ProductSdkError("unsupported_runtime",`unknown native storage event ${n.pallet}.${n.event}`)}}
export async function* subscribeStorageNativeEvents(source:TypedFinalizedEventSource,subscription:StorageNativeEventSubscription,signal:AbortSignal=new AbortController().signal):AsyncGenerator<FinalizedStorageNativeOutcome>{const wanted=new Set<StorageNativeEventKind>(subscription.kinds);for await(const b of source.subscribeFinalizedEvents({from:subscription.from_finalized_block,signal})){if(signal.aborted)throw new ProductSdkError("cancelled","storage subscription cancelled");const finalized=hash(b.hash,"finalized_block_hash") as BlockHash;for(const n of b.events){if(!Number.isSafeInteger(n.index)||n.index<0||n.index>0xffff_ffff)reject("Storage event index is not u32");const e=decodeStorageNativeEvent(n);if(!e||!wanted.has(e.event))continue;const event:FinalizedStorageNativeEvent={finalized_block_hash:finalized,event_index:n.index,event:e};yield{event,outcome:storageNativeEventOutcome(e)}}}}
