// This file is part of CORD – https://cord.network

// Copyright (C) Dhiway Networks Pvt. Ltd.
// SPDX-License-Identifier: GPL-3.0-or-later

// CORD is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// CORD is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with CORD. If not, see <https://www.gnu.org/licenses/>.

//! Autogenerated weights for `pallet_did`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2024-05-09, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `cord-benchmark-8gb`, CPU: `AMD EPYC 7B12`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: 1024

// Executed Command:
// ./target/production/cord
// benchmark
// pallet
// --chain=dev
// --steps=50
// --repeat=20
// --pallet=pallet_did
// --extrinsic=*
// --wasm-execution=compiled
// --heap-pages=4096
// --header=./HEADER-GPL3
// --output=./runtime/src/weights/

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_did`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_did::WeightInfo for WeightInfo<T> {
	/// Storage: `Did::DidBlacklist` (r:1 w:0)
	/// Proof: `Did::DidBlacklist` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2184), added: 4659, mode: `MaxEncodedLen`)
	/// Storage: `Did::DidEndpointsCount` (r:0 w:1)
	/// Proof: `Did::DidEndpointsCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Did::ServiceEndpoints` (r:0 w:25)
	/// Proof: `Did::ServiceEndpoints` (`max_values`: None, `max_size`: Some(413), added: 2888, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 10]`.
	/// The range of component `c` is `[1, 25]`.
	fn create_ed25519_keys(n: u32, c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `42`
		//  Estimated: `5649`
		// Minimum execution time: 106_890_000 picoseconds.
		Weight::from_parts(97_902_805, 0)
			.saturating_add(Weight::from_parts(0, 5649))
			// Standard Error: 89_930
			.saturating_add(Weight::from_parts(1_217_921, 0).saturating_mul(n.into()))
			// Standard Error: 34_769
			.saturating_add(Weight::from_parts(7_174_474, 0).saturating_mul(c.into()))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(c.into())))
	}
	/// Storage: `Did::DidBlacklist` (r:1 w:0)
	/// Proof: `Did::DidBlacklist` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2184), added: 4659, mode: `MaxEncodedLen`)
	/// Storage: `Did::DidEndpointsCount` (r:0 w:1)
	/// Proof: `Did::DidEndpointsCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Did::ServiceEndpoints` (r:0 w:25)
	/// Proof: `Did::ServiceEndpoints` (`max_values`: None, `max_size`: Some(413), added: 2888, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 10]`.
	/// The range of component `c` is `[1, 25]`.
	fn create_sr25519_keys(n: u32, c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `42`
		//  Estimated: `5649`
		// Minimum execution time: 96_260_000 picoseconds.
		Weight::from_parts(87_882_291, 0)
			.saturating_add(Weight::from_parts(0, 5649))
			// Standard Error: 70_669
			.saturating_add(Weight::from_parts(923_434, 0).saturating_mul(n.into()))
			// Standard Error: 27_323
			.saturating_add(Weight::from_parts(8_073_076, 0).saturating_mul(c.into()))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(c.into())))
	}
	/// Storage: `Did::DidBlacklist` (r:1 w:0)
	/// Proof: `Did::DidBlacklist` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2184), added: 4659, mode: `MaxEncodedLen`)
	/// Storage: `Did::DidEndpointsCount` (r:0 w:1)
	/// Proof: `Did::DidEndpointsCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Did::ServiceEndpoints` (r:0 w:25)
	/// Proof: `Did::ServiceEndpoints` (`max_values`: None, `max_size`: Some(413), added: 2888, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 10]`.
	/// The range of component `c` is `[1, 25]`.
	fn create_ecdsa_keys(n: u32, c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `42`
		//  Estimated: `5649`
		// Minimum execution time: 94_060_000 picoseconds.
		Weight::from_parts(79_829_920, 0)
			.saturating_add(Weight::from_parts(0, 5649))
			// Standard Error: 92_347
			.saturating_add(Weight::from_parts(1_188_009, 0).saturating_mul(n.into()))
			// Standard Error: 35_704
			.saturating_add(Weight::from_parts(7_251_639, 0).saturating_mul(c.into()))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(c.into())))
	}
	/// Storage: `Did::DidEndpointsCount` (r:1 w:1)
	/// Proof: `Did::DidEndpointsCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Did::ServiceEndpoints` (r:25 w:25)
	/// Proof: `Did::ServiceEndpoints` (`max_values`: None, `max_size`: Some(413), added: 2888, mode: `MaxEncodedLen`)
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2184), added: 4659, mode: `MaxEncodedLen`)
	/// Storage: `Did::DidBlacklist` (r:0 w:1)
	/// Proof: `Did::DidBlacklist` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// The range of component `c` is `[1, 25]`.
	fn delete(c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `364 + c * (105 ±0)`
		//  Estimated: `5649 + c * (2888 ±0)`
		// Minimum execution time: 26_500_000 picoseconds.
		Weight::from_parts(26_746_414, 0)
			.saturating_add(Weight::from_parts(0, 5649))
			// Standard Error: 6_049
			.saturating_add(Weight::from_parts(1_261_504, 0).saturating_mul(c.into()))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(c.into())))
			.saturating_add(T::DbWeight::get().writes(3))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(c.into())))
			.saturating_add(Weight::from_parts(0, 2888).saturating_mul(c.into()))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2184), added: 4659, mode: `MaxEncodedLen`)
	fn submit_did_call_ed25519_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `233`
		//  Estimated: `5649`
		// Minimum execution time: 83_500_000 picoseconds.
		Weight::from_parts(86_560_000, 0)
			.saturating_add(Weight::from_parts(0, 5649))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2184), added: 4659, mode: `MaxEncodedLen`)
	fn submit_did_call_sr25519_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `233`
		//  Estimated: `5649`
		// Minimum execution time: 68_071_000 picoseconds.
		Weight::from_parts(70_910_000, 0)
			.saturating_add(Weight::from_parts(0, 5649))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2184), added: 4659, mode: `MaxEncodedLen`)
	fn submit_did_call_ecdsa_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `234`
		//  Estimated: `5649`
		// Minimum execution time: 69_370_000 picoseconds.
		Weight::from_parts(72_720_000, 0)
			.saturating_add(Weight::from_parts(0, 5649))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2184), added: 4659, mode: `MaxEncodedLen`)
	fn set_ed25519_authentication_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1457`
		//  Estimated: `5649`
		// Minimum execution time: 26_400_000 picoseconds.
		Weight::from_parts(30_130_000, 0)
			.saturating_add(Weight::from_parts(0, 5649))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2184), added: 4659, mode: `MaxEncodedLen`)
	fn set_sr25519_authentication_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1457`
		//  Estimated: `5649`
		// Minimum execution time: 26_070_000 picoseconds.
		Weight::from_parts(29_151_000, 0)
			.saturating_add(Weight::from_parts(0, 5649))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2184), added: 4659, mode: `MaxEncodedLen`)
	fn set_ecdsa_authentication_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1460`
		//  Estimated: `5649`
		// Minimum execution time: 25_650_000 picoseconds.
		Weight::from_parts(29_391_000, 0)
			.saturating_add(Weight::from_parts(0, 5649))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2184), added: 4659, mode: `MaxEncodedLen`)
	fn set_ed25519_delegation_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1457`
		//  Estimated: `5649`
		// Minimum execution time: 28_740_000 picoseconds.
		Weight::from_parts(34_840_000, 0)
			.saturating_add(Weight::from_parts(0, 5649))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2184), added: 4659, mode: `MaxEncodedLen`)
	fn set_sr25519_delegation_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1457`
		//  Estimated: `5649`
		// Minimum execution time: 29_991_000 picoseconds.
		Weight::from_parts(33_280_000, 0)
			.saturating_add(Weight::from_parts(0, 5649))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2184), added: 4659, mode: `MaxEncodedLen`)
	fn set_ecdsa_delegation_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1460`
		//  Estimated: `5649`
		// Minimum execution time: 26_520_000 picoseconds.
		Weight::from_parts(30_620_000, 0)
			.saturating_add(Weight::from_parts(0, 5649))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2184), added: 4659, mode: `MaxEncodedLen`)
	fn remove_ed25519_delegation_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1457`
		//  Estimated: `5649`
		// Minimum execution time: 24_350_000 picoseconds.
		Weight::from_parts(27_350_000, 0)
			.saturating_add(Weight::from_parts(0, 5649))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2184), added: 4659, mode: `MaxEncodedLen`)
	fn remove_sr25519_delegation_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1457`
		//  Estimated: `5649`
		// Minimum execution time: 24_570_000 picoseconds.
		Weight::from_parts(26_380_000, 0)
			.saturating_add(Weight::from_parts(0, 5649))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2184), added: 4659, mode: `MaxEncodedLen`)
	fn remove_ecdsa_delegation_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1460`
		//  Estimated: `5649`
		// Minimum execution time: 24_150_000 picoseconds.
		Weight::from_parts(25_760_000, 0)
			.saturating_add(Weight::from_parts(0, 5649))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2184), added: 4659, mode: `MaxEncodedLen`)
	fn set_ed25519_assertion_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1457`
		//  Estimated: `5649`
		// Minimum execution time: 27_520_000 picoseconds.
		Weight::from_parts(29_980_000, 0)
			.saturating_add(Weight::from_parts(0, 5649))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2184), added: 4659, mode: `MaxEncodedLen`)
	fn set_sr25519_assertion_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1457`
		//  Estimated: `5649`
		// Minimum execution time: 27_320_000 picoseconds.
		Weight::from_parts(29_200_000, 0)
			.saturating_add(Weight::from_parts(0, 5649))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2184), added: 4659, mode: `MaxEncodedLen`)
	fn set_ecdsa_assertion_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1460`
		//  Estimated: `5649`
		// Minimum execution time: 25_670_000 picoseconds.
		Weight::from_parts(27_570_000, 0)
			.saturating_add(Weight::from_parts(0, 5649))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2184), added: 4659, mode: `MaxEncodedLen`)
	fn remove_ed25519_assertion_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1457`
		//  Estimated: `5649`
		// Minimum execution time: 24_630_000 picoseconds.
		Weight::from_parts(28_551_000, 0)
			.saturating_add(Weight::from_parts(0, 5649))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2184), added: 4659, mode: `MaxEncodedLen`)
	fn remove_sr25519_assertion_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1457`
		//  Estimated: `5649`
		// Minimum execution time: 26_369_000 picoseconds.
		Weight::from_parts(29_131_000, 0)
			.saturating_add(Weight::from_parts(0, 5649))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2184), added: 4659, mode: `MaxEncodedLen`)
	fn remove_ecdsa_assertion_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1460`
		//  Estimated: `5649`
		// Minimum execution time: 24_550_000 picoseconds.
		Weight::from_parts(25_829_000, 0)
			.saturating_add(Weight::from_parts(0, 5649))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2184), added: 4659, mode: `MaxEncodedLen`)
	fn add_ed25519_key_agreement_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1355`
		//  Estimated: `5649`
		// Minimum execution time: 26_031_000 picoseconds.
		Weight::from_parts(27_940_000, 0)
			.saturating_add(Weight::from_parts(0, 5649))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2184), added: 4659, mode: `MaxEncodedLen`)
	fn add_sr25519_key_agreement_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1355`
		//  Estimated: `5649`
		// Minimum execution time: 25_811_000 picoseconds.
		Weight::from_parts(28_750_000, 0)
			.saturating_add(Weight::from_parts(0, 5649))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2184), added: 4659, mode: `MaxEncodedLen`)
	fn add_ecdsa_key_agreement_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1358`
		//  Estimated: `5649`
		// Minimum execution time: 25_610_000 picoseconds.
		Weight::from_parts(28_950_000, 0)
			.saturating_add(Weight::from_parts(0, 5649))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2184), added: 4659, mode: `MaxEncodedLen`)
	fn remove_ed25519_key_agreement_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1457`
		//  Estimated: `5649`
		// Minimum execution time: 24_130_000 picoseconds.
		Weight::from_parts(25_480_000, 0)
			.saturating_add(Weight::from_parts(0, 5649))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2184), added: 4659, mode: `MaxEncodedLen`)
	fn remove_sr25519_key_agreement_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1457`
		//  Estimated: `5649`
		// Minimum execution time: 23_960_000 picoseconds.
		Weight::from_parts(26_489_000, 0)
			.saturating_add(Weight::from_parts(0, 5649))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2184), added: 4659, mode: `MaxEncodedLen`)
	fn remove_ecdsa_key_agreement_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1460`
		//  Estimated: `5649`
		// Minimum execution time: 23_730_000 picoseconds.
		Weight::from_parts(25_170_000, 0)
			.saturating_add(Weight::from_parts(0, 5649))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2184), added: 4659, mode: `MaxEncodedLen`)
	/// Storage: `Did::DidEndpointsCount` (r:1 w:1)
	/// Proof: `Did::DidEndpointsCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Did::ServiceEndpoints` (r:1 w:1)
	/// Proof: `Did::ServiceEndpoints` (`max_values`: None, `max_size`: Some(413), added: 2888, mode: `MaxEncodedLen`)
	fn add_service_endpoint() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `905`
		//  Estimated: `5649`
		// Minimum execution time: 31_220_000 picoseconds.
		Weight::from_parts(33_060_000, 0)
			.saturating_add(Weight::from_parts(0, 5649))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2184), added: 4659, mode: `MaxEncodedLen`)
	/// Storage: `Did::ServiceEndpoints` (r:1 w:1)
	/// Proof: `Did::ServiceEndpoints` (`max_values`: None, `max_size`: Some(413), added: 2888, mode: `MaxEncodedLen`)
	/// Storage: `Did::DidEndpointsCount` (r:1 w:1)
	/// Proof: `Did::DidEndpointsCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn remove_service_endpoint() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1286`
		//  Estimated: `5649`
		// Minimum execution time: 30_980_000 picoseconds.
		Weight::from_parts(33_169_000, 0)
			.saturating_add(Weight::from_parts(0, 5649))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `Did::Did` (r:1 w:0)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2184), added: 4659, mode: `MaxEncodedLen`)
	/// The range of component `l` is `[1, 5242880]`.
	fn signature_verification_sr25519(l: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1459`
		//  Estimated: `5649`
		// Minimum execution time: 59_120_000 picoseconds.
		Weight::from_parts(61_131_000, 0)
			.saturating_add(Weight::from_parts(0, 5649))
			// Standard Error: 1
			.saturating_add(Weight::from_parts(4_907, 0).saturating_mul(l.into()))
			.saturating_add(T::DbWeight::get().reads(1))
	}
	/// Storage: `Did::Did` (r:1 w:0)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2184), added: 4659, mode: `MaxEncodedLen`)
	/// The range of component `l` is `[1, 5242880]`.
	fn signature_verification_ed25519(l: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1459`
		//  Estimated: `5649`
		// Minimum execution time: 75_230_000 picoseconds.
		Weight::from_parts(27_481_992, 0)
			.saturating_add(Weight::from_parts(0, 5649))
			// Standard Error: 2
			.saturating_add(Weight::from_parts(1_936, 0).saturating_mul(l.into()))
			.saturating_add(T::DbWeight::get().reads(1))
	}
	/// Storage: `Did::Did` (r:1 w:0)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2184), added: 4659, mode: `MaxEncodedLen`)
	/// The range of component `l` is `[1, 5242880]`.
	fn signature_verification_ecdsa(l: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1460`
		//  Estimated: `5649`
		// Minimum execution time: 60_869_000 picoseconds.
		Weight::from_parts(46_719_324, 0)
			.saturating_add(Weight::from_parts(0, 5649))
			// Standard Error: 1
			.saturating_add(Weight::from_parts(1_108, 0).saturating_mul(l.into()))
			.saturating_add(T::DbWeight::get().reads(1))
	}
	/// Storage: `Did::Did` (r:1 w:0)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2184), added: 4659, mode: `MaxEncodedLen`)
	fn dispatch_as() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `234`
		//  Estimated: `5649`
		// Minimum execution time: 17_750_000 picoseconds.
		Weight::from_parts(19_420_000, 0)
			.saturating_add(Weight::from_parts(0, 5649))
			.saturating_add(T::DbWeight::get().reads(1))
	}
	/// Storage: `Did::DidBlacklist` (r:1 w:0)
	/// Proof: `Did::DidBlacklist` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2184), added: 4659, mode: `MaxEncodedLen`)
	fn create_from_account() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `42`
		//  Estimated: `5649`
		// Minimum execution time: 14_129_000 picoseconds.
		Weight::from_parts(15_400_000, 0)
			.saturating_add(Weight::from_parts(0, 5649))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}
