// This file is part of CORD – https://cord.network

// Copyright (C) Dhiway Networks Pvt. Ltd.
// SPDX-License-Identifier: GPL-3.0-or-later

// CORD is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// CORD is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with CORD. If not, see <https://www.gnu.org/licenses/>.

//! Autogenerated weights for `pallet_identity`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2024-01-02, STEPS: `5`, REPEAT: `2`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `pi.lan`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: 1024

// Executed Command:
// ./target/release/cord
// benchmark
// pallet
// --chain=dev
// --steps=5
// --repeat=2
// --pallet=pallet_identity
// --extrinsic=*
// --execution=wasm
// --wasm-execution=compiled
// --heap-pages=4096
// --header=./HEADER-GPL3
// --output=./runtime/src/weights/

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_identity`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_identity::WeightInfo for WeightInfo<T> {
	/// Storage: `Identity::Registrars` (r:1 w:1)
	/// Proof: `Identity::Registrars` (`max_values`: Some(1), `max_size`: Some(1026), added: 1521, mode: `MaxEncodedLen`)
	/// The range of component `r` is `[1, 24]`.
	fn add_registrar(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `32 + r * (41 ±0)`
		//  Estimated: `2511`
		// Minimum execution time: 9_000_000 picoseconds.
		Weight::from_parts(10_663_004, 0)
			.saturating_add(Weight::from_parts(0, 2511))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Identity::Registrars` (r:1 w:1)
	/// Proof: `Identity::Registrars` (`max_values`: Some(1), `max_size`: Some(1026), added: 1521, mode: `MaxEncodedLen`)
	/// The range of component `r` is `[1, 24]`.
	fn remove_registrar(r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `32 + r * (41 ±0)`
		//  Estimated: `2511`
		// Minimum execution time: 8_000_000 picoseconds.
		Weight::from_parts(8_658_847, 0)
			.saturating_add(Weight::from_parts(0, 2511))
			// Standard Error: 28_048
			.saturating_add(Weight::from_parts(52_553, 0).saturating_mul(r.into()))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Identity::IdentityOf` (r:1 w:1)
	/// Proof: `Identity::IdentityOf` (`max_values`: None, `max_size`: Some(1683), added: 4158, mode: `MaxEncodedLen`)
	/// The range of component `r` is `[0, 10]`.
	fn set_identity(r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `306 + r * (33 ±0)`
		//  Estimated: `5148`
		// Minimum execution time: 13_000_000 picoseconds.
		Weight::from_parts(13_328_025, 0)
			.saturating_add(Weight::from_parts(0, 5148))
			// Standard Error: 183_682
			.saturating_add(Weight::from_parts(910_828, 0).saturating_mul(r.into()))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Identity::IdentityOf` (r:1 w:1)
	/// Proof: `Identity::IdentityOf` (`max_values`: None, `max_size`: Some(1683), added: 4158, mode: `MaxEncodedLen`)
	/// The range of component `r` is `[1, 25]`.
	/// The range of component `x` is `[0, 10]`.
	fn clear_identity(r: u32, x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `240 + r * (33 ±0) + x * (66 ±0)`
		//  Estimated: `5148`
		// Minimum execution time: 12_000_000 picoseconds.
		Weight::from_parts(10_993_896, 0)
			.saturating_add(Weight::from_parts(0, 5148))
			// Standard Error: 36_386
			.saturating_add(Weight::from_parts(32_411, 0).saturating_mul(r.into()))
			// Standard Error: 85_592
			.saturating_add(Weight::from_parts(307_922, 0).saturating_mul(x.into()))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Identity::Registrars` (r:1 w:0)
	/// Proof: `Identity::Registrars` (`max_values`: Some(1), `max_size`: Some(1026), added: 1521, mode: `MaxEncodedLen`)
	/// Storage: `Identity::IdentityOf` (r:1 w:1)
	/// Proof: `Identity::IdentityOf` (`max_values`: None, `max_size`: Some(1683), added: 4158, mode: `MaxEncodedLen`)
	/// The range of component `r` is `[1, 25]`.
	/// The range of component `x` is `[0, 10]`.
	fn request_judgement(r: u32, x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `230 + r * (41 ±0) + x * (66 ±0)`
		//  Estimated: `5148`
		// Minimum execution time: 14_000_000 picoseconds.
		Weight::from_parts(14_153_151, 0)
			.saturating_add(Weight::from_parts(0, 5148))
			// Standard Error: 38_918
			.saturating_add(Weight::from_parts(62_244, 0).saturating_mul(r.into()))
			// Standard Error: 91_548
			.saturating_add(Weight::from_parts(646_113, 0).saturating_mul(x.into()))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Identity::IdentityOf` (r:1 w:1)
	/// Proof: `Identity::IdentityOf` (`max_values`: None, `max_size`: Some(1683), added: 4158, mode: `MaxEncodedLen`)
	/// The range of component `r` is `[1, 25]`.
	/// The range of component `x` is `[0, 10]`.
	fn cancel_request(_r: u32, x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `273 + x * (66 ±0)`
		//  Estimated: `5148`
		// Minimum execution time: 13_000_000 picoseconds.
		Weight::from_parts(15_074_925, 0)
			.saturating_add(Weight::from_parts(0, 5148))
			// Standard Error: 87_680
			.saturating_add(Weight::from_parts(587_443, 0).saturating_mul(x.into()))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Identity::Registrars` (r:1 w:1)
	/// Proof: `Identity::Registrars` (`max_values`: Some(1), `max_size`: Some(1026), added: 1521, mode: `MaxEncodedLen`)
	/// The range of component `r` is `[1, 24]`.
	fn set_account_id(r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `73 + r * (41 ±0)`
		//  Estimated: `2511`
		// Minimum execution time: 7_000_000 picoseconds.
		Weight::from_parts(6_969_714, 0)
			.saturating_add(Weight::from_parts(0, 2511))
			// Standard Error: 21_974
			.saturating_add(Weight::from_parts(51_662, 0).saturating_mul(r.into()))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Identity::Registrars` (r:1 w:1)
	/// Proof: `Identity::Registrars` (`max_values`: Some(1), `max_size`: Some(1026), added: 1521, mode: `MaxEncodedLen`)
	/// The range of component `r` is `[1, 24]`.
	fn set_fields(r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `73 + r * (41 ±0)`
		//  Estimated: `2511`
		// Minimum execution time: 7_000_000 picoseconds.
		Weight::from_parts(7_078_384, 0)
			.saturating_add(Weight::from_parts(0, 2511))
			// Standard Error: 24_248
			.saturating_add(Weight::from_parts(42_755, 0).saturating_mul(r.into()))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Identity::Registrars` (r:1 w:0)
	/// Proof: `Identity::Registrars` (`max_values`: Some(1), `max_size`: Some(1026), added: 1521, mode: `MaxEncodedLen`)
	/// Storage: `Identity::IdentityOf` (r:1 w:1)
	/// Proof: `Identity::IdentityOf` (`max_values`: None, `max_size`: Some(1683), added: 4158, mode: `MaxEncodedLen`)
	/// The range of component `r` is `[1, 24]`.
	/// The range of component `x` is `[0, 10]`.
	fn provide_judgement(_r: u32, x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `304 + r * (41 ±0) + x * (66 ±0)`
		//  Estimated: `5148`
		// Minimum execution time: 18_000_000 picoseconds.
		Weight::from_parts(19_630_128, 0)
			.saturating_add(Weight::from_parts(0, 5148))
			// Standard Error: 102_511
			.saturating_add(Weight::from_parts(653_280, 0).saturating_mul(x.into()))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Identity::IdentityOf` (r:1 w:1)
	/// Proof: `Identity::IdentityOf` (`max_values`: None, `max_size`: Some(1683), added: 4158, mode: `MaxEncodedLen`)
	/// The range of component `r` is `[1, 25]`.
	/// The range of component `x` is `[0, 10]`.
	fn kill_identity(r: u32, x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `240 + r * (33 ±0) + x * (66 ±0)`
		//  Estimated: `5148`
		// Minimum execution time: 12_000_000 picoseconds.
		Weight::from_parts(11_581_153, 0)
			.saturating_add(Weight::from_parts(0, 5148))
			// Standard Error: 61_288
			.saturating_add(Weight::from_parts(56_813, 0).saturating_mul(r.into()))
			// Standard Error: 144_169
			.saturating_add(Weight::from_parts(217_115, 0).saturating_mul(x.into()))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}
